/* =============================================================
   TEXTOS DA PÁGINA (português do Brasil)
   Substituem os textos em espanhol do index.html.
   {0}, {1}, {2}: valores que a página insere (números, nomes, datas).
   ============================================================= */

window.TEXTOS = {
  locale: "pt-BR",
  errConfig: "Não foi possível ler o config.js. Confira vírgulas e aspas nesse arquivo.",
  horaLocal: "Hora local", cambiarVersion: "Trocar de país", bandera: "Bandeira de {0}",
  calendario: "Calendário", mesAnt: "Mês anterior", mesSig: "Próximo mês", hoy: "Hoje", manana: "Amanhã",
  festivoDe: "Feriado {0}", legPrev: "Feriado previsto", familia: "Família", diaSenalado: "Data especial", evento: "Evento", escolar: "Escola",
  proximas: "Próximas datas", expresiones: "Expressões úteis", repaso: "Revisão", reiniciar: "Zerar aprendidas",
  actualizar: "Atualizar agora", actualizado: "Atualizado às {0} ({1})", tocaCerrar: "Toque para fechar",
  conversor: "Conversor", queConvertir: "O que converter", solAire: "Sol e ar",
  deDiferencia: "de diferença", mismaHora: "mesmo horário", sinConexion: "Sem conexão", sinDatos: "Sem dados",
  horaEn: "{0} em {1}", horaEnPais: "{0} no {1}",
  haceMin: "há {0} min", haceH: "há {0} h", haceDias: "há {0} dias",
  wmo: {
    "0": "Céu limpo", "1": "Predomínio de sol", "2": "Parcialmente nublado", "3": "Nublado", "45": "Neblina", "48": "Neblina com geada",
    "51": "Garoa fraca", "53": "Garoa", "55": "Garoa forte", "56": "Garoa congelante", "57": "Garoa congelante forte",
    "61": "Chuva fraca", "63": "Chuva", "65": "Chuva forte", "66": "Chuva congelante", "67": "Chuva congelante forte",
    "71": "Neve fraca", "73": "Neve", "75": "Neve forte", "77": "Grãos de neve",
    "80": "Pancadas fracas", "81": "Pancadas de chuva", "82": "Pancadas fortes", "85": "Pancadas de neve", "86": "Pancadas de neve fortes",
    "95": "Trovoada", "96": "Trovoada com granizo", "99": "Trovoada com granizo forte"
  },
  max: "Máx", min: "Mín", ahora: "Agora", sensacion: "sensação", lluvia: "chuva", lluviaDia: "Chuva",
  amanece: "nascer do sol", anochece: "pôr do sol", deLuz: "{0} h {1} min de luz", sensMin: "Sens. mín", sinNieve: "Sem neve", nieve: "Neve",
  tiempoEn: "Tempo em {0}", cargandoTiempo: "Carregando o tempo…", horaAHora: "Hoje hora a hora", proximosDias: "Próximos dias",
  prevGuardada: "Sem conexão: previsão salva {0}",
  errTiempo: "Não foi possível carregar o tempo e não há previsão salva. Toque em Atualizar agora.",
  meses: ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
  iniciales: ["S", "T", "Q", "Q", "S", "S", "D"], diaDe: "{0} de {1}", esHoyAria: ", hoje",
  tagFest: "Fer", tagFam: "Fam", tagEvt: "Evt", tagEsc: "Escola", tagDia: "Data",
  rango: "de {0} a {1}", fechaConfirmar: "data a confirmar", datoOnline: "dado on-line", porConfirmar: "a confirmar",
  horaConfirmar: "horário a confirmar",
  fuenteOnline: " · fonte on-line (Nager.Date)", pendConfirmar: ", a confirmar", pendConfirmarCon: ", a confirmar com {0}",
  previsto: " · previsto, sem calendário oficial carregado", pendAprob: " · aguardando aprovação",
  calEscolar: "Calendário escolar", nadaMarcado: "Nada marcado para este dia.", santoral: "Santo do dia:",
  warnFestivos: "Faltam os feriados oficiais de {0} de {1} no config.js.",
  warnFestivosSig: "O calendário de feriados de {0} já deve estar publicado ({1}): adicione ao config.js.",
  warnEscolar: "Falta o calendário escolar{0} do próximo ano no config.js.", deX: " de {0}",
  warnEventos: "Não há mais eventos futuros no config.js.",
  warnPartidos: "Não há mais jogos dos {0}: adicione o calendário da nova temporada ao config.js.",
  stPartidos: "Jogos on-line {0}", stPartidosCopia: "Fonte dos jogos indisponível: usando a cópia de {0}",
  stPartidosConfig: "Fonte dos jogos indisponível: usando os do config.js",
  stFestivos: "Feriados {0} {1} on-line", stSinFestivos: "Fonte de feriados {0} {1} indisponível",
  cambioAdelanta: "Mudança de horário ({0}): relógios uma hora adiantados", cambioRetrasa: "Mudança de horário ({0}): relógios uma hora atrasados",
  desdeHoyDif: "a partir de hoje, {0} h de diferença", desdeHoyMisma: "a partir de hoje, mesmo horário",
  noFechas: "Nenhuma data próxima.", porConfirmarParen: " (a confirmar)", esHoy: "É hoje!", enCurso: "Em andamento",
  mes: "mês", mesesN: "meses", dia: "dia", dias: "dias",
  recuerda: "Lembre-se. ", enNDias: "Em {0} dias",
  felicita: "Dê os parabéns a {0}!", cumpleDe: "Aniversário de {0}",
  aprendidasDe: "Aprendidas: {0} de {1}.", marcaCirculo: "Marque com o círculo as que você já sabe: elas não vão aparecer mais.",
  marcarAprendida: "Marcar como aprendida", aprendidasManana: "Aprendidas: {0}. A partir de amanhã não aparecem mais.",
  confirmReiniciar: "Voltar a incluir todas as expressões marcadas como aprendidas?", tocaVer: "toque para ver",
  dolares: "Dólares", millas: "Milhas", kilometros: "Quilômetros", fahrenheit: "Fahrenheit", celsius: "Celsius",
  libras: "Libras", kilos: "Quilos", onzas: "Onças", gramos: "Gramas", pulgadas: "Polegadas", centimetros: "Centímetros",
  mph: "Milhas por hora", kmh: "Km por hora",
  bMillas: "Milhas / km", bYardas: "Jardas / m", bTazas: "Xícaras / ml", tazas: "Xícaras (cup)", mililitros: "Mililitros", notaTaza: "Xícara de cozinha dos EUA. Nos rótulos nutricionais arredonda-se para 240 ml.", bGalones: "Galões / litros", galones: "Galões", litros: "Litros", notaGalon: "Galão dos EUA (gasolina, leite). O galão britânico tem 4,55 litros.", yardas: "Jardas", metros: "Metros", bLibras: "Libras / quilos", bOnzas: "Onças / gramas", bPulgadas: "Polegadas / cm",
  notaOnza: "Onça de peso. A onça líquida (fl oz) tem 29,57 ml.",
  cargandoCambio: "Carregando a cotação…", bce: "taxa de referência do BCE", tasaGuardada: "sem conexão: cotação salva {0}",
  tasaManual: "sem conexão: cotação manual do config.js, confira", sinCambio: "Sem cotação: não há conexão.",
  uvTxt: ["baixo", "moderado", "alto", "muito alto", "extremo"],
  aqTxt: ["Boa", "Moderada", "Ruim para grupos sensíveis", "Ruim", "Muito ruim", "Perigosa"],
  cargandoAire: "Carregando ar…", cargandoUV: "Carregando índice UV…", errUV: "Não foi possível carregar o índice UV.",
  aire: "Ar {0} · {1}", aireSinDatos: "Ar: sem dados", uvMax: "UV máximo {0} ({1}) por volta das {2} h. ",
  protSi: "Use protetor solar nas horas amarelas ou acima.", protNo: "Não é preciso proteção solar especial.",
  datosGuardados: "Sem conexão: dados salvos {0}. ", uvAria: "Índice UV hora a hora em {0}"
};
