/* =============================================================
   SANTO DO DIA (indicativo)
   Santo ou festa principal de cada dia segundo o calendário
   católico, com as festas próprias do Brasil. Pode variar.
   Formato: "MM-DD": "Santo; outro santo"
   ============================================================= */

window.SANTORAL = {
  "01-01": "Santa Maria, Mãe de Deus",
  "01-02": "São Basílio Magno e São Gregório Nazianzeno",
  "01-03": "Santíssimo Nome de Jesus; Santa Genoveva",
  "01-04": "Santa Ângela de Foligno",
  "01-05": "São João Nepomuceno Neumann",
  "01-06": "Epifania do Senhor (Santos Reis)",
  "01-07": "São Raimundo de Peñafort",
  "01-08": "São Severino; São Máximo",
  "01-09": "São Juliano; Santo Adriano de Cantuária",
  "01-10": "São Gonçalo de Amarante; São Guilherme",
  "01-11": "São Higino, papa",
  "01-12": "São Modesto; Santo Arcádio",
  "01-13": "Santo Hilário de Poitiers",
  "01-14": "São Félix de Nola",
  "01-15": "São Mauro, abade; São Paulo eremita",
  "01-16": "São Marcelo I, papa",
  "01-17": "Santo Antão, abade",
  "01-18": "Santa Margarida da Hungria; Santa Prisca",
  "01-19": "São Mário; São Canuto",
  "01-20": "São Sebastião; São Fabiano",
  "01-21": "Santa Inês",
  "01-22": "São Vicente, diácono",
  "01-23": "Santa Emerenciana; São João Esmoler",
  "01-24": "São Francisco de Sales",
  "01-25": "Conversão de São Paulo",
  "01-26": "São Timóteo e São Tito",
  "01-27": "Santa Ângela Merici",
  "01-28": "São Tomás de Aquino",
  "01-29": "São Valério; São Constâncio",
  "01-30": "Santa Martina; Santa Jacinta Marescotti",
  "01-31": "São João Bosco",
  "02-01": "Santa Viridiana; São Severo",
  "02-02": "Apresentação do Senhor; Nossa Senhora dos Navegantes",
  "02-03": "São Brás",
  "02-04": "São Gilberto; Santa Joana de Valois",
  "02-05": "Santa Águeda",
  "02-06": "São Paulo Miki e companheiros; Santa Doroteia",
  "02-07": "São Ricardo; São Teodoro",
  "02-08": "São Jerônimo Emiliani; Santa Josefina Bakhita",
  "02-09": "Santa Apolônia",
  "02-10": "Santa Escolástica",
  "02-11": "Nossa Senhora de Lourdes",
  "02-12": "Santa Eulália; São Bento de Aniane",
  "02-13": "São Benigno; Santa Fosca",
  "02-14": "São Cirilo e São Metódio; São Valentim",
  "02-15": "São Faustino e São Jovita",
  "02-16": "Santa Juliana",
  "02-17": "Sete Santos Fundadores dos Servitas",
  "02-18": "Santa Bernadete; São Simeão",
  "02-19": "São Conrado de Piacenza",
  "02-20": "São Francisco e Santa Jacinta Marto",
  "02-21": "São Pedro Damião",
  "02-22": "Cátedra de São Pedro",
  "02-23": "São Policarpo",
  "02-24": "São Sérgio; São Modesto",
  "02-25": "São Cesário; São Gerlando",
  "02-26": "São Porfírio; Santo Alexandre",
  "02-27": "São Gabriel das Dores",
  "02-28": "São Romão; Santo Hilário, papa",
  "02-29": "São João Cassiano",
  "03-01": "Santo Albino; São Félix III, papa",
  "03-02": "Santa Inês da Boêmia",
  "03-03": "Santa Cunegundes",
  "03-04": "São Casimiro; São Lúcio",
  "03-05": "São João José da Cruz; Santo Adriano",
  "03-06": "Santa Coleta; São Marciano",
  "03-07": "Santas Perpétua e Felicidade",
  "03-08": "São João de Deus",
  "03-09": "Santa Francisca Romana; São Domingos Sávio",
  "03-10": "São Simplício, papa; São Macário",
  "03-11": "São Constantino; São Sofrônio",
  "03-12": "São Maximiliano; São Luís Orione",
  "03-13": "Santa Patrícia; Santa Eufrásia",
  "03-14": "Santa Matilde",
  "03-15": "Santa Luísa de Marillac; São Longuinho",
  "03-16": "São Heriberto; Santo Hilário de Aquileia",
  "03-17": "São Patrício",
  "03-18": "São Cirilo de Jerusalém",
  "03-19": "São José",
  "03-20": "São Cláudio; Santa Alexandra",
  "03-21": "São Nicolau de Flüe; São Serapião",
  "03-22": "Santa Lea; São Benvenuto",
  "03-23": "São Turíbio de Mogrovejo; Santa Rebeca",
  "03-24": "Santa Catarina da Suécia; São Rômulo",
  "03-25": "Anunciação do Senhor",
  "03-26": "São Teodoro; São Emanuel",
  "03-27": "São Ruperto; Santa Augusta",
  "03-28": "São Sisto III, papa; São Castor",
  "03-29": "São Segundo; São Bertoldo",
  "03-30": "São João Clímaco; São Leonardo Murialdo",
  "03-31": "São Benjamim; Santa Balbina",
  "04-01": "Santo Hugo; São Valerico",
  "04-02": "São Francisco de Paula",
  "04-03": "São Ricardo; São Sisto I, papa",
  "04-04": "Santo Isidoro de Sevilha",
  "04-05": "São Vicente Ferrer",
  "04-06": "São Guilherme; São Prudêncio",
  "04-07": "São João Batista de La Salle",
  "04-08": "São Dionísio; Santa Júlia Billiart",
  "04-09": "Santa Maria de Cléofas; São Demétrio",
  "04-10": "São Terêncio; Santo Ezequiel",
  "04-11": "Santo Estanislau; Santa Gema Galgani",
  "04-12": "São Júlio I, papa; São Zenão de Verona",
  "04-13": "São Martinho I, papa; Santo Hermenegildo",
  "04-14": "São Lamberto; Santa Lidvina",
  "04-15": "Santa Anastácia; São Damião de Veuster",
  "04-16": "Santa Bernadete Soubirous; São Bento José Labre",
  "04-17": "Santo Aniceto, papa; São Roberto",
  "04-18": "São Galdino; Santo Apolônio",
  "04-19": "Santa Ema; São Leão IX, papa",
  "04-20": "Santa Inês de Montepulciano",
  "04-21": "Santo Anselmo",
  "04-22": "São Caio, papa; São Sotero",
  "04-23": "São Jorge; Santo Adalberto",
  "04-24": "São Fidélis de Sigmaringen",
  "04-25": "São Marcos, evangelista",
  "04-26": "São Cleto, papa; São Marcelino",
  "04-27": "Santa Zita; São Liberal",
  "04-28": "São Pedro Chanel; São Luís Maria Grignion de Montfort",
  "04-29": "Santa Catarina de Sena",
  "04-30": "São Pio V, papa",
  "05-01": "São José Operário",
  "05-02": "Santo Atanásio",
  "05-03": "São Filipe e São Tiago, apóstolos",
  "05-04": "São Ciríaco; São Floriano",
  "05-05": "São Godofredo; Santa Irene",
  "05-06": "São Domingos Sávio; Santa Judite",
  "05-07": "Santa Flávia Domitila",
  "05-08": "Nossa Senhora do Rosário de Pompeia; São Vítor",
  "05-09": "São Pacômio; São Gregório de Óstia",
  "05-10": "Santo Antonino; São João de Ávila",
  "05-11": "Santo Inácio de Laconi; São Fábio",
  "05-12": "São Nereu e Santo Aquiles; São Pancrácio",
  "05-13": "Nossa Senhora de Fátima",
  "05-14": "São Matias, apóstolo",
  "05-15": "Santo Isidoro Lavrador; São Torquato",
  "05-16": "Santo Ubaldo; São Simão Stock",
  "05-17": "São Pascoal Bailão",
  "05-18": "São João I, papa; São Félix de Cantalice",
  "05-19": "São Celestino V, papa; Santo Ivo",
  "05-20": "São Bernardino de Sena",
  "05-21": "São Cristóvão Magalhães e companheiros",
  "05-22": "Santa Rita de Cássia",
  "05-23": "São Desidério; São João Batista de Rossi",
  "05-24": "Nossa Senhora Auxiliadora",
  "05-25": "São Beda; São Gregório VII, papa; Santa Maria Madalena de Pazzi",
  "05-26": "São Filipe Néri",
  "05-27": "Santo Agostinho de Cantuária",
  "05-28": "Santo Emílio; São Germano",
  "05-29": "São Paulo VI, papa; São Maximino",
  "05-30": "Santa Joana d'Arc; São Fernando",
  "05-31": "Visitação de Nossa Senhora",
  "06-01": "São Justino, mártir",
  "06-02": "São Marcelino e São Pedro",
  "06-03": "São Carlos Lwanga e companheiros",
  "06-04": "São Francisco Caracciolo; São Quirino",
  "06-05": "São Bonifácio",
  "06-06": "São Norberto; São Cláudio",
  "06-07": "Santo Antônio Maria Gianelli; São Roberto",
  "06-08": "São Medardo",
  "06-09": "São José de Anchieta; Santo Efrém",
  "06-10": "Beata Diana; São Landerico",
  "06-11": "São Barnabé, apóstolo",
  "06-12": "São Guido; São Gaspar Bertoni",
  "06-13": "Santo Antônio de Pádua (de Lisboa)",
  "06-14": "São Eliseu; São Valério",
  "06-15": "São Vito; Santa Germana",
  "06-16": "São Quirico e Santa Julita",
  "06-17": "São Ranieri; Santo Avito",
  "06-18": "São Gregório Barbarigo; Santa Marina",
  "06-19": "São Romualdo; São Gervásio e São Protásio",
  "06-20": "São Silvério, papa; Santa Florentina",
  "06-21": "São Luís Gonzaga",
  "06-22": "São Paulino de Nola; São João Fisher e São Tomás More",
  "06-23": "São José Cafasso; Santa Agripina",
  "06-24": "Natividade de São João Batista",
  "06-25": "São Guilherme de Vercelli; São Máximo",
  "06-26": "São Vigílio; São Josemaria Escrivá",
  "06-27": "São Cirilo de Alexandria",
  "06-28": "Santo Ireneu de Lião",
  "06-29": "São Pedro e São Paulo",
  "06-30": "Santos Primeiros Mártires da Igreja de Roma",
  "07-01": "São Teobaldo; Santo Aarão",
  "07-02": "São Bernardino Realino; São Otão",
  "07-03": "São Tomé, apóstolo",
  "07-04": "Santa Isabel de Portugal; São Pier Giorgio Frassati",
  "07-05": "Santo Antônio Maria Zaccaria",
  "07-06": "Santa Maria Goretti",
  "07-07": "São Cláudio; São Panteno",
  "07-08": "São Áquila e Santa Priscila",
  "07-09": "Santa Paulina do Coração Agonizante de Jesus; Santa Verônica Giuliani",
  "07-10": "Santas Rufina e Segunda",
  "07-11": "São Bento de Núrsia",
  "07-12": "São Fortunato; São João Gualberto",
  "07-13": "Santo Henrique; Santo Eugênio",
  "07-14": "São Camilo de Lellis",
  "07-15": "São Boaventura",
  "07-16": "Nossa Senhora do Carmo",
  "07-17": "Santo Aleixo; Santa Marcelina",
  "07-18": "São Frederico; Santa Marina",
  "07-19": "Santo Arsênio; Santa Macrina",
  "07-20": "Santo Elias, profeta; Santo Apolinário",
  "07-21": "São Lourenço de Brindisi; Santa Praxedes",
  "07-22": "Santa Maria Madalena",
  "07-23": "Santa Brígida da Suécia",
  "07-24": "Santa Cristina; São Charbel Makhlouf",
  "07-25": "São Tiago, apóstolo; São Cristóvão",
  "07-26": "São Joaquim e Santa Ana",
  "07-27": "São Pantaleão; Santa Natália",
  "07-28": "São Nazário e São Celso; São Vítor I, papa",
  "07-29": "Santa Marta, Santa Maria e São Lázaro",
  "07-30": "São Pedro Crisólogo",
  "07-31": "Santo Inácio de Loyola",
  "08-01": "Santo Afonso Maria de Ligório",
  "08-02": "Santo Eusébio de Vercelli; São Pedro Julião Eymard",
  "08-03": "Santa Lídia; Santo Aspreno",
  "08-04": "São João Maria Vianney, Cura d'Ars",
  "08-05": "Nossa Senhora das Neves",
  "08-06": "Transfiguração do Senhor",
  "08-07": "São Caetano; São Sisto II, papa",
  "08-08": "São Domingos de Gusmão",
  "08-09": "Santa Teresa Benedita da Cruz (Edith Stein)",
  "08-10": "São Lourenço, mártir",
  "08-11": "Santa Clara de Assis",
  "08-12": "Santa Joana Francisca de Chantal",
  "08-13": "Santa Dulce dos Pobres; São Ponciano e Santo Hipólito",
  "08-14": "São Maximiliano Kolbe",
  "08-15": "Assunção de Nossa Senhora",
  "08-16": "São Roque; Santo Estêvão da Hungria",
  "08-17": "São Jacinto; Santa Clara da Cruz",
  "08-18": "Santa Helena",
  "08-19": "São João Eudes",
  "08-20": "São Bernardo de Claraval",
  "08-21": "São Pio X, papa",
  "08-22": "Nossa Senhora Rainha",
  "08-23": "Santa Rosa de Lima",
  "08-24": "São Bartolomeu, apóstolo",
  "08-25": "São Luís, rei da França; São José de Calasanz",
  "08-26": "Santo Alexandre de Bérgamo; Santa Teresa de Jesus Jornet",
  "08-27": "Santa Mônica",
  "08-28": "Santo Agostinho",
  "08-29": "Martírio de São João Batista; Santa Sabina",
  "08-30": "São Félix e Santo Adauto",
  "08-31": "São Raimundo Nonato; Santo Aristides",
  "09-01": "Santo Egídio",
  "09-02": "Santo Elpídio; Santa Ingrid",
  "09-03": "São Gregório Magno",
  "09-04": "Santa Rosália; Santa Rosa de Viterbo",
  "09-05": "Santa Teresa de Calcutá",
  "09-06": "São Zacarias, profeta",
  "09-07": "Santa Regina; São Grato",
  "09-08": "Natividade de Nossa Senhora",
  "09-09": "São Pedro Claver; São Sérgio I, papa",
  "09-10": "São Nicolau de Tolentino",
  "09-11": "São Proto e São Jacinto",
  "09-12": "Santíssimo Nome de Maria",
  "09-13": "São João Crisóstomo",
  "09-14": "Exaltação da Santa Cruz",
  "09-15": "Nossa Senhora das Dores",
  "09-16": "São Cornélio e São Cipriano",
  "09-17": "São Roberto Belarmino; Santa Hildegarda de Bingen",
  "09-18": "São José de Cupertino",
  "09-19": "São Januário",
  "09-20": "Santo André Kim Taegon e companheiros",
  "09-21": "São Mateus, apóstolo e evangelista",
  "09-22": "São Maurício; São Tomás de Vilanova",
  "09-23": "São Pio de Pietrelcina",
  "09-24": "Nossa Senhora das Mercês; São Pacífico",
  "09-25": "São Cléofas; São Sérgio de Radonej",
  "09-26": "São Cosme e São Damião",
  "09-27": "São Vicente de Paulo",
  "09-28": "São Venceslau; São Lourenço Ruiz e companheiros",
  "09-29": "São Miguel, São Gabriel e São Rafael, arcanjos",
  "09-30": "São Jerônimo",
  "10-01": "Santa Teresinha do Menino Jesus",
  "10-02": "Santos Anjos da Guarda",
  "10-03": "Santos Mártires de Cunhaú e Uruaçu; São Gerardo",
  "10-04": "São Francisco de Assis",
  "10-05": "São Plácido; Santa Faustina Kowalska",
  "10-06": "São Bruno",
  "10-07": "Nossa Senhora do Rosário",
  "10-08": "Santa Reparata; Santa Pelágia",
  "10-09": "São Dionísio e companheiros; São João Leonardi",
  "10-10": "São Daniel Comboni; São Francisco de Borja",
  "10-11": "São João XXIII, papa",
  "10-12": "Nossa Senhora Aparecida, padroeira do Brasil",
  "10-13": "Santo Eduardo; São Teófilo",
  "10-14": "São Calisto I, papa",
  "10-15": "Santa Teresa de Ávila",
  "10-16": "Santa Margarida Maria Alacoque; Santa Edwiges",
  "10-17": "Santo Inácio de Antioquia",
  "10-18": "São Lucas, evangelista",
  "10-19": "São Paulo da Cruz; São Pedro de Alcântara",
  "10-20": "Santa Irene; Santa Adelina",
  "10-21": "Santa Úrsula; São Gaspar del Bufalo",
  "10-22": "São João Paulo II, papa",
  "10-23": "São João de Capistrano",
  "10-24": "Santo Antônio Maria Claret",
  "10-25": "Santo Antônio de Sant'Ana Galvão (Frei Galvão); Santos Crisanto e Daria",
  "10-26": "Santo Evaristo, papa",
  "10-27": "São Florêncio; Santa Sabina",
  "10-28": "São Simão e São Judas Tadeu, apóstolos",
  "10-29": "Santa Ermelinda; São Narciso",
  "10-30": "São Germano de Cápua; São Marciano",
  "10-31": "São Quintino; Santo Afonso Rodrigues",
  "11-01": "Todos os Santos",
  "11-02": "Finados (Comemoração dos Fiéis Defuntos)",
  "11-03": "São Martinho de Lima; Santa Sílvia",
  "11-04": "São Carlos Borromeu",
  "11-05": "São Zacarias e Santa Isabel",
  "11-06": "São Leonardo",
  "11-07": "São Prosdócimo; São Ernesto",
  "11-08": "São Godofredo; Santos Quatro Coroados",
  "11-09": "Dedicação da Basílica de Latrão",
  "11-10": "São Leão Magno, papa",
  "11-11": "São Martinho de Tours",
  "11-12": "São Josafá",
  "11-13": "Santo Homem Bom; São Diogo",
  "11-14": "São Jocundo; São Lourenço O'Toole",
  "11-15": "Santo Alberto Magno",
  "11-16": "Santa Margarida da Escócia; Santa Gertrudes",
  "11-17": "Santa Isabel da Hungria",
  "11-18": "Dedicação das Basílicas de São Pedro e São Paulo",
  "11-19": "São Fausto; São Abdias",
  "11-20": "São Otávio; Santo Edmundo",
  "11-21": "Apresentação de Nossa Senhora",
  "11-22": "Santa Cecília",
  "11-23": "São Clemente I, papa; São Columbano",
  "11-24": "Santo André Dung-Lac e companheiros",
  "11-25": "Santa Catarina de Alexandria",
  "11-26": "São Leonardo de Porto Maurício; São Conrado",
  "11-27": "Nossa Senhora das Graças (Medalha Milagrosa); São Virgílio",
  "11-28": "São Tiago da Marca",
  "11-29": "São Saturnino",
  "11-30": "Santo André, apóstolo",
  "12-01": "Santo Elói; Santo Ansano",
  "12-02": "Santa Bibiana",
  "12-03": "São Francisco Xavier",
  "12-04": "Santa Bárbara; São João Damasceno",
  "12-05": "São Sabas; São Júlio",
  "12-06": "São Nicolau",
  "12-07": "Santo Ambrósio",
  "12-08": "Imaculada Conceição",
  "12-09": "São Juan Diego; São Siro",
  "12-10": "Nossa Senhora de Loreto",
  "12-11": "São Dâmaso I, papa",
  "12-12": "Nossa Senhora de Guadalupe",
  "12-13": "Santa Luzia",
  "12-14": "São João da Cruz",
  "12-15": "Santa Virgínia Centurione Bracelli; São Valeriano",
  "12-16": "Santa Adelaide; Santa Albina",
  "12-17": "São Lázaro; São João da Mata",
  "12-18": "Nossa Senhora do Ó; São Graciano",
  "12-19": "Santo Anastácio I, papa; São Urbano V, papa",
  "12-20": "São Liberato; São Domingos de Silos",
  "12-21": "São Pedro Canísio",
  "12-22": "Santa Francisca Xavier Cabrini",
  "12-23": "São João Câncio; Santa Vitória",
  "12-24": "Santa Adélia; Santa Irmina",
  "12-25": "Natal do Senhor",
  "12-26": "Santo Estêvão, primeiro mártir",
  "12-27": "São João, apóstolo e evangelista",
  "12-28": "Santos Inocentes, mártires",
  "12-29": "São Tomás Becket; São Davi, rei",
  "12-30": "São Rogério; Santo Eugênio",
  "12-31": "São Silvestre I, papa"
};
