/* =============================================================
   EXPRESIONES DEL DÍA
   Una por día, en orden; al acabar la lista vuelve a empezar.
   Para añadir una, copia una línea completa y cambia el texto.
   en: expresión en inglés · es: traducción
   ej: ejemplo en inglés · ejEs: traducción del ejemplo
   ============================================================= */

window.PALABRAS = [
  { en: "How's it going?", es: "¿Qué tal?", ej: "Hey, how's it going?", ejEs: "Hola, ¿qué tal?" },
  { en: "No worries", es: "No pasa nada / Tranquilo", ej: "Sorry I'm late. — No worries!", ejEs: "Perdona el retraso. — ¡No pasa nada!" },
  { en: "I'm running late", es: "Llego tarde / Voy con retraso", ej: "I'm running late, I'll be there in ten.", ejEs: "Voy con retraso, llego en diez minutos." },
  { en: "To grab a bite", es: "Picar algo / Comer algo rápido", ej: "Want to grab a bite after class?", ejEs: "¿Quieres comer algo después de clase?" },
  { en: "To-go / For here", es: "Para llevar / Para tomar aquí", ej: "Is that for here or to-go?", ejEs: "¿Es para tomar aquí o para llevar?" },
  { en: "Check, please", es: "La cuenta, por favor", ej: "Could we get the check, please?", ejEs: "¿Nos trae la cuenta, por favor?" },
  { en: "Tip", es: "Propina", ej: "Is the tip included?", ejEs: "¿La propina está incluida?" },
  { en: "Receipt", es: "Ticket / Recibo", ej: "Do you need the receipt?", ejEs: "¿Necesitas el ticket?" },
  { en: "Paper or plastic?", es: "¿Bolsa de papel o de plástico?", ej: "Paper or plastic? — Paper, please.", ejEs: "¿Papel o plástico? — Papel, por favor." },
  { en: "Aisle", es: "Pasillo (de supermercado)", ej: "The milk is in aisle five.", ejEs: "La leche está en el pasillo cinco." },
  { en: "On sale", es: "En oferta / Rebajado", ej: "These boots are on sale this week.", ejEs: "Estas botas están rebajadas esta semana." },
  { en: "Pharmacy / Drugstore", es: "Farmacia", ej: "Is there a drugstore nearby?", ejEs: "¿Hay una farmacia cerca?" },
  { en: "Over-the-counter", es: "Sin receta", ej: "You can buy it over-the-counter.", ejEs: "Lo puedes comprar sin receta." },
  { en: "Prescription", es: "Receta médica", ej: "I need to pick up my prescription.", ejEs: "Tengo que recoger mi receta." },
  { en: "Appointment", es: "Cita", ej: "I'd like to make an appointment.", ejEs: "Quería pedir una cita." },
  { en: "Gas station", es: "Gasolinera", ej: "Let's stop at the gas station.", ejEs: "Paremos en la gasolinera." },
  { en: "Fill it up", es: "Llénalo / Lleno, por favor", ej: "Fill it up with regular, please.", ejEs: "Lleno de normal, por favor." },
  { en: "Snowplow", es: "Quitanieves", ej: "The snowplow hasn't come yet.", ejEs: "Todavía no ha pasado el quitanieves." },
  { en: "Black ice", es: "Placas de hielo en la carretera", ej: "Drive slowly, there's black ice.", ejEs: "Conduce despacio, hay placas de hielo." },
  { en: "Snow day", es: "Día sin clase por la nieve", ej: "School is closed, it's a snow day!", ejEs: "No hay colegio, ¡día de nieve!" },
  { en: "Bundle up", es: "Abrígate bien", ej: "Bundle up, it's freezing outside.", ejEs: "Abrígate bien, fuera hace un frío que pela." },
  { en: "It's freezing", es: "Hace un frío que pela", ej: "It's freezing this morning!", ejEs: "¡Hace un frío que pela esta mañana!" },
  { en: "Mittens", es: "Manoplas", ej: "Don't forget your mittens.", ejEs: "No olvides las manoplas." },
  { en: "Shovel the driveway", es: "Quitar la nieve de la entrada", ej: "I have to shovel the driveway first.", ejEs: "Primero tengo que quitar la nieve de la entrada." },
  { en: "Up North", es: "El norte de Michigan (así lo llaman allí)", ej: "We're going Up North for the weekend.", ejEs: "Nos vamos al norte el fin de semana." },
  { en: "The Mitten", es: "Michigan (por su forma de manopla)", ej: "Welcome to the Mitten!", ejEs: "¡Bienvenida a Michigan!" },
  { en: "Pop", es: "Refresco (en Michigan se dice pop, no soda)", ej: "Do you want a pop?", ejEs: "¿Quieres un refresco?" },
  { en: "Party store", es: "Tienda de barrio con bebidas (típico de Michigan)", ej: "I'll stop by the party store.", ejEs: "Paso por la tienda." },
  { en: "Tailgate", es: "Comida en el aparcamiento antes de un partido", ej: "Are you coming to the tailgate?", ejEs: "¿Vienes a la comida antes del partido?" },
  { en: "Hang out", es: "Quedar / Pasar el rato", ej: "Do you want to hang out on Saturday?", ejEs: "¿Quieres quedar el sábado?" },
  { en: "To catch up", es: "Ponerse al día", ej: "Let's call this weekend and catch up.", ejEs: "Llamémonos este fin de semana y nos ponemos al día." },
  { en: "To miss someone", es: "Echar de menos a alguien", ej: "I miss you guys so much.", ejEs: "Os echo mucho de menos." },
  { en: "Homesick", es: "Con morriña / Echando de menos casa", ej: "I feel a bit homesick today.", ejEs: "Hoy tengo un poco de morriña." },
  { en: "To figure out", es: "Averiguar / Resolver", ej: "I'll figure it out.", ejEs: "Ya lo resolveré." },
  { en: "To look forward to", es: "Tener ganas de", ej: "I'm looking forward to the weekend.", ejEs: "Tengo ganas de que llegue el fin de semana." },
  { en: "To run errands", es: "Hacer recados", ej: "I have to run some errands this afternoon.", ejEs: "Esta tarde tengo que hacer unos recados." },
  { en: "To give someone a ride", es: "Llevar a alguien en coche", ej: "Can you give me a ride home?", ejEs: "¿Me llevas a casa?" },
  { en: "To pick someone up", es: "Recoger a alguien", ej: "I'll pick you up at seven.", ejEs: "Te recojo a las siete." },
  { en: "Sounds good", es: "Me parece bien / Vale", ej: "Dinner at six? — Sounds good.", ejEs: "¿Cenamos a las seis? — Vale." },
  { en: "I'm down", es: "Me apunto", ej: "Movie tonight? — I'm down.", ejEs: "¿Peli esta noche? — Me apunto." },
  { en: "My bad", es: "Culpa mía", ej: "My bad, I forgot to text you.", ejEs: "Culpa mía, se me olvidó escribirte." },
  { en: "Never mind", es: "Da igual / Olvídalo", ej: "Never mind, I found it.", ejEs: "Da igual, ya lo he encontrado." },
  { en: "It's up to you", es: "Como tú quieras / Tú decides", ej: "Pizza or burgers? It's up to you.", ejEs: "¿Pizza o hamburguesas? Tú decides." },
  { en: "Take your time", es: "Tómate tu tiempo / Sin prisa", ej: "No rush, take your time.", ejEs: "Sin prisa, tómate tu tiempo." },
  { en: "To be broke", es: "Estar sin dinero / Estar pelado", ej: "I can't go, I'm broke this month.", ejEs: "No puedo ir, este mes estoy sin blanca." },
  { en: "A piece of cake", es: "Pan comido", ej: "The test was a piece of cake.", ejEs: "El examen fue pan comido." },
  { en: "Break a leg", es: "¡Mucha suerte! (antes de una actuación)", ej: "Break a leg tonight!", ejEs: "¡Mucha suerte esta noche!" },
  { en: "Under the weather", es: "Pachucho / Algo enfermo", ej: "I'm feeling a bit under the weather.", ejEs: "Estoy un poco pachucha." },
  { en: "To call it a day", es: "Dar por terminado el día", ej: "I'm tired, let's call it a day.", ejEs: "Estoy cansada, dejémoslo por hoy." },
  { en: "Sleep in", es: "Dormir hasta tarde", ej: "I'm going to sleep in on Sunday.", ejEs: "El domingo voy a dormir hasta tarde." },
  { en: "Leftovers", es: "Sobras", ej: "We're having leftovers tonight.", ejEs: "Esta noche cenamos sobras." },
  { en: "Potluck", es: "Comida donde cada uno lleva un plato", ej: "Bring a dish to the potluck.", ejEs: "Trae un plato a la comida compartida." },
  { en: "Thanksgiving dinner", es: "La cena de Acción de Gracias", ej: "Are you coming to Thanksgiving dinner?", ejEs: "¿Vienes a la cena de Acción de Gracias?" },
  { en: "To go Dutch", es: "Pagar a medias / Cada uno lo suyo", ej: "Let's go Dutch on dinner.", ejEs: "Paguemos la cena a medias." },
  { en: "It's on me", es: "Invito yo", ej: "Put your wallet away, it's on me.", ejEs: "Guarda la cartera, invito yo." },
  { en: "Can I get…?", es: "¿Me pones…? (para pedir)", ej: "Can I get a medium coffee?", ejEs: "¿Me pones un café mediano?" },
  { en: "Refill", es: "Rellenar la bebida (muchas veces gratis)", ej: "Can I get a refill?", ejEs: "¿Me la puede rellenar?" },
  { en: "Restroom", es: "Baño / Aseo", ej: "Where's the restroom?", ejEs: "¿Dónde está el baño?" },
  { en: "Line", es: "Cola / Fila", ej: "Is this the line for tickets?", ejEs: "¿Es esta la cola para las entradas?" },
  { en: "Downtown", es: "El centro (de la ciudad)", ej: "Let's meet downtown.", ejEs: "Quedamos en el centro." },
  { en: "Blocks away", es: "A unas manzanas", ej: "It's just two blocks away.", ejEs: "Está a solo dos manzanas." },
  { en: "Mailbox", es: "Buzón", ej: "Check the mailbox, please.", ejEs: "Mira el buzón, por favor." },
  { en: "Package", es: "Paquete", ej: "My package was left on the porch.", ejEs: "Me dejaron el paquete en el porche." },
  { en: "Laundromat", es: "Lavandería", ej: "The laundromat is open 24 hours.", ejEs: "La lavandería abre 24 horas." },
  { en: "Northern lights", es: "Auroras boreales", ej: "We saw the northern lights last night!", ejEs: "¡Anoche vimos auroras boreales!" },
  { en: "Deer season", es: "Temporada de caza del ciervo", ej: "Wear orange in the woods, it's deer season.", ejEs: "Ponte algo naranja en el bosque, es temporada de caza." },
  { en: "Cottage", es: "Casa de campo / Casa del lago", ej: "They have a cottage on the lake.", ejEs: "Tienen una casa en el lago." },
  { en: "Have a good one!", es: "¡Que vaya bien! (despedida)", ej: "Thanks! Have a good one!", ejEs: "¡Gracias! ¡Que vaya bien!" }
];

/* =============================================================
   FRASE CARIÑOSA DEL DÍA (arriba del todo)
   Una por día, en orden. en: inglés · es: español
   ============================================================= */
window.FRASES = [
  { en: "We're so proud of you.", es: "Estamos muy orgullosos de ti." },
  { en: "You've got this.", es: "Tú puedes con esto." },
  { en: "Thinking of you today.", es: "Hoy pensamos en ti." },
  { en: "Distance means so little when someone means so much.", es: "La distancia importa poco cuando alguien importa tanto." },
  { en: "Every day is one day closer.", es: "Cada día es un día menos." },
  { en: "Be brave, be kind, be you.", es: "Sé valiente, sé buena, sé tú." },
  { en: "Home is wherever you are loved.", es: "Tu casa está donde te quieren." },
  { en: "Enjoy every moment of this adventure.", es: "Disfruta cada momento de esta aventura." },
  { en: "You make us smile from far away.", es: "Nos haces sonreír desde lejos." },
  { en: "Small steps every day.", es: "Pequeños pasos cada día." },
  { en: "We miss you, and we're cheering for you.", es: "Te echamos de menos y te animamos desde aquí." },
  { en: "Trust yourself. You know more than you think.", es: "Confía en ti. Sabes más de lo que crees." },
  { en: "It's okay to have a hard day.", es: "Está bien tener un día difícil." },
  { en: "Keep being curious.", es: "Sigue siendo curiosa." },
  { en: "Today is a good day to learn something new.", es: "Hoy es un buen día para aprender algo nuevo." },
  { en: "You are stronger than you know.", es: "Eres más fuerte de lo que crees." },
  { en: "Sending you a big hug across the ocean.", es: "Te mandamos un abrazo enorme al otro lado del océano." },
  { en: "Be proud of how far you've come.", es: "Siéntete orgullosa de lo lejos que has llegado." },
  { en: "Make today count.", es: "Haz que hoy cuente." },
  { en: "Smile, it suits you.", es: "Sonríe, te queda genial." },
  { en: "One day at a time.", es: "Día a día." },
  { en: "You belong wherever you choose to shine.", es: "Encajas allí donde decides brillar." },
  { en: "Say yes to new things.", es: "Di que sí a cosas nuevas." },
  { en: "Mistakes mean you're trying.", es: "Equivocarse significa que lo estás intentando." },
  { en: "We love you to the moon and back.", es: "Te queremos hasta la luna y vuelta." },
  { en: "Take care of yourself today.", es: "Cuídate hoy." },
  { en: "Your courage inspires us.", es: "Tu valentía nos inspira." },
  { en: "Good things are coming.", es: "Vienen cosas buenas." },
  { en: "Call us whenever you want. Always.", es: "Llámanos cuando quieras. Siempre." },
  { en: "The best stories start far from home.", es: "Las mejores historias empiezan lejos de casa." }
];

/* =============================================================
   PALABRAS DE LA ESTACIÓN (cambian solas según el mes)
   otoño: sep-nov · invierno: dic-feb · primavera: mar-may · verano: jun-ago
   ============================================================= */
window.ESTACIONES = {
  otono: [
    { en: "Fall", es: "Otoño (en EE. UU. casi nunca dicen autumn)" },
    { en: "Leaves / Fall colors", es: "Hojas / Colores del otoño" },
    { en: "Rake", es: "Rastrillo / Rastrillar" },
    { en: "Pumpkin patch", es: "Campo de calabazas" },
    { en: "Corn maze", es: "Laberinto de maíz" },
    { en: "Apple cider", es: "Zumo de manzana sin filtrar (típico de otoño)" },
    { en: "Hayride", es: "Paseo en remolque con paja" },
    { en: "Trick-or-treat", es: "Truco o trato" },
    { en: "Costume", es: "Disfraz" },
    { en: "Turkey / Stuffing", es: "Pavo / Relleno" },
    { en: "Black Friday", es: "Día de rebajas tras Thanksgiving" },
    { en: "Sweater weather", es: "Tiempo de jersey" },
    { en: "Chilly", es: "Fresquito / Frío" },
    { en: "Frost", es: "Escarcha / Helada" },
    { en: "Acorn", es: "Bellota" },
    { en: "Maple tree", es: "Arce" },
    { en: "Foliage", es: "Follaje" },
    { en: "Haunted house", es: "Casa del terror" },
    { en: "Candy corn", es: "Caramelos de Halloween con forma de maíz" },
    { en: "Jack-o'-lantern", es: "Calabaza tallada con vela" },
    { en: "Pumpkin pie", es: "Tarta de calabaza" },
    { en: "Leftovers", es: "Sobras (las de Thanksgiving duran días)" },
    { en: "Flannel", es: "Camisa de franela" },
    { en: "Bonfire", es: "Hoguera" },
    { en: "Harvest", es: "Cosecha" },
    { en: "Scarecrow", es: "Espantapájaros" },
    { en: "Squirrel", es: "Ardilla" },
    { en: "Chipmunk", es: "Ardilla listada" },
    { en: "Deer", es: "Ciervo" },
    { en: "Hunting season", es: "Temporada de caza" },
    { en: "Blaze orange", es: "Naranja fluorescente (se lleva en el bosque en temporada de caza)" },
    { en: "Cider mill", es: "Lagar de sidra con tienda (muy típico de Michigan)" },
    { en: "Cider donuts", es: "Donuts de sidra" },
    { en: "Gourd", es: "Calabaza decorativa" },
    { en: "Caramel apple", es: "Manzana de caramelo" },
    { en: "Cranberry sauce", es: "Salsa de arándanos rojos" },
    { en: "Mashed potatoes", es: "Puré de patatas" },
    { en: "Gravy", es: "Salsa de carne" },
    { en: "Sweet potato", es: "Boniato" },
    { en: "Pecan pie", es: "Tarta de nueces pecanas" },
    { en: "Wishbone", es: "Espoleta del pavo (se rompe entre dos y se pide un deseo)" },
    { en: "Parade", es: "Desfile" },
    { en: "Football season", es: "Temporada de fútbol americano" },
    { en: "Tailgating", es: "Comer en el aparcamiento antes del partido" },
    { en: "Hoodie", es: "Sudadera con capucha" },
    { en: "Scarf", es: "Bufanda" },
    { en: "Overcast", es: "Cubierto / Nublado" },
    { en: "Drizzle", es: "Llovizna" },
    { en: "Gusty", es: "Con rachas de viento" },
    { en: "Dusk", es: "Anochecer" },
    { en: "Fall back", es: "Atrasar el reloj (cambio de hora de otoño)" },
    { en: "Veterans Day", es: "Día de los Veteranos (11 de noviembre)" },
    { en: "Election Day", es: "Día de elecciones (noviembre)" },
    { en: "Pilgrims", es: "Los peregrinos (historia de Thanksgiving)" },
    { en: "Grateful", es: "Agradecido/a" },
    { en: "Cozy", es: "Acogedor / Calentito" },
    { en: "Pumpkin spice", es: "Especias de calabaza (sabor estrella del otoño)" },
    { en: "Bare trees", es: "Árboles desnudos" },
    { en: "Fog", es: "Niebla" },
    { en: "Mushroom", es: "Seta" }
  ],
  invierno: [
    { en: "Snowstorm / Blizzard", es: "Tormenta de nieve / Ventisca" },
    { en: "Snowflake", es: "Copo de nieve" },
    { en: "Sleet", es: "Aguanieve" },
    { en: "Icicle", es: "Carámbano" },
    { en: "Slippery", es: "Resbaladizo" },
    { en: "Wind chill", es: "Sensación térmica por el viento" },
    { en: "Snow boots", es: "Botas de nieve" },
    { en: "Sledding", es: "Tirarse en trineo" },
    { en: "Snowman", es: "Muñeco de nieve" },
    { en: "Hot cocoa", es: "Chocolate caliente" },
    { en: "Winter break", es: "Vacaciones de Navidad" },
    { en: "Ice fishing", es: "Pesca en el hielo (muy típica en Michigan)" },
    { en: "Frostbite", es: "Congelación (en la piel)" },
    { en: "Snow shovel", es: "Pala de nieve" },
    { en: "Snowplow", es: "Quitanieves" },
    { en: "Black ice", es: "Placas de hielo invisibles" },
    { en: "Below zero", es: "Bajo cero (allí suele ser en °F)" },
    { en: "Layers", es: "Capas de ropa" },
    { en: "Beanie", es: "Gorro de lana" },
    { en: "Snowball fight", es: "Guerra de bolas de nieve" },
    { en: "Ice skating", es: "Patinaje sobre hielo" },
    { en: "Christmas lights", es: "Luces de Navidad" },
    { en: "New Year's resolution", es: "Propósito de Año Nuevo" },
    { en: "Cabin fever", es: "Agobio de estar mucho tiempo encerrado" },
    { en: "Freezing rain", es: "Lluvia helada" },
    { en: "Whiteout", es: "Visibilidad nula por la nieve" },
    { en: "Snowdrift", es: "Montón de nieve acumulada por el viento" },
    { en: "Lake-effect snow", es: "Nevada por efecto lago" },
    { en: "Flurries", es: "Copos sueltos" },
    { en: "Hail", es: "Granizo" },
    { en: "Long johns", es: "Ropa interior térmica" },
    { en: "Parka", es: "Abrigo de plumas" },
    { en: "Earmuffs", es: "Orejeras" },
    { en: "Gloves", es: "Guantes" },
    { en: "Ice scraper", es: "Rasqueta para el hielo del coche" },
    { en: "Defrost", es: "Descongelar / Desempañar" },
    { en: "Road salt", es: "Sal para las carreteras" },
    { en: "Snow pants", es: "Pantalones de nieve" },
    { en: "Snowmobile", es: "Moto de nieve" },
    { en: "Cross-country skiing", es: "Esquí de fondo" },
    { en: "Ice rink", es: "Pista de hielo" },
    { en: "Hockey", es: "Hockey sobre hielo" },
    { en: "Fireplace", es: "Chimenea" },
    { en: "Blanket", es: "Manta" },
    { en: "Stocking", es: "Calcetín de Navidad para regalos" },
    { en: "Wrapping paper", es: "Papel de regalo" },
    { en: "Gingerbread", es: "Pan de jengibre" },
    { en: "Eggnog", es: "Ponche de huevo" },
    { en: "Ugly sweater", es: "Jersey feo de Navidad" },
    { en: "Secret Santa", es: "Amigo invisible" },
    { en: "Mistletoe", es: "Muérdago" },
    { en: "Wreath", es: "Corona navideña" },
    { en: "New Year's Eve", es: "Nochevieja" },
    { en: "Ball drop", es: "Bajada de la bola en Times Square" },
    { en: "Numb", es: "Entumecido" },
    { en: "Polar vortex", es: "Vórtice polar (frío extremo)" },
    { en: "Space heater", es: "Estufa eléctrica" },
    { en: "Groundhog Day", es: "Día de la Marmota (2 de febrero)" },
    { en: "Valentine's Day", es: "San Valentín" },
    { en: "Shiver", es: "Tiritar" }
  ],
  primavera: [
    { en: "Spring break", es: "Vacaciones de primavera" },
    { en: "Thaw", es: "Deshielo" },
    { en: "Mud", es: "Barro" },
    { en: "Bloom", es: "Florecer" },
    { en: "Rain boots", es: "Botas de agua" },
    { en: "Allergies / Pollen", es: "Alergias / Polen" },
    { en: "Easter egg hunt", es: "Búsqueda de huevos de Pascua" },
    { en: "Prom", es: "Baile de fin de curso" },
    { en: "Track and field", es: "Atletismo" },
    { en: "Finals", es: "Exámenes finales" },
    { en: "Sunscreen", es: "Crema solar" },
    { en: "Daylight saving time", es: "Horario de verano" },
    { en: "Showers", es: "Chubascos" },
    { en: "Puddle", es: "Charco" },
    { en: "Sprout", es: "Brote" },
    { en: "Robin", es: "Petirrojo americano (anuncia la primavera)" },
    { en: "Tulip", es: "Tulipán" },
    { en: "Spring cleaning", es: "Limpieza a fondo de primavera" },
    { en: "Mild", es: "Templado / Suave" },
    { en: "Breeze", es: "Brisa" },
    { en: "Corsage", es: "Ramillete de muñeca para el Prom" },
    { en: "Senior year", es: "Último curso de high school" },
    { en: "Yearbook signing", es: "Firmar los anuarios" },
    { en: "Mother's Day", es: "Día de la Madre (2.º domingo de mayo en EE. UU.)" },
    { en: "Spring forward", es: "Adelantar el reloj (cambio de hora de primavera)" },
    { en: "Melt", es: "Derretirse" },
    { en: "Slush", es: "Nieve medio derretida" },
    { en: "Pothole", es: "Bache" },
    { en: "Thunderstorm", es: "Tormenta eléctrica" },
    { en: "Tornado warning", es: "Aviso de tornado" },
    { en: "Rainbow", es: "Arcoíris" },
    { en: "Umbrella", es: "Paraguas" },
    { en: "Windbreaker", es: "Cortavientos" },
    { en: "Daffodil", es: "Narciso" },
    { en: "Cherry blossom", es: "Flor del cerezo" },
    { en: "Lilac", es: "Lila" },
    { en: "Bud", es: "Capullo / Brote" },
    { en: "Lawn", es: "Césped" },
    { en: "Mow the lawn", es: "Cortar el césped" },
    { en: "Garden", es: "Jardín / Huerto" },
    { en: "Seeds", es: "Semillas" },
    { en: "Bunny", es: "Conejito" },
    { en: "Easter basket", es: "Cesta de Pascua" },
    { en: "St. Patrick's Day", es: "San Patricio (17 de marzo, todo el mundo de verde)" },
    { en: "Shamrock", es: "Trébol" },
    { en: "April Fools' Day", es: "1 de abril, día de las bromas (como los Inocentes)" },
    { en: "Baseball season", es: "Temporada de béisbol" },
    { en: "Softball", es: "Sóftbol" },
    { en: "Prom dress / Tux", es: "Vestido de Prom / Esmoquin" },
    { en: "Promposal", es: "Invitación espectacular para ir al Prom" },
    { en: "Boutonniere", es: "Flor para la solapa" },
    { en: "Limo", es: "Limusina" },
    { en: "AP exams", es: "Exámenes AP de nivel universitario (mayo)" },
    { en: "Memorial Day", es: "Memorial Day (último lunes de mayo)" },
    { en: "Graduation party", es: "Fiesta de graduación" },
    { en: "Sneeze", es: "Estornudar" },
    { en: "Itchy eyes", es: "Picor de ojos" },
    { en: "Birdsong", es: "Canto de los pájaros" },
    { en: "Longer days", es: "Días más largos" },
    { en: "Picnic", es: "Picnic" }
  ],
  verano: [
    { en: "Summer break", es: "Vacaciones de verano" },
    { en: "Lake / Beach", es: "Lago / Playa" },
    { en: "Sunburn", es: "Quemadura solar" },
    { en: "Mosquito bite", es: "Picadura de mosquito" },
    { en: "Campfire / S'mores", es: "Hoguera / Galleta con nube y chocolate" },
    { en: "Fireworks", es: "Fuegos artificiales" },
    { en: "Fourth of July", es: "4 de julio, Día de la Independencia" },
    { en: "Graduation", es: "Graduación" },
    { en: "Yearbook", es: "Anuario del instituto" },
    { en: "Goodbye party", es: "Fiesta de despedida" },
    { en: "Keep in touch", es: "Seguimos en contacto" },
    { en: "Back home", es: "De vuelta en casa" },
    { en: "Heat wave", es: "Ola de calor" },
    { en: "Humid", es: "Húmedo / Bochornoso" },
    { en: "Flip-flops", es: "Chanclas" },
    { en: "Popsicle", es: "Polo (helado)" },
    { en: "Lemonade stand", es: "Puesto de limonada" },
    { en: "Barbecue / Cookout", es: "Barbacoa" },
    { en: "Canoe / Kayak", es: "Canoa / Kayak" },
    { en: "Fireflies", es: "Luciérnagas" },
    { en: "Road trip", es: "Viaje en coche" },
    { en: "Farewell", es: "Despedida" },
    { en: "Pack / Suitcase", es: "Hacer la maleta / Maleta" },
    { en: "Jet lag", es: "Desfase horario" },
    { en: "Sunglasses", es: "Gafas de sol" },
    { en: "Swimsuit", es: "Bañador" },
    { en: "Towel", es: "Toalla" },
    { en: "Tan", es: "Moreno / Bronceado" },
    { en: "Shade", es: "Sombra" },
    { en: "Sweaty", es: "Sudado/a" },
    { en: "AC (air conditioning)", es: "Aire acondicionado" },
    { en: "Fan", es: "Ventilador" },
    { en: "Ice cream cone", es: "Cucurucho de helado" },
    { en: "Watermelon", es: "Sandía" },
    { en: "Corn on the cob", es: "Mazorca de maíz" },
    { en: "Hot dog", es: "Perrito caliente" },
    { en: "Lifeguard", es: "Socorrista" },
    { en: "Pool", es: "Piscina" },
    { en: "Dock", es: "Embarcadero" },
    { en: "Pontoon boat", es: "Barca de pontones (típica de los lagos)" },
    { en: "Tubing", es: "Bajar un río en flotador" },
    { en: "Fishing pole", es: "Caña de pescar" },
    { en: "Tent", es: "Tienda de campaña" },
    { en: "Bug spray", es: "Repelente de mosquitos" },
    { en: "Hammock", es: "Hamaca" },
    { en: "Sunset", es: "Puesta de sol" },
    { en: "Thunder and lightning", es: "Truenos y relámpagos" },
    { en: "County fair", es: "Feria del condado" },
    { en: "Farmers market", es: "Mercado de agricultores" },
    { en: "Strawberry picking", es: "Recoger fresas" },
    { en: "Summer camp", es: "Campamento de verano" },
    { en: "Part-time job", es: "Trabajo a tiempo parcial" },
    { en: "Diploma", es: "Diploma / Título" },
    { en: "Airport", es: "Aeropuerto" },
    { en: "Boarding pass", es: "Tarjeta de embarque" },
    { en: "Carry-on", es: "Equipaje de mano" },
    { en: "Layover", es: "Escala" },
    { en: "Customs", es: "Aduana" },
    { en: "Souvenir", es: "Recuerdo (objeto)" },
    { en: "Memories", es: "Recuerdos (vividos)" }
  ]
};

/* =============================================================
   VOCABULARIO DE HIGH SCHOOL
   ============================================================= */
window.VOCAB_HS = [
  { en: "Freshman / Sophomore", es: "1.º / 2.º de high school (9th / 10th grade)" },
  { en: "Junior / Senior", es: "3.º / 4.º de high school (11th / 12th grade)" },
  { en: "Homeroom", es: "Tutoría / Clase de referencia" },
  { en: "Period", es: "Hora de clase (1st period = primera hora)" },
  { en: "Schedule", es: "Horario" },
  { en: "Counselor", es: "Orientador/a" },
  { en: "Principal", es: "Director/a del centro" },
  { en: "Hall pass", es: "Permiso para salir de clase" },
  { en: "Locker", es: "Taquilla" },
  { en: "Tardy", es: "Retraso (llegar tarde a clase)" },
  { en: "Detention", es: "Castigo después de clase" },
  { en: "Assignment / Homework", es: "Tarea / Deberes" },
  { en: "Due date", es: "Fecha de entrega" },
  { en: "Quiz / Test", es: "Control corto / Examen" },
  { en: "Midterm / Final", es: "Examen parcial / Examen final" },
  { en: "Grade", es: "Nota (y también curso: 10th grade)" },
  { en: "GPA", es: "Nota media" },
  { en: "Report card", es: "Boletín de notas" },
  { en: "Extra credit", es: "Puntos extra" },
  { en: "Elective", es: "Asignatura optativa" },
  { en: "Credit", es: "Crédito (asignatura aprobada)" },
  { en: "Cafeteria / Lunch line", es: "Comedor / Cola del comedor" },
  { en: "Study hall", es: "Hora de estudio" },
  { en: "Substitute (sub)", es: "Profesor/a sustituto/a" },
  { en: "Bus pass / Bus stop", es: "Pase de autobús / Parada" },
  { en: "Pep rally", es: "Acto de animación antes de un partido" },
  { en: "Homecoming", es: "Semana y baile de bienvenida en otoño" },
  { en: "Spirit week", es: "Semana temática (disfraces cada día)" },
  { en: "Varsity / JV", es: "Equipo principal / Equipo júnior" },
  { en: "Tryouts", es: "Pruebas para entrar en un equipo" },
  { en: "Club", es: "Club o actividad extraescolar" },
  { en: "Field trip", es: "Excursión escolar" },
  { en: "Snow day", es: "Día sin clase por nieve" },
  { en: "Pledge of Allegiance", es: "Juramento a la bandera por la mañana" },
  { en: "Prom", es: "Baile de fin de curso" },
  { en: "Graduation / Cap and gown", es: "Graduación / Birrete y toga" },
  { en: "Syllabus", es: "Programa de la asignatura" },
  { en: "Rubric", es: "Rúbrica (criterios de evaluación)" },
  { en: "Essay", es: "Redacción / Ensayo" },
  { en: "Lab / Lab partner", es: "Laboratorio / Compañero de laboratorio" },
  { en: "Gym class / PE", es: "Educación física" },
  { en: "Bleachers", es: "Gradas" },
  { en: "Media center", es: "Biblioteca del instituto" },
  { en: "Attendance", es: "Asistencia" },
  { en: "Excused absence", es: "Falta justificada" },
  { en: "Permission slip", es: "Autorización firmada por la familia" },
  { en: "Parent-teacher conference", es: "Reunión de familias con profesores" },
  { en: "Honor roll", es: "Cuadro de honor" },
  { en: "AP / Honors class", es: "Asignatura de nivel avanzado" },
  { en: "Plagiarism", es: "Plagio / Copiar" },
  { en: "Pop quiz", es: "Control sorpresa" },
  { en: "Cram", es: "Estudiar a última hora" },
  { en: "Pass / Fail", es: "Aprobar / Suspender" },
  { en: "Teacher's pet", es: "Enchufado/a del profe" },
  { en: "Cheerleader", es: "Animador/a" },
  { en: "Marching band", es: "Banda de música del instituto" },
  { en: "Mascot", es: "Mascota del equipo" },
  { en: "Bell", es: "Timbre" },
  { en: "Early release", es: "Salida temprana" },
  { en: "Student ID", es: "Carné de estudiante" }
];
