/* =============================================================
   TEKSTY STRONY (polski)
   Zastępują domyślne hiszpańskie teksty z index.html.
   {0}, {1}, {2}: wartości wstawiane przez stronę (liczby, nazwy, daty).
   ============================================================= */

window.TEXTOS = {
  locale: "pl-PL",
  errConfig: "Nie udało się odczytać pliku config.js. Sprawdź przecinki i cudzysłowy w tym pliku.",
  horaLocal: "Czas lokalny", cambiarVersion: "Zmień kraj", bandera: "Flaga: {0}",
  calendario: "Kalendarz", mesAnt: "Poprzedni miesiąc", mesSig: "Następny miesiąc", hoy: "Dziś", manana: "Jutro",
  festivoDe: "Święto: {0}", legPrev: "Święto przewidywane", familia: "Rodzina", diaSenalado: "Ważny dzień", evento: "Wydarzenie", escolar: "Szkoła",
  proximas: "Najbliższe daty", expresiones: "Przydatne wyrażenia", repaso: "Powtórka", reiniciar: "Wyzeruj nauczone",
  actualizar: "Odśwież teraz", actualizado: "Zaktualizowano o {0} ({1})", tocaCerrar: "Dotknij, aby zamknąć",
  conversor: "Przelicznik", queConvertir: "Co przeliczyć", solAire: "Słońce i powietrze",
  deDiferencia: "różnicy", mismaHora: "ta sama godzina", sinConexion: "Brak połączenia", sinDatos: "Brak danych",
  horaEn: "{0} ({1})", horaEnPais: "{0} ({1})",
  haceMin: "{0} min temu", haceH: "{0} godz. temu", haceDias: "{0} dni temu",
  wmo: {
    "0": "Bezchmurnie", "1": "Prawie bezchmurnie", "2": "Częściowe zachmurzenie", "3": "Pochmurno", "45": "Mgła", "48": "Mgła ze szronem",
    "51": "Słaba mżawka", "53": "Mżawka", "55": "Silna mżawka", "56": "Marznąca mżawka", "57": "Silna marznąca mżawka",
    "61": "Słaby deszcz", "63": "Deszcz", "65": "Ulewny deszcz", "66": "Marznący deszcz", "67": "Silny marznący deszcz",
    "71": "Słaby śnieg", "73": "Śnieg", "75": "Intensywny śnieg", "77": "Krupa śnieżna",
    "80": "Przelotne opady", "81": "Przelotny deszcz", "82": "Silne przelotne opady", "85": "Przelotny śnieg", "86": "Silny przelotny śnieg",
    "95": "Burza", "96": "Burza z gradem", "99": "Silna burza z gradem"
  },
  max: "Maks", min: "Min", ahora: "Teraz", sensacion: "odczuwalna", lluvia: "deszcz", lluviaDia: "Deszcz",
  amanece: "wschód", anochece: "zachód", deLuz: "{0} godz. {1} min światła", sensMin: "Odcz. min", sinNieve: "Bez śniegu", nieve: "Śnieg",
  tiempoEn: "Pogoda: {0}", cargandoTiempo: "Ładowanie pogody…", horaAHora: "Dziś godzina po godzinie", proximosDias: "Najbliższe dni",
  prevGuardada: "Brak połączenia: zapisana prognoza {0}",
  errTiempo: "Nie udało się pobrać pogody i nie ma zapisanej prognozy. Dotknij Odśwież teraz.",
  meses: ["styczeń", "luty", "marzec", "kwiecień", "maj", "czerwiec", "lipiec", "sierpień", "wrzesień", "październik", "listopad", "grudzień"],
  iniciales: ["P", "W", "Ś", "C", "P", "S", "N"], diaDe: "{0}, {1}", esHoyAria: ", dziś",
  tagFest: "Św", tagFam: "Rodz", tagEvt: "Wyd", tagEsc: "Szk", tagDia: "Dzień",
  rango: "od {0} do {1}", fechaConfirmar: "data do potwierdzenia", datoOnline: "dane online", porConfirmar: "do potwierdzenia",
  horaConfirmar: "godzina do potwierdzenia",
  fuenteOnline: " · źródło online (Nager.Date)", pendConfirmar: ", do potwierdzenia", pendConfirmarCon: ", do potwierdzenia: {0}",
  previsto: " · przewidywane, brak oficjalnego kalendarza", pendAprob: " · czeka na zatwierdzenie",
  calEscolar: "Kalendarz szkolny", nadaMarcado: "Nic nie zaznaczono na ten dzień.", santoral: "Imieniny:",
  warnFestivos: "Brakuje oficjalnych świąt ({0}) na rok {1} w config.js.",
  warnFestivosSig: "Kalendarz świąt na rok {0} powinien być już znany ({1}): dodaj go do config.js.",
  warnEscolar: "Brakuje kalendarza szkolnego{0} na następny rok w config.js.", deX: " ({0})",
  warnEventos: "W config.js nie ma już przyszłych wydarzeń.",
  warnPartidos: "Nie ma już meczów drużyny {0}: dodaj terminarz nowego sezonu do config.js.",
  stPartidos: "Mecze online {0}", stPartidosCopia: "Brak połączenia ze źródłem meczów: używana kopia sprzed {0}",
  stPartidosConfig: "Brak połączenia ze źródłem meczów: używane dane z config.js",
  stFestivos: "Święta ({0}) {1} online", stSinFestivos: "Brak połączenia ze źródłem świąt ({0}) {1}",
  cambioAdelanta: "Zmiana czasu ({0}): zegarki o godzinę do przodu", cambioRetrasa: "Zmiana czasu ({0}): zegarki o godzinę do tyłu",
  desdeHoyDif: "od dziś {0} godz. różnicy", desdeHoyMisma: "od dziś ta sama godzina",
  noFechas: "Brak najbliższych dat.", porConfirmarParen: " (do potwierdzenia)", esHoy: "To dziś!", enCurso: "Trwa",
  mes: "miesiąc", mesesN: "miesiące", mesesVarios: "miesięcy", dia: "dzień", dias: "dni",
  recuerda: "Pamiętaj. ", enNDias: "Za {0} dni",
  felicita: "Złóż życzenia: {0}!", cumpleDe: "Urodziny: {0}",
  aprendidasDe: "Nauczone: {0} z {1}.", marcaCirculo: "Zaznacz kółkiem te, które już znasz: przestaną się pojawiać.",
  marcarAprendida: "Oznacz jako nauczone", aprendidasManana: "Nauczone: {0}. Od jutra przestaną się pojawiać.",
  confirmReiniciar: "Przywrócić wszystkie wyrażenia oznaczone jako nauczone?", tocaVer: "dotknij, aby zobaczyć",
  dolares: "Dolary", millas: "Mile", kilometros: "Kilometry", fahrenheit: "Fahrenheit", celsius: "Celsjusz",
  libras: "Funty", kilos: "Kilogramy", onzas: "Uncje", gramos: "Gramy", pulgadas: "Cale", centimetros: "Centymetry",
  mph: "Mile na godzinę", kmh: "Km na godzinę",
  bMillas: "Mile / km", bLibras: "Funty / kg", bOnzas: "Uncje / gramy", bPulgadas: "Cale / cm",
  notaOnza: "Uncja wagowa. Uncja płynów (fl oz) to 29,57 ml.",
  cargandoCambio: "Ładowanie kursu walut…", bce: "kurs referencyjny EBC", tasaGuardada: "brak połączenia: zapisany kurs {0}",
  tasaManual: "brak połączenia: kurs ręczny z config.js, sprawdź go", sinCambio: "Brak kursu: nie ma połączenia.",
  uvTxt: ["niski", "umiarkowany", "wysoki", "bardzo wysoki", "ekstremalny"],
  aqTxt: ["Dobra", "Umiarkowana", "Niezdrowa dla wrażliwych", "Niezdrowa", "Bardzo niezdrowa", "Niebezpieczna"],
  cargandoAire: "Ładowanie jakości powietrza…", cargandoUV: "Ładowanie indeksu UV…", errUV: "Nie udało się pobrać indeksu UV.",
  aire: "Powietrze {0} · {1}", aireSinDatos: "Powietrze: brak danych", uvMax: "Maks. UV {0} ({1}) około {2}:00. ",
  protSi: "Krem z filtrem w godzinach żółtych i wyżej.", protNo: "Nie potrzeba specjalnej ochrony przed słońcem.",
  datosGuardados: "Brak połączenia: zapisane dane {0}. ", uvAria: "Indeks UV godzina po godzinie: {0}"
};
