/* =============================================================
   WYRAŻENIA I ZDANIA (wersja polska)
   FRASES: frase del día · EXPRESIONES: 2000 en 23 bloques.
   Formato: { en: "...", pl: "..." },
   ============================================================= */

window.FRASES = [
  { en: "We're so proud of you.", pl: "Jesteśmy z Ciebie bardzo dumni." },
  { en: "You've got this.", pl: "Dasz radę." },
  { en: "Thinking of you today.", pl: "Dziś myślimy o Tobie." },
  { en: "Distance means so little when someone means so much.", pl: "Odległość niewiele znaczy, gdy ktoś znaczy tak wiele." },
  { en: "Every day is one day closer.", pl: "Każdy dzień to jeden dzień mniej." },
  { en: "Be brave, be kind, be you.", pl: "Miej odwagę, bądź dobrym człowiekiem, bądź sobą." },
  { en: "Home is wherever you are loved.", pl: "Dom jest tam, gdzie Cię kochają." },
  { en: "Enjoy every moment of this adventure.", pl: "Ciesz się każdą chwilą tej przygody." },
  { en: "You make us smile from far away.", pl: "Nawet z daleka sprawiasz, że się uśmiechamy." },
  { en: "Small steps every day.", pl: "Małe kroki każdego dnia." },
  { en: "We miss you, and we're cheering for you.", pl: "Tęsknimy i trzymamy za Ciebie kciuki." },
  { en: "Trust yourself. You know more than you think.", pl: "Zaufaj sobie. Wiesz więcej, niż myślisz." },
  { en: "It's okay to have a hard day.", pl: "Gorszy dzień to nic złego." },
  { en: "Keep being curious.", pl: "Nigdy nie trać ciekawości świata." },
  { en: "Today is a good day to learn something new.", pl: "Dziś jest dobry dzień, żeby nauczyć się czegoś nowego." },
  { en: "You are stronger than you know.", pl: "Masz w sobie więcej siły, niż myślisz." },
  { en: "Sending you a big hug across the ocean.", pl: "Ściskamy Cię mocno z drugiej strony oceanu." },
  { en: "Be proud of how far you've come.", pl: "Pomyśl, jaką drogę masz już za sobą." },
  { en: "Make today count.", pl: "Niech dzisiejszy dzień się liczy." },
  { en: "Smile, it suits you.", pl: "Uśmiechaj się, pięknie Ci z tym." },
  { en: "One day at a time.", pl: "Dzień po dniu." },
  { en: "You belong wherever you choose to shine.", pl: "Twoje miejsce jest tam, gdzie zechcesz błyszczeć." },
  { en: "Say yes to new things.", pl: "Mów „tak” nowym rzeczom." },
  { en: "Mistakes mean you're trying.", pl: "Błędy oznaczają, że próbujesz." },
  { en: "We love you to the moon and back.", pl: "Kochamy Cię do księżyca i z powrotem." },
  { en: "Take care of yourself today.", pl: "Zadbaj dziś o siebie." },
  { en: "Your courage inspires us.", pl: "Twoja odwaga nas inspiruje." },
  { en: "Good things are coming.", pl: "Nadchodzą dobre rzeczy." },
  { en: "Call us whenever you want. Always.", pl: "Dzwoń, kiedy tylko chcesz. Zawsze." },
  { en: "The best stories start far from home.", pl: "Najlepsze historie zaczynają się daleko od domu." }
];

window.EXPRESIONES = {
  primavera: [
    { en: "Spring", pl: "Wiosna" },
    { en: "Blossom", pl: "Kwiat drzewa owocowego" },
    { en: "Almond blossom", pl: "Kwiat migdałowca" },
    { en: "Cherry blossom", pl: "Kwiat wiśni" },
    { en: "To bloom", pl: "Kwitnąć" },
    { en: "In full bloom", pl: "W pełnym rozkwicie" },
    { en: "Bud", pl: "Pąk" },
    { en: "To sprout", pl: "Kiełkować" },
    { en: "Green shoots", pl: "Pierwsze pędy" },
    { en: "Daisy", pl: "Stokrotka" },
    { en: "Poppy", pl: "Mak" },
    { en: "Tulip", pl: "Tulipan" },
    { en: "Daffodil", pl: "Żonkil" },
    { en: "Lilac", pl: "Bez" },
    { en: "Rose bush", pl: "Krzak róży" },
    { en: "Bouquet", pl: "Bukiet kwiatów" },
    { en: "Wildflowers", pl: "Polne kwiaty" },
    { en: "Meadow", pl: "Łąka" },
    { en: "Fresh grass", pl: "Świeża trawa" },
    { en: "Bee", pl: "Pszczoła" },
    { en: "Butterfly", pl: "Motyl" },
    { en: "Ladybird / Ladybug", pl: "Biedronka" },
    { en: "Caterpillar", pl: "Gąsienica" },
    { en: "Ant", pl: "Mrówka" },
    { en: "Snail", pl: "Ślimak" },
    { en: "Frog", pl: "Żaba" },
    { en: "Tadpole", pl: "Kijanka" },
    { en: "Lizard", pl: "Jaszczurka" },
    { en: "Swallow", pl: "Jaskółka" },
    { en: "Stork", pl: "Bocian" },
    { en: "Nest", pl: "Gniazdo" },
    { en: "Birdsong", pl: "Śpiew ptaków" },
    { en: "Lamb", pl: "Jagnię" },
    { en: "Dew", pl: "Rosa" },
    { en: "Mud", pl: "Błoto" },
    { en: "To mow the lawn", pl: "Kosić trawnik" },
    { en: "To plant", pl: "Sadzić" },
    { en: "Seeds", pl: "Nasiona" },
    { en: "Flowerpot", pl: "Doniczka" },
    { en: "Window box", pl: "Skrzynka balkonowa" },
    { en: "Watering can", pl: "Konewka" },
    { en: "Hose", pl: "Wąż ogrodowy" },
    { en: "Greenhouse", pl: "Szklarnia" },
    { en: "Vegetable garden", pl: "Ogródek warzywny" },
    { en: "To water the plants", pl: "Podlewać rośliny" },
    { en: "Pollen", pl: "Pyłek" },
    { en: "Hay fever", pl: "Katar sienny" },
    { en: "To sneeze", pl: "Kichać" },
    { en: "Itchy eyes", pl: "Swędzące oczy" },
    { en: "Antihistamine", pl: "Lek przeciwhistaminowy" },
    { en: "Spring fatigue", pl: "Przesilenie wiosenne" },
    { en: "April showers", pl: "Kwietniowe deszcze" },
    { en: "Rainbow", pl: "Tęcza" },
    { en: "Thunderstorm", pl: "Burza" },
    { en: "Mild weather", pl: "Łagodna pogoda" },
    { en: "Breeze", pl: "Wietrzyk" },
    { en: "Sunny spells", pl: "Przejaśnienia" },
    { en: "Changeable weather", pl: "Zmienna pogoda" },
    { en: "Thaw", pl: "Odwilż" },
    { en: "Melting snow", pl: "Topniejący śnieg" },
    { en: "Longer days", pl: "Dłuższe dni" },
    { en: "Sunrise", pl: "Wschód słońca" },
    { en: "The clocks go forward", pl: "Przestawiamy zegarki do przodu" },
    { en: "Spring equinox", pl: "Równonoc wiosenna" },
    { en: "Light jacket", pl: "Lekka kurtka" },
    { en: "Denim jacket", pl: "Kurtka dżinsowa" },
    { en: "Trainers / Sneakers", pl: "Trampki, adidasy" },
    { en: "Short sleeves", pl: "Krótki rękaw" },
    { en: "Pastel colours", pl: "Pastelowe kolory" },
    { en: "Lighter clothes", pl: "Lżejsze ubrania" },
    { en: "To put away winter clothes", pl: "Schować zimowe ubrania" },
    { en: "Spring cleaning", pl: "Wiosenne porządki" },
    { en: "To declutter", pl: "Zrobić porządek i pozbyć się rupieci" },
    { en: "Lent", pl: "Wielki Post" },
    { en: "Palm Sunday", pl: "Niedziela Palmowa" },
    { en: "Holy Week", pl: "Wielki Tydzień" },
    { en: "Easter", pl: "Wielkanoc" },
    { en: "Easter Sunday", pl: "Niedziela Wielkanocna" },
    { en: "Procession", pl: "Procesja" },
    { en: "Easter egg", pl: "Pisanka" },
    { en: "Easter bunny", pl: "Zajączek wielkanocny" },
    { en: "French toast", pl: "Tosty francuskie" },
    { en: "Easter holidays", pl: "Ferie wielkanocne" },
    { en: "Father's Day", pl: "Dzień Ojca" },
    { en: "Mother's Day", pl: "Dzień Matki" },
    { en: "World Book Day", pl: "Światowy Dzień Książki" },
    { en: "Labour Day", pl: "Święto Pracy" },
    { en: "April Fools' Day", pl: "Prima aprilis" },
    { en: "Prank", pl: "Psikus, żart" },
    { en: "Fair", pl: "Jarmark, festyn" },
    { en: "First communion", pl: "Pierwsza komunia" },
    { en: "Wedding season", pl: "Sezon ślubny" },
    { en: "Picnic", pl: "Piknik" },
    { en: "Day trip", pl: "Jednodniowa wycieczka" },
    { en: "Bike ride", pl: "Przejażdżka rowerowa" },
    { en: "Hiking", pl: "Wędrówki piesze" },
    { en: "Terrace", pl: "Taras, ogródek kawiarniany" },
    { en: "To have a drink outside", pl: "Napić się czegoś na świeżym powietrzu" },
    { en: "Final exams", pl: "Egzaminy końcowe" },
    { en: "To revise", pl: "Powtarzać materiał" },
    { en: "Study plan", pl: "Plan nauki" },
    { en: "Final project", pl: "Projekt końcowy" },
    { en: "University entrance exam", pl: "Egzamin wstępny na studia" },
    { en: "Application form", pl: "Formularz zgłoszeniowy" },
    { en: "Graduation ceremony", pl: "Uroczystość wręczenia dyplomów" },
    { en: "Prom", pl: "Bal na zakończenie szkoły" },
    { en: "Yearbook", pl: "Księga pamiątkowa rocznika" },
    { en: "Fresh strawberries", pl: "Świeże truskawki" },
    { en: "Asparagus", pl: "Szparagi" },
    { en: "Artichoke", pl: "Karczoch" },
    { en: "Broad beans", pl: "Bób" },
    { en: "Peas", pl: "Groszek" },
    { en: "Cherries", pl: "Czereśnie" },
    { en: "Loquat", pl: "Nieśplik" },
    { en: "Butterflies in my stomach", pl: "Motyle w brzuchu" },
    { en: "A spring in your step", pl: "Chodzić pełnym energii" },
    { en: "To turn over a new leaf", pl: "Zacząć nowy rozdział" },
    { en: "Every cloud has a silver lining", pl: "Nie ma tego złego, co by na dobre nie wyszło" },
    { en: "Fresh as a daisy", pl: "Świeży jak skowronek" },
    { en: "Rain or shine", pl: "W deszcz czy w słońce" },
    { en: "Bright colours", pl: "Żywe kolory" },
    { en: "To feel refreshed", pl: "Poczuć się odświeżonym" },
    { en: "Sunny day", pl: "Słoneczny dzień" },
    { en: "To stretch your legs", pl: "Rozprostować nogi" },
    { en: "To soak up the sun", pl: "Wygrzewać się na słońcu" }
  ],
  verano: [
    { en: "Summer", pl: "Lato" },
    { en: "Summer holidays", pl: "Wakacje letnie" },
    { en: "Heatwave", pl: "Fala upałów" },
    { en: "Scorching hot", pl: "Skwar" },
    { en: "Muggy", pl: "Parno" },
    { en: "It's boiling", pl: "Ale upał!" },
    { en: "The dog days of summer", pl: "Kanikuła" },
    { en: "To sweat", pl: "Pocić się" },
    { en: "Sunstroke", pl: "Udar słoneczny" },
    { en: "Heatstroke", pl: "Udar cieplny" },
    { en: "Sunburn", pl: "Oparzenie słoneczne" },
    { en: "Sunscreen", pl: "Krem z filtrem" },
    { en: "After-sun lotion", pl: "Balsam po opalaniu" },
    { en: "Stay hydrated", pl: "Pij dużo wody" },
    { en: "Water bottle", pl: "Butelka na wodę" },
    { en: "To cool off", pl: "Ochłodzić się" },
    { en: "In the shade", pl: "W cieniu" },
    { en: "Fan", pl: "Wentylator" },
    { en: "Air conditioning", pl: "Klimatyzacja" },
    { en: "Sunglasses", pl: "Okulary przeciwsłoneczne" },
    { en: "Sun hat", pl: "Kapelusz przeciwsłoneczny" },
    { en: "Flip-flops", pl: "Japonki" },
    { en: "Sandals", pl: "Sandały" },
    { en: "Swimsuit", pl: "Strój kąpielowy" },
    { en: "Bikini", pl: "Bikini" },
    { en: "Beach towel", pl: "Ręcznik plażowy" },
    { en: "Beach umbrella", pl: "Parasol plażowy" },
    { en: "Sunbed", pl: "Leżak" },
    { en: "Beach bag", pl: "Torba plażowa" },
    { en: "Cool box", pl: "Lodówka turystyczna" },
    { en: "Sand", pl: "Piasek" },
    { en: "Sandcastle", pl: "Zamek z piasku" },
    { en: "Bucket and spade", pl: "Wiaderko i łopatka" },
    { en: "Seashell", pl: "Muszelka" },
    { en: "Wave", pl: "Fala" },
    { en: "Tide", pl: "Pływ" },
    { en: "High tide / Low tide", pl: "Przypływ / odpływ" },
    { en: "Shore", pl: "Brzeg" },
    { en: "Cove", pl: "Zatoczka" },
    { en: "Cliff", pl: "Klif" },
    { en: "Lighthouse", pl: "Latarnia morska" },
    { en: "Pier", pl: "Molo" },
    { en: "Crystal-clear water", pl: "Krystalicznie czysta woda" },
    { en: "Sea breeze", pl: "Morska bryza" },
    { en: "Jellyfish", pl: "Meduza" },
    { en: "Lifeguard", pl: "Ratownik" },
    { en: "Red flag", pl: "Czerwona flaga" },
    { en: "To go for a swim", pl: "Popływać" },
    { en: "To sunbathe", pl: "Opalać się" },
    { en: "To get a tan", pl: "Opalić się" },
    { en: "Tan lines", pl: "Ślady po stroju" },
    { en: "Freckles", pl: "Piegi" },
    { en: "Swimming pool", pl: "Basen" },
    { en: "To dive in", pl: "Skoczyć do wody" },
    { en: "Snorkel", pl: "Fajka do nurkowania" },
    { en: "Swimming goggles", pl: "Okulary pływackie" },
    { en: "Water park", pl: "Park wodny" },
    { en: "Pool party", pl: "Impreza przy basenie" },
    { en: "Ice cream", pl: "Lody" },
    { en: "Ice lolly / Popsicle", pl: "Lód na patyku" },
    { en: "Slushie", pl: "Granita, lodowy napój" },
    { en: "Tiger nut milk", pl: "Mleko z cibory (horchata)" },
    { en: "Cold tomato soup", pl: "Zimna zupa pomidorowa (gazpacho)" },
    { en: "Watermelon", pl: "Arbuz" },
    { en: "Melon", pl: "Melon" },
    { en: "Peach", pl: "Brzoskwinia" },
    { en: "Apricot", pl: "Morela" },
    { en: "Plum", pl: "Śliwka" },
    { en: "Lemonade", pl: "Lemoniada" },
    { en: "Iced coffee", pl: "Mrożona kawa" },
    { en: "Barbecue", pl: "Grill" },
    { en: "Grilled sardines", pl: "Sardynki z grilla" },
    { en: "Seafood", pl: "Owoce morza" },
    { en: "Beach bar", pl: "Bar na plaży" },
    { en: "Late dinner", pl: "Późna kolacja" },
    { en: "Afternoon nap", pl: "Popołudniowa drzemka" },
    { en: "Long summer evenings", pl: "Długie letnie wieczory" },
    { en: "Rooftop bar", pl: "Bar na dachu" },
    { en: "Outdoor cinema", pl: "Kino plenerowe" },
    { en: "Open-air concert", pl: "Koncert plenerowy" },
    { en: "Music festival", pl: "Festiwal muzyczny" },
    { en: "Village fiesta", pl: "Festyn w miasteczku" },
    { en: "Funfair rides", pl: "Karuzele w wesołym miasteczku" },
    { en: "Fireworks", pl: "Fajerwerki" },
    { en: "Midsummer Night", pl: "Noc Kupały, noc świętojańska" },
    { en: "Summer solstice", pl: "Przesilenie letnie" },
    { en: "The longest day", pl: "Najdłuższy dzień" },
    { en: "Shooting star", pl: "Spadająca gwiazda" },
    { en: "Starry sky", pl: "Rozgwieżdżone niebo" },
    { en: "The Perseids", pl: "Perseidy" },
    { en: "Sunset", pl: "Zachód słońca" },
    { en: "Mosquito bite", pl: "Ukąszenie komara" },
    { en: "Insect repellent", pl: "Środek na komary" },
    { en: "Wasp", pl: "Osa" },
    { en: "Cicada", pl: "Cykada" },
    { en: "Firefly", pl: "Świetlik" },
    { en: "Thunder and lightning", pl: "Grzmoty i błyskawice" },
    { en: "Drought", pl: "Susza" },
    { en: "Forest fire", pl: "Pożar lasu" },
    { en: "Road trip", pl: "Podróż samochodem" },
    { en: "Traffic jam", pl: "Korek" },
    { en: "Holiday exodus", pl: "Wakacyjny exodus" },
    { en: "Suitcase", pl: "Walizka" },
    { en: "To pack", pl: "Spakować się" },
    { en: "To unpack", pl: "Rozpakować się" },
    { en: "Passport", pl: "Paszport" },
    { en: "Boarding pass", pl: "Karta pokładowa" },
    { en: "Carry-on bag", pl: "Bagaż podręczny" },
    { en: "Check-in desk", pl: "Stanowisko odprawy" },
    { en: "Delayed flight", pl: "Opóźniony lot" },
    { en: "Jet lag", pl: "Jet lag, zmęczenie po zmianie stref" },
    { en: "Souvenir", pl: "Pamiątka" },
    { en: "Postcard", pl: "Pocztówka" },
    { en: "Campsite", pl: "Kemping" },
    { en: "Tent", pl: "Namiot" },
    { en: "Sleeping bag", pl: "Śpiwór" },
    { en: "Hammock", pl: "Hamak" },
    { en: "Summer camp", pl: "Obóz letni" },
    { en: "Summer job", pl: "Praca wakacyjna" },
    { en: "Resit exams", pl: "Egzaminy poprawkowe" },
    { en: "To chill out", pl: "Wyluzować" },
    { en: "To hang out", pl: "Spędzać razem czas" },
    { en: "Out of office", pl: "Poza biurem" },
    { en: "Summer fling", pl: "Wakacyjna miłość" },
    { en: "Boat trip", pl: "Rejs łodzią" }
  ],
  otono: [
    { en: "Autumn / Fall", pl: "Jesień" },
    { en: "Fallen leaves", pl: "Opadłe liście" },
    { en: "To rake the leaves", pl: "Grabić liście" },
    { en: "Chestnut", pl: "Kasztan jadalny" },
    { en: "Roasted chestnuts", pl: "Pieczone kasztany" },
    { en: "Acorn", pl: "Żołądź" },
    { en: "Mushroom", pl: "Grzyb" },
    { en: "To go mushroom picking", pl: "Iść na grzyby" },
    { en: "Pumpkin", pl: "Dynia" },
    { en: "Harvest", pl: "Żniwa, zbiory" },
    { en: "Grape harvest", pl: "Winobranie" },
    { en: "Vineyard", pl: "Winnica" },
    { en: "Pomegranate", pl: "Granat" },
    { en: "Quince jelly", pl: "Pasta z pigwy" },
    { en: "Persimmon", pl: "Persymona (kaki)" },
    { en: "Walnut", pl: "Orzech włoski" },
    { en: "Hazelnut", pl: "Orzech laskowy" },
    { en: "Sweet potato", pl: "Batat" },
    { en: "Apple picking", pl: "Zbieranie jabłek" },
    { en: "Scarecrow", pl: "Strach na wróble" },
    { en: "Squirrel", pl: "Wiewiórka" },
    { en: "Hedgehog", pl: "Jeż" },
    { en: "Migrating birds", pl: "Ptaki wędrowne" },
    { en: "Bare branches", pl: "Gołe gałęzie" },
    { en: "Foliage", pl: "Listowie" },
    { en: "Golden leaves", pl: "Złote liście" },
    { en: "Crunchy leaves", pl: "Szeleszczące liście" },
    { en: "Chilly", pl: "Chłodno" },
    { en: "Crisp air", pl: "Rześkie powietrze" },
    { en: "Drizzle", pl: "Mżawka" },
    { en: "Downpour", pl: "Ulewa" },
    { en: "It's pouring down", pl: "Leje jak z cebra" },
    { en: "Overcast", pl: "Pochmurno" },
    { en: "Fog", pl: "Mgła" },
    { en: "Mist", pl: "Lekka mgiełka" },
    { en: "Damp", pl: "Wilgotno" },
    { en: "Gust of wind", pl: "Podmuch wiatru" },
    { en: "Windy", pl: "Wietrznie" },
    { en: "Puddle", pl: "Kałuża" },
    { en: "Raincoat", pl: "Płaszcz przeciwdeszczowy" },
    { en: "Umbrella", pl: "Parasol" },
    { en: "Rain boots / Wellies", pl: "Kalosze" },
    { en: "Sweater / Jumper", pl: "Sweter" },
    { en: "Cardigan", pl: "Kardigan" },
    { en: "Scarf", pl: "Szalik" },
    { en: "Trench coat", pl: "Trencz" },
    { en: "Corduroy", pl: "Sztruks" },
    { en: "Ankle boots", pl: "Botki" },
    { en: "Turtleneck", pl: "Golf" },
    { en: "Thick socks", pl: "Grube skarpety" },
    { en: "To layer up", pl: "Ubierać się na cebulkę" },
    { en: "Sweater weather", pl: "Pogoda na sweter" },
    { en: "The days are getting shorter", pl: "Dni są coraz krótsze" },
    { en: "The clocks go back", pl: "Przestawiamy zegarki do tyłu" },
    { en: "It gets dark early", pl: "Wcześnie robi się ciemno" },
    { en: "Dusk", pl: "Zmierzch" },
    { en: "Back to school", pl: "Powrót do szkoły" },
    { en: "School supplies", pl: "Przybory szkolne" },
    { en: "Timetable", pl: "Plan lekcji" },
    { en: "Homework", pl: "Praca domowa" },
    { en: "Locker", pl: "Szafka szkolna" },
    { en: "Term", pl: "Semestr, trymestr" },
    { en: "Midterm exam", pl: "Sprawdzian w połowie semestru" },
    { en: "Deadline", pl: "Termin" },
    { en: "To catch up on", pl: "Nadrobić" },
    { en: "To settle in", pl: "Zaaklimatyzować się" },
    { en: "New routine", pl: "Nowa rutyna" },
    { en: "Back to work", pl: "Powrót do pracy" },
    { en: "Post-holiday blues", pl: "Depresja powakacyjna" },
    { en: "To get back into the swing of things", pl: "Wrócić do formy" },
    { en: "New school year", pl: "Nowy rok szkolny" },
    { en: "Extracurricular activities", pl: "Zajęcia pozalekcyjne" },
    { en: "Field trip", pl: "Wycieczka szkolna" },
    { en: "Halloween", pl: "Halloween" },
    { en: "Costume", pl: "Przebranie, kostium" },
    { en: "Trick or treat", pl: "Cukierek albo psikus" },
    { en: "Haunted house", pl: "Nawiedzony dom" },
    { en: "Spooky", pl: "Straszny" },
    { en: "Witch", pl: "Czarownica" },
    { en: "Ghost", pl: "Duch" },
    { en: "Skeleton", pl: "Szkielet" },
    { en: "Bat", pl: "Nietoperz" },
    { en: "Spider web", pl: "Pajęczyna" },
    { en: "Carved pumpkin", pl: "Wydrążona dynia" },
    { en: "All Saints' Day", pl: "Wszystkich Świętych" },
    { en: "Cemetery", pl: "Cmentarz" },
    { en: "Bonfire", pl: "Ognisko" },
    { en: "Cosy / Cozy", pl: "Przytulny" },
    { en: "To curl up on the sofa", pl: "Zwinąć się w kłębek na kanapie" },
    { en: "Hot drink", pl: "Ciepły napój" },
    { en: "Pumpkin soup", pl: "Krem z dyni" },
    { en: "Stew", pl: "Gulasz" },
    { en: "Comfort food", pl: "Jedzenie na pocieszenie" },
    { en: "Baked apple", pl: "Pieczone jabłko" },
    { en: "Cinnamon", pl: "Cynamon" },
    { en: "Herbal tea", pl: "Herbatka ziołowa" },
    { en: "To catch a cold", pl: "Przeziębić się" },
    { en: "Runny nose", pl: "Katar" },
    { en: "Sore throat", pl: "Ból gardła" },
    { en: "Flu jab / Flu shot", pl: "Szczepionka na grypę" },
    { en: "Cough", pl: "Kaszel" },
    { en: "Tissues", pl: "Chusteczki higieniczne" },
    { en: "Under the weather", pl: "Nie w formie" },
    { en: "Hiking boots", pl: "Buty trekkingowe" },
    { en: "Forest trail", pl: "Leśny szlak" },
    { en: "Deer rut", pl: "Rykowisko" },
    { en: "Moss", pl: "Mech" },
    { en: "Pine cone", pl: "Szyszka" },
    { en: "To turn on the heating", pl: "Włączyć ogrzewanie" },
    { en: "Weather forecast", pl: "Prognoza pogody" },
    { en: "Long weekend", pl: "Długi weekend" },
    { en: "Bank holiday", pl: "Dzień wolny, święto" },
    { en: "Black Friday sales", pl: "Wyprzedaże z okazji Black Friday" },
    { en: "To save up", pl: "Odkładać pieniądze" },
    { en: "Autumn equinox", pl: "Równonoc jesienna" },
    { en: "Harvest moon", pl: "Księżyc żniwiarzy" },
    { en: "To stay in", pl: "Zostać w domu" },
    { en: "Board game", pl: "Gra planszowa" },
    { en: "Movie night", pl: "Wieczór filmowy" },
    { en: "Rustling leaves", pl: "Szelest liści" },
    { en: "Change of season", pl: "Zmiana pory roku" },
    { en: "Wardrobe swap", pl: "Wymiana garderoby na sezon" },
    { en: "To put away summer clothes", pl: "Schować letnie ubrania" },
    { en: "To fall behind", pl: "Zostać w tyle" },
    { en: "To hit the books", pl: "Zabrać się do nauki" }
  ],
  invierno: [
    { en: "Winter", pl: "Zima" },
    { en: "Snow", pl: "Śnieg" },
    { en: "Snowflake", pl: "Płatek śniegu" },
    { en: "Snowfall", pl: "Opady śniegu" },
    { en: "Blizzard", pl: "Zamieć" },
    { en: "Sleet", pl: "Deszcz ze śniegiem" },
    { en: "Hail", pl: "Grad" },
    { en: "Frost", pl: "Szron" },
    { en: "Frosty morning", pl: "Mroźny poranek" },
    { en: "Black ice", pl: "Gołoledź" },
    { en: "Icicle", pl: "Sopel" },
    { en: "Slippery", pl: "Ślisko" },
    { en: "Below freezing", pl: "Poniżej zera" },
    { en: "It's freezing out there", pl: "Na dworze jest mróz" },
    { en: "Wind chill", pl: "Temperatura odczuwalna" },
    { en: "Cold snap", pl: "Fala mrozów" },
    { en: "To shiver", pl: "Trząść się z zimna" },
    { en: "Numb fingers", pl: "Zdrętwiałe palce" },
    { en: "Chapped lips", pl: "Spierzchnięte usta" },
    { en: "Goosebumps", pl: "Gęsia skórka" },
    { en: "Coat", pl: "Płaszcz" },
    { en: "Puffer jacket", pl: "Kurtka puchowa" },
    { en: "Gloves", pl: "Rękawiczki" },
    { en: "Mittens", pl: "Rękawiczki z jednym palcem" },
    { en: "Woolly hat / Beanie", pl: "Czapka" },
    { en: "Earmuffs", pl: "Nauszniki" },
    { en: "Thermal underwear", pl: "Bielizna termiczna" },
    { en: "Snow boots", pl: "Śniegowce" },
    { en: "Slippers", pl: "Kapcie" },
    { en: "Hot water bottle", pl: "Termofor" },
    { en: "Blanket", pl: "Koc" },
    { en: "Duvet", pl: "Kołdra" },
    { en: "Fireplace", pl: "Kominek" },
    { en: "Radiator", pl: "Kaloryfer" },
    { en: "Heater", pl: "Grzejnik, piecyk" },
    { en: "Thermostat", pl: "Termostat" },
    { en: "Electricity bill", pl: "Rachunek za prąd" },
    { en: "Power cut", pl: "Przerwa w dostawie prądu" },
    { en: "Wrap up warm", pl: "Ubierz się ciepło" },
    { en: "Steamy window", pl: "Zaparowane okno" },
    { en: "Hot chocolate", pl: "Gorąca czekolada" },
    { en: "Chocolate with churros", pl: "Czekolada z churros" },
    { en: "Soup", pl: "Zupa" },
    { en: "Broth", pl: "Rosół, bulion" },
    { en: "Chickpea stew", pl: "Gulasz z ciecierzycy" },
    { en: "Ski resort", pl: "Ośrodek narciarski" },
    { en: "Ski slope", pl: "Stok narciarski" },
    { en: "Ski lift", pl: "Wyciąg narciarski" },
    { en: "Chairlift", pl: "Wyciąg krzesełkowy" },
    { en: "Ski pass", pl: "Karnet narciarski" },
    { en: "Ski boots", pl: "Buty narciarskie" },
    { en: "Ski goggles", pl: "Gogle narciarskie" },
    { en: "Sledge / Sled", pl: "Sanki" },
    { en: "Snowman", pl: "Bałwan" },
    { en: "Snowball fight", pl: "Bitwa na śnieżki" },
    { en: "Ice skating", pl: "Jazda na łyżwach" },
    { en: "Ice rink", pl: "Lodowisko" },
    { en: "Snow-capped mountains", pl: "Ośnieżone góry" },
    { en: "Frozen lake", pl: "Zamarznięte jezioro" },
    { en: "Snowdrift", pl: "Zaspa" },
    { en: "Snow day", pl: "Dzień bez lekcji z powodu śniegu" },
    { en: "Snowed in", pl: "Zasypani śniegiem" },
    { en: "Snow chains", pl: "Łańcuchy na koła" },
    { en: "Snowplough / Snowplow", pl: "Pług śnieżny" },
    { en: "The roads are icy", pl: "Na drogach jest ślisko" },
    { en: "To defrost the windscreen", pl: "Odmrozić szybę" },
    { en: "Christmas", pl: "Boże Narodzenie" },
    { en: "Christmas Eve", pl: "Wigilia" },
    { en: "Merry Christmas!", pl: "Wesołych Świąt!" },
    { en: "Season's greetings", pl: "Pozdrowienia świąteczne" },
    { en: "Christmas tree", pl: "Choinka" },
    { en: "Nativity scene", pl: "Szopka" },
    { en: "Fairy lights", pl: "Lampki choinkowe" },
    { en: "Tinsel", pl: "Łańcuch choinkowy" },
    { en: "Bauble", pl: "Bombka" },
    { en: "Wreath", pl: "Wieniec" },
    { en: "Mistletoe", pl: "Jemioła" },
    { en: "Advent calendar", pl: "Kalendarz adwentowy" },
    { en: "Wrapping paper", pl: "Papier do pakowania" },
    { en: "To wrap presents", pl: "Pakować prezenty" },
    { en: "Secret Santa", pl: "Losowanie prezentów (Secret Santa)" },
    { en: "Christmas carol", pl: "Kolęda" },
    { en: "Christmas lottery", pl: "Loteria bożonarodzeniowa" },
    { en: "Nougat", pl: "Nugat, turron" },
    { en: "Marzipan", pl: "Marcepan" },
    { en: "Gingerbread", pl: "Piernik" },
    { en: "Candy cane", pl: "Laska cukrowa" },
    { en: "Reindeer", pl: "Renifer" },
    { en: "Santa Claus", pl: "Święty Mikołaj" },
    { en: "Family dinner", pl: "Kolacja rodzinna" },
    { en: "Leftovers", pl: "Resztki" },
    { en: "New Year's Eve", pl: "Sylwester" },
    { en: "The twelve grapes", pl: "Dwanaście winogron (tradycja hiszpańska)" },
    { en: "Countdown", pl: "Odliczanie" },
    { en: "Midnight toast", pl: "Toast o północy" },
    { en: "Cheers!", pl: "Na zdrowie!" },
    { en: "Happy New Year!", pl: "Szczęśliwego Nowego Roku!" },
    { en: "New Year's resolution", pl: "Postanowienie noworoczne" },
    { en: "A fresh start", pl: "Nowy początek" },
    { en: "Three Kings' Day", pl: "Święto Trzech Króli" },
    { en: "Kings' parade", pl: "Orszak Trzech Króli" },
    { en: "King cake", pl: "Ciasto Trzech Króli" },
    { en: "Winter sales", pl: "Zimowe wyprzedaże" },
    { en: "Gift receipt", pl: "Paragon prezentowy" },
    { en: "To return something", pl: "Zwrócić coś" },
    { en: "Christmas holidays", pl: "Przerwa świąteczna" },
    { en: "Report card", pl: "Świadectwo" },
    { en: "End of term", pl: "Koniec semestru" },
    { en: "Exam period", pl: "Sesja egzaminacyjna" },
    { en: "To cram", pl: "Wkuwać" },
    { en: "Winter solstice", pl: "Przesilenie zimowe" },
    { en: "The shortest day", pl: "Najkrótszy dzień" },
    { en: "Long nights", pl: "Długie noce" },
    { en: "Cabin fever", pl: "Klaustrofobia od siedzenia w domu" },
    { en: "Flu season", pl: "Sezon grypowy" },
    { en: "Fever", pl: "Gorączka" },
    { en: "Cough syrup", pl: "Syrop na kaszel" },
    { en: "To stay in bed", pl: "Leżeć w łóżku" },
    { en: "Get well soon", pl: "Wracaj do zdrowia" },
    { en: "Valentine's Day", pl: "Walentynki" },
    { en: "Carnival", pl: "Karnawał" },
    { en: "Fancy dress party", pl: "Bal przebierańców" },
    { en: "To hibernate", pl: "Zapaść w sen zimowy" },
    { en: "Winter wonderland", pl: "Zimowa kraina czarów" },
    { en: "To break the ice", pl: "Przełamać lody" }
  ],
  social: [
    { en: "Nice to meet you", pl: "Miło Cię poznać" },
    { en: "How's it going?", pl: "Jak leci?" },
    { en: "What's up?", pl: "Co słychać?" },
    { en: "Long time no see", pl: "Kopę lat!" },
    { en: "How have you been?", pl: "Co u Ciebie słychać?" },
    { en: "I'm doing well, thanks", pl: "Dobrze, dziękuję" },
    { en: "Not bad at all", pl: "Całkiem nieźle" },
    { en: "Same as always", pl: "Po staremu" },
    { en: "Take care", pl: "Trzymaj się" },
    { en: "See you later", pl: "Na razie" },
    { en: "See you around", pl: "Do zobaczenia" },
    { en: "Catch you later", pl: "Pogadamy później" },
    { en: "Have a good one", pl: "Miłego dnia" },
    { en: "Talk to you soon", pl: "Odezwę się wkrótce" },
    { en: "Say hi to your parents", pl: "Pozdrów rodziców" },
    { en: "Thanks a lot", pl: "Dzięki wielkie" },
    { en: "Thanks anyway", pl: "I tak dziękuję" },
    { en: "You're welcome", pl: "Proszę bardzo, nie ma za co" },
    { en: "No worries", pl: "Nie przejmuj się" },
    { en: "My pleasure", pl: "Cała przyjemność po mojej stronie" },
    { en: "Don't mention it", pl: "Nie ma o czym mówić" },
    { en: "Excuse me", pl: "Przepraszam (żeby zwrócić uwagę)" },
    { en: "Sorry to bother you", pl: "Przepraszam, że przeszkadzam" },
    { en: "I'm so sorry", pl: "Bardzo mi przykro" },
    { en: "My bad", pl: "Mój błąd" },
    { en: "Never mind", pl: "Nieważne" },
    { en: "It doesn't matter", pl: "Nic nie szkodzi" },
    { en: "Congratulations!", pl: "Gratulacje!" },
    { en: "Well done!", pl: "Brawo!" },
    { en: "Good luck!", pl: "Powodzenia!" },
    { en: "Fingers crossed", pl: "Trzymajmy kciuki" },
    { en: "Cheer up!", pl: "Głowa do góry!" },
    { en: "Have fun!", pl: "Baw się dobrze!" },
    { en: "Enjoy your meal", pl: "Smacznego" },
    { en: "Bless you!", pl: "Na zdrowie! (po kichnięciu)" },
    { en: "Make yourself at home", pl: "Czuj się jak u siebie" },
    { en: "Help yourself", pl: "Częstuj się" },
    { en: "After you", pl: "Ty pierwszy / Proszę przodem" },
    { en: "Can I join you?", pl: "Mogę się dosiąść?" },
    { en: "Do you mind if I sit here?", pl: "Mogę tu usiąść?" },
    { en: "Let me introduce you to…", pl: "Przedstawiam Ci…" },
    { en: "This is my friend…", pl: "To mój przyjaciel…" },
    { en: "Where are you from?", pl: "Skąd jesteś?" },
    { en: "What do you do?", pl: "Czym się zajmujesz?" },
    { en: "How old are you?", pl: "Ile masz lat?" },
    { en: "What's your name again?", pl: "Przypomnisz mi, jak masz na imię?" },
    { en: "I've heard a lot about you", pl: "Dużo o Tobie słyszałem" },
    { en: "It was nice talking to you", pl: "Miło było porozmawiać" },
    { en: "Let's keep in touch", pl: "Bądźmy w kontakcie" },
    { en: "Give me a call", pl: "Zadzwoń do mnie" },
    { en: "Drop me a line", pl: "Napisz do mnie" },
    { en: "Let's hang out sometime", pl: "Spotkajmy się kiedyś" },
    { en: "Are you free tonight?", pl: "Masz czas dziś wieczorem?" },
    { en: "What are you up to?", pl: "Co porabiasz?" },
    { en: "Do you want to grab a coffee?", pl: "Pójdziemy na kawę?" },
    { en: "I'm in!", pl: "Wchodzę w to!" },
    { en: "Count me out", pl: "Beze mnie" },
    { en: "Maybe next time", pl: "Może następnym razem" },
    { en: "I'll let you know", pl: "Dam Ci znać" },
    { en: "Sounds good", pl: "Brzmi dobrze" },
    { en: "Sounds like a plan", pl: "Dobry plan" },
    { en: "Deal!", pl: "Umowa stoi!" },
    { en: "It's up to you", pl: "To zależy od Ciebie" },
    { en: "Whatever you prefer", pl: "Jak wolisz" },
    { en: "I don't mind", pl: "Wszystko mi jedno" },
    { en: "Fair enough", pl: "W porządku, rozumiem" },
    { en: "Good point", pl: "Słuszna uwaga" },
    { en: "Happy birthday!", pl: "Wszystkiego najlepszego!" },
    { en: "Many happy returns", pl: "Sto lat!" },
    { en: "My condolences", pl: "Wyrazy współczucia" },
    { en: "Welcome back!", pl: "Witaj z powrotem!" },
    { en: "Safe trip!", pl: "Szczęśliwej podróży!" },
    { en: "Have a nice weekend", pl: "Miłego weekendu" },
    { en: "Same to you", pl: "Wzajemnie" },
    { en: "You too", pl: "Ty też" },
    { en: "How kind of you", pl: "Jak miło" },
    { en: "That's very nice of you", pl: "To bardzo miłe z Twojej strony" },
    { en: "I owe you one", pl: "Wiszę Ci przysługę" },
    { en: "It's on me", pl: "Ja stawiam" },
    { en: "Let's split the bill", pl: "Podzielmy rachunek" },
    { en: "Party", pl: "Impreza" },
    { en: "Get-together", pl: "Spotkanie, spotkanko" },
    { en: "Housewarming party", pl: "Parapetówka" },
    { en: "Surprise party", pl: "Przyjęcie niespodzianka" },
    { en: "Sleepover", pl: "Piżama party" },
    { en: "Guest", pl: "Gość" },
    { en: "Host", pl: "Gospodarz" },
    { en: "To RSVP", pl: "Potwierdzić przybycie" }
  ],
  conversacion: [
    { en: "I think so", pl: "Chyba tak" },
    { en: "I don't think so", pl: "Chyba nie" },
    { en: "I guess so", pl: "Przypuszczam, że tak" },
    { en: "I agree", pl: "Zgadzam się" },
    { en: "I totally agree", pl: "Całkowicie się zgadzam" },
    { en: "I disagree", pl: "Nie zgadzam się" },
    { en: "I'm not sure", pl: "Nie jestem pewien" },
    { en: "It depends", pl: "To zależy" },
    { en: "In my opinion", pl: "Moim zdaniem" },
    { en: "As far as I know", pl: "O ile wiem" },
    { en: "If I'm not mistaken", pl: "Jeśli się nie mylę" },
    { en: "To be honest", pl: "Szczerze mówiąc" },
    { en: "Frankly", pl: "Szczerze" },
    { en: "Let me think", pl: "Daj mi pomyśleć" },
    { en: "That makes sense", pl: "To ma sens" },
    { en: "That doesn't make sense", pl: "To nie ma sensu" },
    { en: "I see what you mean", pl: "Rozumiem, o co Ci chodzi" },
    { en: "What do you mean?", pl: "Co masz na myśli?" },
    { en: "Could you repeat that?", pl: "Możesz powtórzyć?" },
    { en: "Could you speak more slowly?", pl: "Możesz mówić wolniej?" },
    { en: "How do you say … in English?", pl: "Jak się mówi … po angielsku?" },
    { en: "What does … mean?", pl: "Co znaczy …?" },
    { en: "How do you spell it?", pl: "Jak to się pisze?" },
    { en: "I didn't catch that", pl: "Nie dosłyszałem" },
    { en: "Sorry, I lost you", pl: "Przepraszam, zgubiłem się" },
    { en: "Got it", pl: "Jasne, rozumiem" },
    { en: "Exactly", pl: "Dokładnie" },
    { en: "Absolutely", pl: "Absolutnie" },
    { en: "Of course", pl: "Oczywiście" },
    { en: "Sure", pl: "Jasne, pewnie" },
    { en: "No way!", pl: "Nie może być! / Nie ma mowy!" },
    { en: "Really?", pl: "Naprawdę?" },
    { en: "Are you kidding?", pl: "Żartujesz?" },
    { en: "I can't believe it", pl: "Nie mogę w to uwierzyć" },
    { en: "That's amazing", pl: "To niesamowite" },
    { en: "That's a shame", pl: "Szkoda" },
    { en: "What a pity", pl: "Jaka szkoda" },
    { en: "Lucky you!", pl: "Ale masz szczęście!" },
    { en: "Good for you", pl: "Cieszę się Twoim szczęściem" },
    { en: "Tell me about it", pl: "Mnie to mówisz?" },
    { en: "You can say that again", pl: "Święta prawda" },
    { en: "I couldn't care less", pl: "Mam to gdzieś" },
    { en: "It's not a big deal", pl: "To nic wielkiego" },
    { en: "Whatever", pl: "Wszystko jedno" },
    { en: "Anyway", pl: "W każdym razie" },
    { en: "By the way", pl: "Przy okazji" },
    { en: "Speaking of which", pl: "A propos" },
    { en: "Long story short", pl: "Krótko mówiąc" },
    { en: "Guess what?", pl: "Wiesz co?" },
    { en: "You know what?", pl: "Wiesz, co?" },
    { en: "The thing is…", pl: "Chodzi o to, że…" },
    { en: "What I'm trying to say is…", pl: "Chcę powiedzieć, że…" },
    { en: "Let me put it another way", pl: "Powiem to inaczej" },
    { en: "For example", pl: "Na przykład" },
    { en: "Such as", pl: "Taki jak, na przykład" },
    { en: "In other words", pl: "Innymi słowy" },
    { en: "On the one hand", pl: "Z jednej strony" },
    { en: "On the other hand", pl: "Z drugiej strony" },
    { en: "However", pl: "Jednak" },
    { en: "Although", pl: "Chociaż" },
    { en: "Even though", pl: "Mimo że" },
    { en: "Despite", pl: "Pomimo" },
    { en: "Therefore", pl: "Dlatego" },
    { en: "Because of", pl: "Z powodu" },
    { en: "As a result", pl: "W rezultacie" },
    { en: "Instead of", pl: "Zamiast" },
    { en: "Apart from", pl: "Oprócz" },
    { en: "Besides", pl: "Poza tym" },
    { en: "Actually", pl: "Właściwie" },
    { en: "Basically", pl: "W zasadzie" },
    { en: "Obviously", pl: "Oczywiście" },
    { en: "Apparently", pl: "Podobno" },
    { en: "Hopefully", pl: "Miejmy nadzieję" },
    { en: "Luckily", pl: "Na szczęście" },
    { en: "Unfortunately", pl: "Niestety" },
    { en: "Eventually", pl: "W końcu" },
    { en: "Meanwhile", pl: "W międzyczasie" },
    { en: "At least", pl: "Przynajmniej" },
    { en: "At first", pl: "Na początku" },
    { en: "In the end", pl: "Na koniec" },
    { en: "So far", pl: "Do tej pory" },
    { en: "From now on", pl: "Od teraz" },
    { en: "Sooner or later", pl: "Prędzej czy później" },
    { en: "Just in case", pl: "Na wszelki wypadek" },
    { en: "No matter what", pl: "Bez względu na wszystko" },
    { en: "As soon as possible", pl: "Jak najszybciej" },
    { en: "More or less", pl: "Mniej więcej" },
    { en: "Kind of", pl: "Tak jakby" },
    { en: "Sort of", pl: "Coś w tym stylu" },
    { en: "Pretty much", pl: "Praktycznie" },
    { en: "Not at all", pl: "Wcale nie" },
    { en: "Not really", pl: "Raczej nie" },
    { en: "I have no idea", pl: "Nie mam pojęcia" },
    { en: "Beats me", pl: "Nie wiem" },
    { en: "Who knows?", pl: "Kto wie?" },
    { en: "It's hard to say", pl: "Trudno powiedzieć" },
    { en: "Let's see", pl: "Zobaczmy" },
    { en: "Hold on", pl: "Chwileczkę" },
    { en: "Just a second", pl: "Sekundę" },
    { en: "Go ahead", pl: "Proszę, śmiało" },
    { en: "Keep going", pl: "Mów dalej" }
  ],
  restaurante: [
    { en: "A table for two, please", pl: "Stolik dla dwóch osób, proszę" },
    { en: "Do you have a reservation?", pl: "Czy ma Pan rezerwację?" },
    { en: "I booked a table", pl: "Zarezerwowałem stolik" },
    { en: "Can I see the menu?", pl: "Mogę prosić o menu?" },
    { en: "What do you recommend?", pl: "Co Pan poleca?" },
    { en: "What's the dish of the day?", pl: "Jakie jest danie dnia?" },
    { en: "I'd like…", pl: "Poproszę…" },
    { en: "I'll have the…", pl: "Wezmę…" },
    { en: "Same for me", pl: "Dla mnie to samo" },
    { en: "Can I order?", pl: "Mogę zamówić?" },
    { en: "Starter", pl: "Przystawka" },
    { en: "Main course", pl: "Danie główne" },
    { en: "Side dish", pl: "Dodatek" },
    { en: "Dessert", pl: "Deser" },
    { en: "Set menu", pl: "Zestaw dnia" },
    { en: "Tap water", pl: "Woda z kranu" },
    { en: "Still water", pl: "Woda niegazowana" },
    { en: "Sparkling water", pl: "Woda gazowana" },
    { en: "Soft drink", pl: "Napój gazowany" },
    { en: "Draught beer", pl: "Piwo z beczki" },
    { en: "A glass of red wine", pl: "Kieliszek czerwonego wina" },
    { en: "Rare / Medium / Well done", pl: "Krwisty / Średnio wysmażony / Dobrze wysmażony" },
    { en: "Grilled", pl: "Z grilla, z płyty" },
    { en: "Fried", pl: "Smażony" },
    { en: "Roasted", pl: "Pieczony" },
    { en: "Boiled", pl: "Gotowany" },
    { en: "Steamed", pl: "Na parze" },
    { en: "Spicy", pl: "Ostry" },
    { en: "Mild", pl: "Łagodny" },
    { en: "Salty", pl: "Słony" },
    { en: "Sweet", pl: "Słodki" },
    { en: "Sour", pl: "Kwaśny" },
    { en: "Bitter", pl: "Gorzki" },
    { en: "Tasty", pl: "Smaczny" },
    { en: "Delicious", pl: "Pyszny" },
    { en: "Bland", pl: "Mdły" },
    { en: "Greasy", pl: "Tłusty" },
    { en: "Crunchy", pl: "Chrupiący" },
    { en: "Juicy", pl: "Soczysty" },
    { en: "Homemade", pl: "Domowy" },
    { en: "Leftover food", pl: "Resztki jedzenia" },
    { en: "I'm a vegetarian", pl: "Jestem wegetarianinem" },
    { en: "I'm allergic to nuts", pl: "Mam alergię na orzechy" },
    { en: "Gluten-free", pl: "Bezglutenowy" },
    { en: "Dairy-free", pl: "Bez nabiału" },
    { en: "Does it contain…?", pl: "Czy to zawiera…?" },
    { en: "Without onion, please", pl: "Bez cebuli, proszę" },
    { en: "Could I have some more bread?", pl: "Mogę prosić o więcej chleba?" },
    { en: "Can we have the bill, please?", pl: "Poprosimy rachunek" },
    { en: "Check, please", pl: "Rachunek, proszę" },
    { en: "Is service included?", pl: "Czy obsługa jest wliczona?" },
    { en: "Keep the change", pl: "Reszty nie trzeba" },
    { en: "To tip", pl: "Dać napiwek" },
    { en: "Takeaway / To go", pl: "Na wynos" },
    { en: "To eat in", pl: "Na miejscu" },
    { en: "Can I pay by card?", pl: "Mogę zapłacić kartą?" },
    { en: "Cutlery", pl: "Sztućce" },
    { en: "Fork", pl: "Widelec" },
    { en: "Knife", pl: "Nóż" },
    { en: "Spoon", pl: "Łyżka" },
    { en: "Napkin", pl: "Serwetka" },
    { en: "Plate", pl: "Talerz" },
    { en: "Bowl", pl: "Miska" },
    { en: "Glass", pl: "Szklanka" },
    { en: "Mug", pl: "Kubek" },
    { en: "Jug", pl: "Dzbanek" },
    { en: "Waiter / Waitress", pl: "Kelner / Kelnerka" },
    { en: "Chef", pl: "Kucharz, szef kuchni" },
    { en: "Snack", pl: "Przekąska" },
    { en: "Breakfast", pl: "Śniadanie" },
    { en: "Brunch", pl: "Brunch" },
    { en: "Lunch", pl: "Obiad" },
    { en: "Dinner", pl: "Kolacja" },
    { en: "To have a bite", pl: "Przekąsić coś" },
    { en: "I'm starving", pl: "Umieram z głodu" },
    { en: "I'm full", pl: "Najadłem się" },
    { en: "I'm thirsty", pl: "Chce mi się pić" },
    { en: "It's my treat", pl: "Ja stawiam" },
    { en: "Fast food", pl: "Fast food" },
    { en: "Food truck", pl: "Food truck" },
    { en: "Buffet", pl: "Bufet" },
    { en: "To toast", pl: "Wznieść toast" },
    { en: "Scrambled eggs", pl: "Jajecznica" },
    { en: "Fried egg", pl: "Jajko sadzone" },
    { en: "Toast", pl: "Tost" },
    { en: "Butter", pl: "Masło" },
    { en: "Jam", pl: "Dżem" },
    { en: "Cereal", pl: "Płatki śniadaniowe" },
    { en: "Orange juice", pl: "Sok pomarańczowy" },
    { en: "Decaf", pl: "Kawa bezkofeinowa" },
    { en: "Coffee with milk", pl: "Kawa z mlekiem" },
    { en: "Black coffee", pl: "Czarna kawa" },
    { en: "Herbal infusion", pl: "Herbatka ziołowa" },
    { en: "Sandwich", pl: "Kanapka" },
    { en: "Wrap", pl: "Wrap, tortilla z nadzieniem" },
    { en: "Salad", pl: "Sałatka" },
    { en: "Steak", pl: "Stek" },
    { en: "Chicken breast", pl: "Pierś z kurczaka" },
    { en: "Pork", pl: "Wieprzowina" },
    { en: "Lamb chop", pl: "Kotlet jagnięcy" },
    { en: "Seafood platter", pl: "Półmisek owoców morza" },
    { en: "Prawns", pl: "Krewetki" },
    { en: "Squid rings", pl: "Krążki kalmarów" },
    { en: "Octopus", pl: "Ośmiornica" },
    { en: "Cod", pl: "Dorsz" },
    { en: "Hake", pl: "Morszczuk" },
    { en: "Tuna", pl: "Tuńczyk" },
    { en: "Salmon", pl: "Łosoś" },
    { en: "Rice", pl: "Ryż" },
    { en: "Pasta", pl: "Makaron" },
    { en: "Lentils", pl: "Soczewica" },
    { en: "Chickpeas", pl: "Ciecierzyca" },
    { en: "Mushrooms", pl: "Pieczarki" },
    { en: "Garlic", pl: "Czosnek" },
    { en: "Onion", pl: "Cebula" },
    { en: "Pepper (vegetable)", pl: "Papryka" },
    { en: "Black pepper", pl: "Pieprz" },
    { en: "Olive oil", pl: "Oliwa z oliwek" },
    { en: "Vinegar", pl: "Ocet" },
    { en: "Salt", pl: "Sól" },
    { en: "Sugar", pl: "Cukier" },
    { en: "Flour", pl: "Mąka" },
    { en: "Cheese", pl: "Ser" },
    { en: "Cured ham", pl: "Szynka dojrzewająca" },
    { en: "Sausage", pl: "Kiełbasa, wędlina" },
    { en: "Bacon", pl: "Boczek" },
    { en: "Cake", pl: "Ciasto, tort" },
    { en: "Biscuit / Cookie", pl: "Ciastko, herbatnik" },
    { en: "Ice-cream cone", pl: "Rożek lodowy" }
  ],
  compras: [
    { en: "How much is it?", pl: "Ile to kosztuje?" },
    { en: "How much are these?", pl: "Ile kosztują te?" },
    { en: "Do you have this in a smaller size?", pl: "Czy jest mniejszy rozmiar?" },
    { en: "Do you have it in another colour?", pl: "Czy jest w innym kolorze?" },
    { en: "Can I try it on?", pl: "Mogę przymierzyć?" },
    { en: "Where are the fitting rooms?", pl: "Gdzie są przymierzalnie?" },
    { en: "It fits me well", pl: "Dobrze leży" },
    { en: "It's too tight", pl: "Jest za ciasne" },
    { en: "It's too loose", pl: "Jest za luźne" },
    { en: "It doesn't suit me", pl: "Nie pasuje mi" },
    { en: "I'm just looking", pl: "Tylko się rozglądam" },
    { en: "I'll take it", pl: "Wezmę to" },
    { en: "I'll think about it", pl: "Zastanowię się" },
    { en: "Is it on sale?", pl: "Czy to jest w promocji?" },
    { en: "Discount", pl: "Zniżka" },
    { en: "Bargain", pl: "Okazja" },
    { en: "Rip-off", pl: "Zdzierstwo" },
    { en: "Expensive", pl: "Drogi" },
    { en: "Cheap", pl: "Tani" },
    { en: "Affordable", pl: "Przystępny cenowo" },
    { en: "Price tag", pl: "Metka z ceną" },
    { en: "Receipt", pl: "Paragon" },
    { en: "Refund", pl: "Zwrot pieniędzy" },
    { en: "Exchange", pl: "Wymiana" },
    { en: "Can I return it?", pl: "Mogę to zwrócić?" },
    { en: "Cashier", pl: "Kasjer" },
    { en: "Checkout", pl: "Kasa" },
    { en: "Queue / Line", pl: "Kolejka" },
    { en: "Shopping basket", pl: "Koszyk" },
    { en: "Shopping trolley / cart", pl: "Wózek sklepowy" },
    { en: "Shopping bag", pl: "Torba na zakupy" },
    { en: "Shopping centre / mall", pl: "Centrum handlowe" },
    { en: "Supermarket", pl: "Supermarket" },
    { en: "Grocery store", pl: "Sklep spożywczy" },
    { en: "Bakery", pl: "Piekarnia" },
    { en: "Butcher's", pl: "Sklep mięsny" },
    { en: "Fishmonger's", pl: "Sklep rybny" },
    { en: "Greengrocer's", pl: "Warzywniak" },
    { en: "Chemist's / Pharmacy", pl: "Apteka" },
    { en: "Bookshop", pl: "Księgarnia" },
    { en: "Stationery shop", pl: "Sklep papierniczy" },
    { en: "Hardware store", pl: "Sklep żelazny" },
    { en: "Department store", pl: "Dom towarowy" },
    { en: "Second-hand", pl: "Używany, z drugiej ręki" },
    { en: "Online shopping", pl: "Zakupy przez internet" },
    { en: "Delivery", pl: "Dostawa" },
    { en: "Free shipping", pl: "Darmowa wysyłka" },
    { en: "Out of stock", pl: "Wyprzedane" },
    { en: "In stock", pl: "Dostępne" },
    { en: "Brand", pl: "Marka" },
    { en: "Size", pl: "Rozmiar" },
    { en: "Shoe size", pl: "Rozmiar buta" },
    { en: "Wallet", pl: "Portfel" },
    { en: "Purse", pl: "Portmonetka, torebka" },
    { en: "Cash", pl: "Gotówka" },
    { en: "Change (money)", pl: "Reszta" },
    { en: "Coins", pl: "Monety" },
    { en: "Notes / Bills", pl: "Banknoty" },
    { en: "Credit card", pl: "Karta kredytowa" },
    { en: "Debit card", pl: "Karta debetowa" },
    { en: "PIN number", pl: "Kod PIN" },
    { en: "Contactless", pl: "Zbliżeniowo" },
    { en: "To pay in instalments", pl: "Płacić w ratach" },
    { en: "To save money", pl: "Oszczędzać pieniądze" },
    { en: "To spend money", pl: "Wydawać pieniądze" },
    { en: "To waste money", pl: "Marnować pieniądze" },
    { en: "To lend", pl: "Pożyczyć (komuś)" },
    { en: "To borrow", pl: "Pożyczyć (od kogoś)" },
    { en: "To owe", pl: "Być winnym (pieniądze)" },
    { en: "Bank account", pl: "Konto bankowe" },
    { en: "Cash machine / ATM", pl: "Bankomat" },
    { en: "To withdraw money", pl: "Wypłacić pieniądze" },
    { en: "Pocket money", pl: "Kieszonkowe" },
    { en: "Budget", pl: "Budżet" },
    { en: "Bill (invoice)", pl: "Rachunek, faktura" },
    { en: "Rent", pl: "Czynsz" },
    { en: "Deposit", pl: "Kaucja" }
  ],
  viajes: [
    { en: "Where is the train station?", pl: "Gdzie jest dworzec kolejowy?" },
    { en: "How do I get to…?", pl: "Jak dojść do…?" },
    { en: "Is it far from here?", pl: "Czy to daleko stąd?" },
    { en: "Is it within walking distance?", pl: "Czy da się dojść pieszo?" },
    { en: "A single ticket, please", pl: "Bilet w jedną stronę, proszę" },
    { en: "A return ticket", pl: "Bilet w obie strony" },
    { en: "What time does it leave?", pl: "O której odjeżdża?" },
    { en: "What time does it arrive?", pl: "O której przyjeżdża?" },
    { en: "Which platform?", pl: "Który peron?" },
    { en: "Does this bus go to…?", pl: "Czy ten autobus jedzie do…?" },
    { en: "Where do I change?", pl: "Gdzie mam się przesiąść?" },
    { en: "Next stop", pl: "Następny przystanek" },
    { en: "Bus stop", pl: "Przystanek autobusowy" },
    { en: "Underground / Subway", pl: "Metro" },
    { en: "Tram", pl: "Tramwaj" },
    { en: "Coach", pl: "Autokar" },
    { en: "Taxi rank", pl: "Postój taksówek" },
    { en: "Rush hour", pl: "Godziny szczytu" },
    { en: "Fare", pl: "Cena biletu" },
    { en: "Travel card", pl: "Bilet okresowy" },
    { en: "To get on", pl: "Wsiadać" },
    { en: "To get off", pl: "Wysiadać" },
    { en: "To catch the bus", pl: "Złapać autobus" },
    { en: "To miss the train", pl: "Spóźnić się na pociąg" },
    { en: "Delay", pl: "Opóźnienie" },
    { en: "Cancelled", pl: "Odwołany" },
    { en: "On time", pl: "Punktualnie" },
    { en: "Departures", pl: "Odloty" },
    { en: "Arrivals", pl: "Przyloty" },
    { en: "Gate", pl: "Wyjście do samolotu" },
    { en: "Boarding", pl: "Wejście na pokład" },
    { en: "Window seat", pl: "Miejsce przy oknie" },
    { en: "Aisle seat", pl: "Miejsce przy przejściu" },
    { en: "Seatbelt", pl: "Pas bezpieczeństwa" },
    { en: "Take-off", pl: "Start" },
    { en: "Landing", pl: "Lądowanie" },
    { en: "Luggage / Baggage", pl: "Bagaż" },
    { en: "Checked luggage", pl: "Bagaż rejestrowany" },
    { en: "Baggage claim", pl: "Odbiór bagażu" },
    { en: "Lost luggage", pl: "Zagubiony bagaż" },
    { en: "Hand luggage", pl: "Bagaż podręczny (UK)" },
    { en: "Security check", pl: "Kontrola bezpieczeństwa" },
    { en: "Passport control", pl: "Kontrola paszportowa" },
    { en: "Visa", pl: "Wiza" },
    { en: "Round trip", pl: "Podróż w obie strony" },
    { en: "One-way trip", pl: "Podróż w jedną stronę" },
    { en: "Direct flight", pl: "Lot bezpośredni" },
    { en: "Connecting flight", pl: "Lot z przesiadką" },
    { en: "Flight attendant", pl: "Steward / stewardesa" },
    { en: "Pilot", pl: "Pilot" },
    { en: "Travel agency", pl: "Biuro podróży" },
    { en: "Package holiday", pl: "Wycieczka zorganizowana" },
    { en: "Sightseeing", pl: "Zwiedzanie" },
    { en: "Tourist attraction", pl: "Atrakcja turystyczna" },
    { en: "Guided tour", pl: "Wycieczka z przewodnikiem" },
    { en: "Map", pl: "Mapa" },
    { en: "Guidebook", pl: "Przewodnik (książka)" },
    { en: "Hotel", pl: "Hotel" },
    { en: "Hostel", pl: "Hostel" },
    { en: "Bed and breakfast", pl: "Nocleg ze śniadaniem" },
    { en: "Do you have any rooms available?", pl: "Czy są wolne pokoje?" },
    { en: "Single room", pl: "Pokój jednoosobowy" },
    { en: "Double room", pl: "Pokój dwuosobowy z dużym łóżkiem" },
    { en: "Twin room", pl: "Pokój z dwoma łóżkami" },
    { en: "Check-in time", pl: "Godzina zameldowania" },
    { en: "Check-out time", pl: "Godzina wymeldowania" },
    { en: "Reception", pl: "Recepcja" },
    { en: "Room key", pl: "Klucz do pokoju" },
    { en: "Room service", pl: "Obsługa pokoju" },
    { en: "Is breakfast included?", pl: "Czy śniadanie jest wliczone?" },
    { en: "Wake-up call", pl: "Budzenie telefoniczne" },
    { en: "The Wi-Fi password, please", pl: "Poproszę hasło do Wi-Fi" },
    { en: "Book in advance", pl: "Zarezerwować z wyprzedzeniem" },
    { en: "Fully booked", pl: "Brak wolnych miejsc" },
    { en: "Backpack", pl: "Plecak" },
    { en: "To travel light", pl: "Podróżować z małym bagażem" },
    { en: "To go abroad", pl: "Wyjechać za granicę" },
    { en: "Overseas", pl: "Za granicą" },
    { en: "Foreigner", pl: "Obcokrajowiec" },
    { en: "Local", pl: "Miejscowy" },
    { en: "Currency exchange", pl: "Kantor, wymiana walut" },
    { en: "Exchange rate", pl: "Kurs walut" },
    { en: "Embassy", pl: "Ambasada" },
    { en: "Travel insurance", pl: "Ubezpieczenie podróżne" },
    { en: "To rent a car", pl: "Wynająć samochód" },
    { en: "Driving licence", pl: "Prawo jazdy" },
    { en: "Petrol station / Gas station", pl: "Stacja benzynowa" },
    { en: "To fill up the tank", pl: "Zatankować do pełna" },
    { en: "Parking space", pl: "Miejsce parkingowe" },
    { en: "Car park / Parking lot", pl: "Parking" },
    { en: "Speed limit", pl: "Ograniczenie prędkości" },
    { en: "Traffic lights", pl: "Sygnalizacja świetlna" },
    { en: "Roundabout", pl: "Rondo" },
    { en: "Motorway / Highway", pl: "Autostrada" }
  ],
  ciudad: [
    { en: "Turn left", pl: "Skręć w lewo" },
    { en: "Turn right", pl: "Skręć w prawo" },
    { en: "Go straight on", pl: "Idź prosto" },
    { en: "Take the first left", pl: "Pierwsza w lewo" },
    { en: "At the end of the street", pl: "Na końcu ulicy" },
    { en: "On the corner", pl: "Na rogu" },
    { en: "Next to", pl: "Obok" },
    { en: "Opposite", pl: "Naprzeciwko" },
    { en: "Between", pl: "Między" },
    { en: "Behind", pl: "Za" },
    { en: "In front of", pl: "Przed" },
    { en: "Around the corner", pl: "Za rogiem" },
    { en: "Across the street", pl: "Po drugiej stronie ulicy" },
    { en: "Block", pl: "Kwartał, przecznica" },
    { en: "Crossroads", pl: "Skrzyżowanie" },
    { en: "Zebra crossing", pl: "Przejście dla pieszych" },
    { en: "Pavement / Sidewalk", pl: "Chodnik" },
    { en: "Square", pl: "Plac" },
    { en: "Avenue", pl: "Aleja" },
    { en: "Neighbourhood", pl: "Dzielnica, okolica" },
    { en: "Downtown / City centre", pl: "Centrum miasta" },
    { en: "Outskirts", pl: "Obrzeża" },
    { en: "Suburbs", pl: "Przedmieścia" },
    { en: "Town hall", pl: "Ratusz, urząd miasta" },
    { en: "Post office", pl: "Poczta" },
    { en: "Police station", pl: "Komisariat policji" },
    { en: "Fire station", pl: "Remiza strażacka" },
    { en: "Hospital", pl: "Szpital" },
    { en: "Library", pl: "Biblioteka" },
    { en: "Museum", pl: "Muzeum" },
    { en: "Art gallery", pl: "Galeria sztuki" },
    { en: "Theatre", pl: "Teatr" },
    { en: "Cinema / Movie theater", pl: "Kino" },
    { en: "Stadium", pl: "Stadion" },
    { en: "Gym", pl: "Siłownia" },
    { en: "Swimming baths", pl: "Pływalnia miejska" },
    { en: "Park", pl: "Park" },
    { en: "Playground", pl: "Plac zabaw" },
    { en: "Church", pl: "Kościół" },
    { en: "Cathedral", pl: "Katedra" },
    { en: "Palace", pl: "Pałac" },
    { en: "Market", pl: "Targ, rynek" },
    { en: "Bridge", pl: "Most" },
    { en: "Fountain", pl: "Fontanna" },
    { en: "Statue", pl: "Pomnik" },
    { en: "Skyscraper", pl: "Wieżowiec" },
    { en: "Building", pl: "Budynek" },
    { en: "Block of flats", pl: "Blok mieszkalny" },
    { en: "Traffic", pl: "Ruch uliczny" },
    { en: "Pedestrian", pl: "Pieszy" },
    { en: "Pedestrian street", pl: "Deptak" },
    { en: "Bike lane", pl: "Ścieżka rowerowa" },
    { en: "Litter bin", pl: "Kosz na śmieci" },
    { en: "Bench", pl: "Ławka" },
    { en: "Street light", pl: "Latarnia" },
    { en: "Noise", pl: "Hałas" },
    { en: "Crowded", pl: "Zatłoczony" },
    { en: "Busy street", pl: "Ruchliwa ulica" },
    { en: "Quiet area", pl: "Spokojna okolica" },
    { en: "I'm lost", pl: "Zgubiłem się" }
  ],
  casa: [
    { en: "Flat / Apartment", pl: "Mieszkanie" },
    { en: "Detached house", pl: "Dom wolnostojący" },
    { en: "Terraced house", pl: "Dom szeregowy" },
    { en: "Ground floor", pl: "Parter" },
    { en: "First floor", pl: "Pierwsze piętro (UK)" },
    { en: "Upstairs", pl: "Na górze" },
    { en: "Downstairs", pl: "Na dole" },
    { en: "Lift / Elevator", pl: "Winda" },
    { en: "Stairs", pl: "Schody" },
    { en: "Doorbell", pl: "Dzwonek do drzwi" },
    { en: "Landlord", pl: "Właściciel mieszkania" },
    { en: "Tenant", pl: "Najemca" },
    { en: "Flatmate / Roommate", pl: "Współlokator" },
    { en: "Living room", pl: "Salon" },
    { en: "Kitchen", pl: "Kuchnia" },
    { en: "Bedroom", pl: "Sypialnia" },
    { en: "Bathroom", pl: "Łazienka" },
    { en: "Dining room", pl: "Jadalnia" },
    { en: "Hall", pl: "Przedpokój" },
    { en: "Balcony", pl: "Balkon" },
    { en: "Garage", pl: "Garaż" },
    { en: "Storage room", pl: "Komórka lokatorska" },
    { en: "Wardrobe / Closet", pl: "Szafa" },
    { en: "Chest of drawers", pl: "Komoda" },
    { en: "Bookshelf", pl: "Regał na książki" },
    { en: "Sofa / Couch", pl: "Kanapa" },
    { en: "Armchair", pl: "Fotel" },
    { en: "Coffee table", pl: "Stolik kawowy" },
    { en: "Carpet", pl: "Dywan, wykładzina" },
    { en: "Curtains", pl: "Zasłony" },
    { en: "Blinds", pl: "Rolety, żaluzje" },
    { en: "Lamp", pl: "Lampa" },
    { en: "Pillow", pl: "Poduszka" },
    { en: "Sheets", pl: "Pościel" },
    { en: "Mattress", pl: "Materac" },
    { en: "Fridge", pl: "Lodówka" },
    { en: "Freezer", pl: "Zamrażarka" },
    { en: "Oven", pl: "Piekarnik" },
    { en: "Microwave", pl: "Mikrofalówka" },
    { en: "Dishwasher", pl: "Zmywarka" },
    { en: "Washing machine", pl: "Pralka" },
    { en: "Tumble dryer", pl: "Suszarka do ubrań" },
    { en: "Kettle", pl: "Czajnik elektryczny" },
    { en: "Toaster", pl: "Toster" },
    { en: "Frying pan", pl: "Patelnia" },
    { en: "Saucepan", pl: "Garnek, rondel" },
    { en: "Sink", pl: "Zlew, umywalka" },
    { en: "Tap / Faucet", pl: "Kran" },
    { en: "Shower", pl: "Prysznic" },
    { en: "Bathtub", pl: "Wanna" },
    { en: "Toilet", pl: "Toaleta" },
    { en: "Toilet paper", pl: "Papier toaletowy" },
    { en: "Towel rail", pl: "Wieszak na ręczniki" },
    { en: "Mirror", pl: "Lustro" },
    { en: "Plug", pl: "Wtyczka, korek" },
    { en: "Socket", pl: "Gniazdko" },
    { en: "Light switch", pl: "Włącznik światła" },
    { en: "Light bulb", pl: "Żarówka" },
    { en: "Fuse box", pl: "Skrzynka z bezpiecznikami" },
    { en: "Smoke alarm", pl: "Czujnik dymu" },
    { en: "To do the housework", pl: "Robić porządki w domu" },
    { en: "To make the bed", pl: "Ścielić łóżko" },
    { en: "To tidy up", pl: "Sprzątać, porządkować" },
    { en: "To clean", pl: "Czyścić" },
    { en: "To sweep", pl: "Zamiatać" },
    { en: "To mop the floor", pl: "Myć podłogę" },
    { en: "To vacuum", pl: "Odkurzać" },
    { en: "To dust", pl: "Ścierać kurze" },
    { en: "To do the laundry", pl: "Robić pranie" },
    { en: "To hang out the washing", pl: "Wieszać pranie" },
    { en: "To iron", pl: "Prasować" },
    { en: "To fold clothes", pl: "Składać ubrania" },
    { en: "To take out the rubbish", pl: "Wynosić śmieci" },
    { en: "Recycling bin", pl: "Pojemnik do segregacji" },
    { en: "To water the garden", pl: "Podlewać ogród" },
    { en: "To feed the cat", pl: "Nakarmić kota" },
    { en: "To walk the dog", pl: "Wyprowadzić psa" },
    { en: "To lock the door", pl: "Zamknąć drzwi na klucz" },
    { en: "I left my keys inside", pl: "Zostawiłem klucze w środku" },
    { en: "To move house", pl: "Przeprowadzić się" },
    { en: "To redecorate", pl: "Odnowić wystrój" },
    { en: "To fix", pl: "Naprawić" },
    { en: "It's broken", pl: "To jest zepsute" },
    { en: "It doesn't work", pl: "To nie działa" },
    { en: "Leak", pl: "Przeciek" },
    { en: "Plumber", pl: "Hydraulik" },
    { en: "Electrician", pl: "Elektryk" },
    { en: "Neighbour", pl: "Sąsiad" },
    { en: "Noisy neighbours", pl: "Głośni sąsiedzi" },
    { en: "Home sweet home", pl: "Nie ma jak w domu" },
    { en: "To feel at home", pl: "Czuć się jak w domu" },
    { en: "Household chores", pl: "Obowiązki domowe" },
    { en: "Spare room", pl: "Pokój gościnny" },
    { en: "Shelf", pl: "Półka" }
  ],
  salud: [
    { en: "I don't feel well", pl: "Źle się czuję" },
    { en: "I feel sick", pl: "Niedobrze mi" },
    { en: "I've got a headache", pl: "Boli mnie głowa" },
    { en: "I've got a stomach ache", pl: "Boli mnie brzuch" },
    { en: "I've got a toothache", pl: "Boli mnie ząb" },
    { en: "I've got a cold", pl: "Jestem przeziębiony" },
    { en: "I've got the flu", pl: "Mam grypę" },
    { en: "I've got a temperature", pl: "Mam gorączkę" },
    { en: "My back hurts", pl: "Bolą mnie plecy" },
    { en: "I feel dizzy", pl: "Kręci mi się w głowie" },
    { en: "I've cut my finger", pl: "Skaleczyłem się w palec" },
    { en: "I've sprained my ankle", pl: "Skręciłem kostkę" },
    { en: "I've broken my arm", pl: "Złamałem rękę" },
    { en: "I need to see a doctor", pl: "Muszę iść do lekarza" },
    { en: "Make an appointment", pl: "Umówić się na wizytę" },
    { en: "Waiting room", pl: "Poczekalnia" },
    { en: "Prescription", pl: "Recepta" },
    { en: "Medicine", pl: "Lek" },
    { en: "Painkiller", pl: "Środek przeciwbólowy" },
    { en: "Pill / Tablet", pl: "Tabletka" },
    { en: "Plaster / Band-Aid", pl: "Plaster" },
    { en: "Bandage", pl: "Bandaż" },
    { en: "Cream", pl: "Krem, maść" },
    { en: "Drops", pl: "Krople" },
    { en: "Injection", pl: "Zastrzyk" },
    { en: "Blood test", pl: "Badanie krwi" },
    { en: "X-ray", pl: "Prześwietlenie, RTG" },
    { en: "Check-up", pl: "Badanie kontrolne" },
    { en: "Emergency room / A&E", pl: "Szpitalny oddział ratunkowy (SOR)" },
    { en: "Ambulance", pl: "Karetka" },
    { en: "Nurse", pl: "Pielęgniarz / pielęgniarka" },
    { en: "Dentist", pl: "Dentysta" },
    { en: "GP / Family doctor", pl: "Lekarz rodzinny" },
    { en: "Health insurance", pl: "Ubezpieczenie zdrowotne" },
    { en: "Side effects", pl: "Skutki uboczne" },
    { en: "Allergy", pl: "Alergia" },
    { en: "Rash", pl: "Wysypka" },
    { en: "Itchy", pl: "Swędzący" },
    { en: "Swollen", pl: "Spuchnięty" },
    { en: "Bruise", pl: "Siniak" },
    { en: "Scar", pl: "Blizna" },
    { en: "Blister", pl: "Pęcherz" },
    { en: "Sore muscles", pl: "Zakwasy" },
    { en: "To recover", pl: "Wyzdrowieć" },
    { en: "To rest", pl: "Odpoczywać" },
    { en: "To take medicine", pl: "Brać leki" },
    { en: "Twice a day", pl: "Dwa razy dziennie" },
    { en: "On an empty stomach", pl: "Na czczo" },
    { en: "Healthy", pl: "Zdrowy" },
    { en: "Unhealthy", pl: "Niezdrowy" },
    { en: "Diet", pl: "Dieta, sposób odżywiania" },
    { en: "To work out", pl: "Ćwiczyć" },
    { en: "To keep fit", pl: "Utrzymywać formę" },
    { en: "To stretch", pl: "Rozciągać się" },
    { en: "To go for a run", pl: "Iść pobiegać" },
    { en: "Stress", pl: "Stres" },
    { en: "To sleep well", pl: "Dobrze spać" },
    { en: "Insomnia", pl: "Bezsenność" },
    { en: "Nightmare", pl: "Koszmar" },
    { en: "To be exhausted", pl: "Być wyczerpanym" },
    { en: "To be worn out", pl: "Być wykończonym" },
    { en: "Head", pl: "Głowa" },
    { en: "Neck", pl: "Szyja" },
    { en: "Shoulder", pl: "Ramię, bark" },
    { en: "Elbow", pl: "Łokieć" },
    { en: "Wrist", pl: "Nadgarstek" },
    { en: "Knee", pl: "Kolano" },
    { en: "Ankle", pl: "Kostka" },
    { en: "Heel", pl: "Pięta" },
    { en: "Toe", pl: "Palec u nogi" },
    { en: "Chest", pl: "Klatka piersiowa" },
    { en: "Stomach", pl: "Żołądek" },
    { en: "Lungs", pl: "Płuca" }
  ],
  estudios: [
    { en: "Classroom", pl: "Sala lekcyjna" },
    { en: "Classmate", pl: "Kolega z klasy" },
    { en: "Teacher", pl: "Nauczyciel" },
    { en: "Headteacher / Principal", pl: "Dyrektor szkoły" },
    { en: "Subject", pl: "Przedmiot" },
    { en: "Break / Recess", pl: "Przerwa" },
    { en: "Lesson", pl: "Lekcja" },
    { en: "Lecture", pl: "Wykład" },
    { en: "Seminar", pl: "Seminarium" },
    { en: "Assignment", pl: "Zadanie, praca" },
    { en: "Essay", pl: "Wypracowanie, esej" },
    { en: "Presentation", pl: "Prezentacja" },
    { en: "Group project", pl: "Projekt grupowy" },
    { en: "Notes", pl: "Notatki" },
    { en: "To take notes", pl: "Robić notatki" },
    { en: "Notebook", pl: "Zeszyt" },
    { en: "Textbook", pl: "Podręcznik" },
    { en: "Pencil case", pl: "Piórnik" },
    { en: "Rubber / Eraser", pl: "Gumka do mazania" },
    { en: "Sharpener", pl: "Temperówka" },
    { en: "Ruler", pl: "Linijka" },
    { en: "Highlighter", pl: "Zakreślacz" },
    { en: "Calculator", pl: "Kalkulator" },
    { en: "Exam", pl: "Egzamin" },
    { en: "Test", pl: "Sprawdzian" },
    { en: "Quiz", pl: "Kartkówka" },
    { en: "Mark / Grade", pl: "Ocena" },
    { en: "To pass an exam", pl: "Zdać egzamin" },
    { en: "To fail an exam", pl: "Oblać egzamin" },
    { en: "To retake an exam", pl: "Poprawiać egzamin" },
    { en: "To study for an exam", pl: "Uczyć się do egzaminu" },
    { en: "To learn by heart", pl: "Uczyć się na pamięć" },
    { en: "To cheat", pl: "Ściągać" },
    { en: "Pass mark", pl: "Ocena dopuszczająca" },
    { en: "Top marks", pl: "Najwyższe oceny" },
    { en: "Report", pl: "Świadectwo, raport" },
    { en: "Average", pl: "Średnia" },
    { en: "Deadline extension", pl: "Przedłużenie terminu" },
    { en: "To hand in", pl: "Oddać (pracę)" },
    { en: "Due date", pl: "Termin oddania" },
    { en: "Library card", pl: "Karta biblioteczna" },
    { en: "Dictionary", pl: "Słownik" },
    { en: "Degree", pl: "Studia, dyplom" },
    { en: "Bachelor's degree", pl: "Licencjat" },
    { en: "Master's degree", pl: "Studia magisterskie" },
    { en: "PhD", pl: "Doktorat" },
    { en: "Scholarship", pl: "Stypendium" },
    { en: "Tuition fees", pl: "Czesne" },
    { en: "Campus", pl: "Kampus" },
    { en: "Student residence", pl: "Akademik" },
    { en: "Undergraduate", pl: "Student studiów pierwszego stopnia" },
    { en: "Graduate", pl: "Absolwent" },
    { en: "To enrol", pl: "Zapisać się" },
    { en: "Course", pl: "Kurs, kierunek" },
    { en: "Term / Semester", pl: "Trymestr / Semestr" },
    { en: "Gap year", pl: "Rok przerwy" },
    { en: "Exchange student", pl: "Uczeń z wymiany" },
    { en: "Erasmus programme", pl: "Program Erasmus" },
    { en: "Homework is due tomorrow", pl: "Pracę domową trzeba oddać jutro" },
    { en: "Can I borrow your notes?", pl: "Pożyczysz mi notatki?" },
    { en: "I didn't understand the question", pl: "Nie zrozumiałem pytania" },
    { en: "Could you explain it again?", pl: "Może Pan to wytłumaczyć jeszcze raz?" },
    { en: "What page are we on?", pl: "Na której jesteśmy stronie?" },
    { en: "May I go to the toilet?", pl: "Czy mogę wyjść do toalety?" },
    { en: "I forgot my homework", pl: "Zapomniałem pracy domowej" },
    { en: "Study group", pl: "Grupa do nauki" },
    { en: "Extra credit", pl: "Dodatkowe punkty" },
    { en: "Maths", pl: "Matematyka" },
    { en: "Language", pl: "Język" },
    { en: "Literature", pl: "Literatura" },
    { en: "History", pl: "Historia" },
    { en: "Geography", pl: "Geografia" },
    { en: "Biology", pl: "Biologia" },
    { en: "Chemistry", pl: "Chemia" },
    { en: "Physics", pl: "Fizyka" },
    { en: "Philosophy", pl: "Filozofia" },
    { en: "Economics", pl: "Ekonomia" },
    { en: "Art", pl: "Plastyka" },
    { en: "Music", pl: "Muzyka" },
    { en: "PE (Physical Education)", pl: "Wychowanie fizyczne (WF)" },
    { en: "Computer science", pl: "Informatyka" },
    { en: "Bilingual", pl: "Dwujęzyczny" },
    { en: "Fluent", pl: "Płynnie" }
  ],
  trabajo: [
    { en: "Job", pl: "Praca" },
    { en: "Career", pl: "Kariera" },
    { en: "Office", pl: "Biuro" },
    { en: "Workplace", pl: "Miejsce pracy" },
    { en: "Colleague", pl: "Współpracownik" },
    { en: "Boss", pl: "Szef" },
    { en: "Manager", pl: "Kierownik" },
    { en: "Employee", pl: "Pracownik" },
    { en: "Employer", pl: "Pracodawca" },
    { en: "Intern", pl: "Stażysta" },
    { en: "Internship", pl: "Staż, praktyki" },
    { en: "Full-time", pl: "Na pełny etat" },
    { en: "Part-time", pl: "Na pół etatu" },
    { en: "Shift", pl: "Zmiana" },
    { en: "Overtime", pl: "Nadgodziny" },
    { en: "Working hours", pl: "Godziny pracy" },
    { en: "Day off work", pl: "Dzień wolny" },
    { en: "Holiday / Vacation", pl: "Urlop" },
    { en: "Sick leave", pl: "Zwolnienie lekarskie" },
    { en: "Maternity leave", pl: "Urlop macierzyński" },
    { en: "To apply for a job", pl: "Ubiegać się o pracę" },
    { en: "CV / Résumé", pl: "CV" },
    { en: "Cover letter", pl: "List motywacyjny" },
    { en: "Job interview", pl: "Rozmowa kwalifikacyjna" },
    { en: "To hire", pl: "Zatrudnić" },
    { en: "To fire", pl: "Zwolnić" },
    { en: "To resign", pl: "Złożyć wypowiedzenie" },
    { en: "To be promoted", pl: "Dostać awans" },
    { en: "Pay rise / Raise", pl: "Podwyżka" },
    { en: "Contract", pl: "Umowa" },
    { en: "Trial period", pl: "Okres próbny" },
    { en: "Meeting", pl: "Spotkanie, zebranie" },
    { en: "Agenda", pl: "Porządek obrad" },
    { en: "Minutes (of a meeting)", pl: "Protokół" },
    { en: "Task", pl: "Zadanie" },
    { en: "Project", pl: "Projekt" },
    { en: "Team", pl: "Zespół" },
    { en: "Teamwork", pl: "Praca zespołowa" },
    { en: "Goal", pl: "Cel" },
    { en: "Feedback", pl: "Informacja zwrotna" },
    { en: "Spreadsheet", pl: "Arkusz kalkulacyjny" },
    { en: "Email", pl: "E-mail" },
    { en: "To reply", pl: "Odpowiedzieć" },
    { en: "To forward", pl: "Przekazać dalej" },
    { en: "Attachment", pl: "Załącznik" },
    { en: "Let's schedule a meeting", pl: "Umówmy się na spotkanie" },
    { en: "I'll get back to you", pl: "Odezwę się później" },
    { en: "Could you send me the file?", pl: "Możesz mi wysłać plik?" },
    { en: "Thanks for your help", pl: "Dzięki za pomoc" },
    { en: "I'm working from home today", pl: "Dziś pracuję z domu" },
    { en: "Remote work", pl: "Praca zdalna" },
    { en: "Commute", pl: "Dojazd do pracy" },
    { en: "Business trip", pl: "Podróż służbowa" },
    { en: "Client", pl: "Klient" },
    { en: "Customer service", pl: "Obsługa klienta" },
    { en: "Supplier", pl: "Dostawca" },
    { en: "Sales", pl: "Sprzedaż" },
    { en: "Marketing", pl: "Marketing" },
    { en: "Accounting", pl: "Księgowość" },
    { en: "Human resources", pl: "Dział kadr (HR)" },
    { en: "Headquarters", pl: "Siedziba główna" },
    { en: "Branch", pl: "Oddział" },
    { en: "Company", pl: "Firma" },
    { en: "Start-up", pl: "Start-up" },
    { en: "Self-employed", pl: "Samozatrudniony" },
    { en: "Unemployed", pl: "Bezrobotny" },
    { en: "Retired", pl: "Emeryt" },
    { en: "Workload", pl: "Obciążenie pracą" },
    { en: "Burnout", pl: "Wypalenie zawodowe" },
    { en: "To multitask", pl: "Robić kilka rzeczy naraz" },
    { en: "To be in charge of", pl: "Odpowiadać za" },
    { en: "To meet a deadline", pl: "Zmieścić się w terminie" },
    { en: "To call it a day", pl: "Skończyć na dziś" },
    { en: "Busy", pl: "Zajęty" }
  ],
  tecnologia: [
    { en: "Mobile phone / Cell phone", pl: "Telefon komórkowy" },
    { en: "Smartphone", pl: "Smartfon" },
    { en: "Charger", pl: "Ładowarka" },
    { en: "My battery is dead", pl: "Rozładował mi się telefon" },
    { en: "My phone is about to die", pl: "Zaraz padnie mi bateria" },
    { en: "Can I charge my phone here?", pl: "Mogę tu naładować telefon?" },
    { en: "No signal", pl: "Brak zasięgu" },
    { en: "Wi-Fi", pl: "Wi-Fi" },
    { en: "Password", pl: "Hasło" },
    { en: "Username", pl: "Nazwa użytkownika" },
    { en: "To log in", pl: "Zalogować się" },
    { en: "To log out", pl: "Wylogować się" },
    { en: "To sign up", pl: "Zarejestrować się" },
    { en: "Account", pl: "Konto" },
    { en: "To download", pl: "Pobrać" },
    { en: "To upload", pl: "Wrzucić, przesłać" },
    { en: "To update", pl: "Zaktualizować" },
    { en: "App", pl: "Aplikacja" },
    { en: "Notification", pl: "Powiadomienie" },
    { en: "Screen", pl: "Ekran" },
    { en: "Screenshot", pl: "Zrzut ekranu" },
    { en: "Keyboard", pl: "Klawiatura" },
    { en: "Mouse", pl: "Myszka" },
    { en: "Laptop", pl: "Laptop" },
    { en: "Tablet", pl: "Tablet" },
    { en: "Headphones", pl: "Słuchawki" },
    { en: "Earbuds", pl: "Słuchawki douszne" },
    { en: "Speaker", pl: "Głośnik" },
    { en: "Printer", pl: "Drukarka" },
    { en: "To print", pl: "Drukować" },
    { en: "To scan", pl: "Skanować" },
    { en: "File", pl: "Plik" },
    { en: "Folder", pl: "Folder" },
    { en: "To save", pl: "Zapisać" },
    { en: "To delete", pl: "Usunąć" },
    { en: "To copy and paste", pl: "Kopiuj i wklej" },
    { en: "To restart", pl: "Uruchomić ponownie" },
    { en: "It's frozen", pl: "Zawiesił się" },
    { en: "Link", pl: "Link" },
    { en: "Website", pl: "Strona internetowa" },
    { en: "Search engine", pl: "Wyszukiwarka" },
    { en: "To google something", pl: "Wygooglować coś" },
    { en: "Social media", pl: "Media społecznościowe" },
    { en: "Post", pl: "Post" },
    { en: "To post", pl: "Opublikować" },
    { en: "To share", pl: "Udostępnić" },
    { en: "To like", pl: "Polubić" },
    { en: "To follow", pl: "Obserwować" },
    { en: "Followers", pl: "Obserwujący" },
    { en: "Hashtag", pl: "Hasztag" },
    { en: "Profile picture", pl: "Zdjęcie profilowe" },
    { en: "Story", pl: "Relacja" },
    { en: "Direct message", pl: "Wiadomość prywatna" },
    { en: "To text", pl: "Napisać wiadomość" },
    { en: "Voice message", pl: "Wiadomość głosowa" },
    { en: "Video call", pl: "Rozmowa wideo" },
    { en: "Group chat", pl: "Czat grupowy" },
    { en: "To mute", pl: "Wyciszyć" },
    { en: "To block", pl: "Zablokować" },
    { en: "Emoji", pl: "Emoji" },
    { en: "Selfie", pl: "Selfie" },
    { en: "Streaming", pl: "Streaming" },
    { en: "Subscription", pl: "Subskrypcja" },
    { en: "Podcast", pl: "Podcast" },
    { en: "Online", pl: "Online" },
    { en: "Offline", pl: "Offline" },
    { en: "Cloud storage", pl: "Chmura (miejsce na dane)" },
    { en: "Data plan", pl: "Pakiet danych" },
    { en: "To go viral", pl: "Stać się viralem" },
    { en: "Fake news", pl: "Fake newsy" }
  ],
  emociones: [
    { en: "Happy", pl: "Szczęśliwy" },
    { en: "Sad", pl: "Smutny" },
    { en: "Angry", pl: "Zły" },
    { en: "Upset", pl: "Zdenerwowany, przybity" },
    { en: "Annoyed", pl: "Poirytowany" },
    { en: "Furious", pl: "Wściekły" },
    { en: "Scared", pl: "Przestraszony" },
    { en: "Worried", pl: "Zmartwiony" },
    { en: "Nervous", pl: "Zdenerwowany (przed czymś)" },
    { en: "Anxious", pl: "Niespokojny" },
    { en: "Excited", pl: "Podekscytowany" },
    { en: "Bored", pl: "Znudzony" },
    { en: "Boring", pl: "Nudny" },
    { en: "Tired", pl: "Zmęczony" },
    { en: "Relaxed", pl: "Zrelaksowany" },
    { en: "Calm", pl: "Spokojny" },
    { en: "Proud", pl: "Dumny" },
    { en: "Ashamed", pl: "Zawstydzony (czymś złym)" },
    { en: "Embarrassed", pl: "Zażenowany" },
    { en: "Jealous", pl: "Zazdrosny (o kogoś)" },
    { en: "Envious", pl: "Zawistny" },
    { en: "Lonely", pl: "Samotny" },
    { en: "Homesick", pl: "Tęskniący za domem" },
    { en: "Confused", pl: "Zdezorientowany" },
    { en: "Surprised", pl: "Zaskoczony" },
    { en: "Shocked", pl: "W szoku" },
    { en: "Disappointed", pl: "Rozczarowany" },
    { en: "Grateful", pl: "Wdzięczny" },
    { en: "Hopeful", pl: "Pełen nadziei" },
    { en: "Confident", pl: "Pewny siebie" },
    { en: "Shy", pl: "Nieśmiały" },
    { en: "Outgoing", pl: "Towarzyski" },
    { en: "Friendly", pl: "Przyjazny" },
    { en: "Kind", pl: "Miły" },
    { en: "Funny", pl: "Zabawny" },
    { en: "Clever", pl: "Bystry" },
    { en: "Hard-working", pl: "Pracowity" },
    { en: "Lazy", pl: "Leniwy" },
    { en: "Patient", pl: "Cierpliwy" },
    { en: "Impatient", pl: "Niecierpliwy" },
    { en: "Generous", pl: "Hojny" },
    { en: "Selfish", pl: "Samolubny" },
    { en: "Honest", pl: "Szczery" },
    { en: "Polite", pl: "Uprzejmy" },
    { en: "Rude", pl: "Niegrzeczny" },
    { en: "Stubborn", pl: "Uparty" },
    { en: "Bossy", pl: "Apodyktyczny" },
    { en: "Moody", pl: "Humorzasty" },
    { en: "Easy-going", pl: "Wyluzowany" },
    { en: "Reliable", pl: "Godny zaufania" },
    { en: "Brave", pl: "Odważny" },
    { en: "Cheerful", pl: "Radosny" },
    { en: "Grumpy", pl: "Zrzęda" },
    { en: "Sensitive", pl: "Wrażliwy" },
    { en: "Sensible", pl: "Rozsądny" },
    { en: "Mature", pl: "Dojrzały" },
    { en: "Childish", pl: "Dziecinny" },
    { en: "Thoughtful", pl: "Troskliwy, taktowny" },
    { en: "Caring", pl: "Opiekuńczy" },
    { en: "Down-to-earth", pl: "Twardo stąpający po ziemi" },
    { en: "Open-minded", pl: "Otwarty na nowe" },
    { en: "Narrow-minded", pl: "Ograniczony" },
    { en: "I'm in a good mood", pl: "Mam dobry humor" },
    { en: "I'm in a bad mood", pl: "Mam zły humor" },
    { en: "I'm fed up", pl: "Mam dość" },
    { en: "I'm stressed out", pl: "Jestem zestresowany" },
    { en: "I'm over the moon", pl: "Jestem w siódmym niebie" },
    { en: "I'm on cloud nine", pl: "Jestem w siódmym niebie" },
    { en: "I'm feeling down", pl: "Mam doła" },
    { en: "I'm freaking out", pl: "Panikuję" },
    { en: "It drives me crazy", pl: "To doprowadza mnie do szału" },
    { en: "It gets on my nerves", pl: "To mnie denerwuje" },
    { en: "I can't stand it", pl: "Nie znoszę tego" },
    { en: "I'm looking forward to it", pl: "Nie mogę się doczekać" },
    { en: "I miss you", pl: "Tęsknię za Tobą" },
    { en: "I love you", pl: "Kocham Cię" },
    { en: "I'm proud of you", pl: "Jestem z Ciebie dumny" },
    { en: "Don't worry about it", pl: "Nie martw się tym" },
    { en: "Calm down", pl: "Uspokój się" },
    { en: "Take it easy", pl: "Spokojnie" },
    { en: "Chill out", pl: "Wyluzuj" },
    { en: "Hang in there", pl: "Trzymaj się" },
    { en: "You've got this", pl: "Dasz radę" },
    { en: "It's going to be fine", pl: "Wszystko będzie dobrze" },
    { en: "I'm here for you", pl: "Jestem przy Tobie" },
    { en: "Keep your chin up", pl: "Głowa do góry" },
    { en: "Mixed feelings", pl: "Mieszane uczucia" },
    { en: "To lose your temper", pl: "Stracić panowanie nad sobą" }
  ],
  phrasal: [
    { en: "To wake up", pl: "Obudzić się" },
    { en: "To get up", pl: "Wstać" },
    { en: "To get dressed", pl: "Ubrać się" },
    { en: "To put on", pl: "Założyć (ubranie)" },
    { en: "To take off", pl: "Zdjąć (ubranie); wystartować" },
    { en: "To turn on", pl: "Włączyć" },
    { en: "To turn off", pl: "Wyłączyć" },
    { en: "To turn up", pl: "Pogłośnić; pojawić się" },
    { en: "To turn down", pl: "Ściszyć; odrzucić" },
    { en: "To look for", pl: "Szukać" },
    { en: "To look after", pl: "Opiekować się" },
    { en: "To look up", pl: "Sprawdzić (informację)" },
    { en: "To look forward to", pl: "Nie móc się doczekać" },
    { en: "To look out", pl: "Uważać" },
    { en: "To find out", pl: "Dowiedzieć się" },
    { en: "To figure out", pl: "Rozgryźć, zrozumieć" },
    { en: "To give up", pl: "Poddać się, rzucić" },
    { en: "To give back", pl: "Oddać" },
    { en: "To give away", pl: "Rozdać; zdradzić" },
    { en: "To go on", pl: "Kontynuować" },
    { en: "To go out", pl: "Wyjść" },
    { en: "To go back", pl: "Wrócić" },
    { en: "To go over", pl: "Przejrzeć, powtórzyć" },
    { en: "To come back", pl: "Wrócić" },
    { en: "To come in", pl: "Wejść" },
    { en: "To come across", pl: "Natknąć się na" },
    { en: "To come up with", pl: "Wpaść na (pomysł)" },
    { en: "To carry on", pl: "Kontynuować" },
    { en: "To check in", pl: "Zameldować się" },
    { en: "To check out", pl: "Wymeldować się; zerknąć" },
    { en: "To fill in", pl: "Wypełnić" },
    { en: "To fill out", pl: "Wypełnić (formularz)" },
    { en: "To get along with", pl: "Dogadywać się z" },
    { en: "To get over", pl: "Przeboleć, wyleczyć się z" },
    { en: "To get back", pl: "Wrócić, odzyskać" },
    { en: "To get in", pl: "Wsiąść (do auta)" },
    { en: "To get out", pl: "Wysiąść (z auta)" },
    { en: "To get rid of", pl: "Pozbyć się" },
    { en: "To get by", pl: "Radzić sobie, wiązać koniec z końcem" },
    { en: "To grow up", pl: "Dorastać" },
    { en: "To hang up", pl: "Rozłączyć się" },
    { en: "To hang on", pl: "Poczekać" },
    { en: "To hold on", pl: "Poczekać, trzymać się" },
    { en: "To keep on", pl: "Robić dalej" },
    { en: "To keep up with", pl: "Nadążać za" },
    { en: "To let down", pl: "Zawieść" },
    { en: "To make up", pl: "Wymyślić; pogodzić się" },
    { en: "To make up your mind", pl: "Zdecydować się" },
    { en: "To pick up", pl: "Odebrać, podnieść" },
    { en: "To put off", pl: "Odłożyć na później" },
    { en: "To put up with", pl: "Znosić" },
    { en: "To put away", pl: "Odłożyć na miejsce" },
    { en: "To run out of", pl: "Skończyć się (komuś coś)" },
    { en: "To run into", pl: "Wpaść na kogoś (przypadkiem)" },
    { en: "To set up", pl: "Założyć, skonfigurować" },
    { en: "To show off", pl: "Popisywać się" },
    { en: "To sit down", pl: "Usiąść" },
    { en: "To stand up", pl: "Wstać" },
    { en: "To take after", pl: "Być podobnym do (kogoś z rodziny)" },
    { en: "To take up", pl: "Zacząć (hobby)" },
    { en: "To take over", pl: "Przejąć" },
    { en: "To throw away", pl: "Wyrzucić" },
    { en: "To try on", pl: "Przymierzyć" },
    { en: "To bring up", pl: "Poruszyć (temat); wychować" },
    { en: "To call off", pl: "Odwołać" },
    { en: "To call back", pl: "Oddzwonić" },
    { en: "To catch up", pl: "Nadrobić zaległości" },
    { en: "To cheer up", pl: "Pocieszyć, poprawić humor" },
    { en: "To count on", pl: "Liczyć na" },
    { en: "To cut down on", pl: "Ograniczyć" },
    { en: "To drop by", pl: "Wpaść (do kogoś)" },
    { en: "To drop off", pl: "Podrzucić (kogoś); przysnąć" },
    { en: "To eat out", pl: "Jeść na mieście" },
    { en: "To end up", pl: "Skończyć (na czymś)" },
    { en: "To fall asleep", pl: "Zasnąć" },
    { en: "To fall out with", pl: "Pokłócić się z" },
    { en: "To get on with", pl: "Kontynuować; dogadywać się" },
    { en: "To hand out", pl: "Rozdawać" },
    { en: "To head off", pl: "Wyruszyć" },
    { en: "To kick off", pl: "Zacząć" },
    { en: "To leave out", pl: "Pominąć" },
    { en: "To log on", pl: "Zalogować się" },
    { en: "To mess up", pl: "Zepsuć, nawalić" },
    { en: "To mix up", pl: "Pomylić" },
    { en: "To move in", pl: "Wprowadzić się" },
    { en: "To move out", pl: "Wyprowadzić się" },
    { en: "To pass out", pl: "Zemdleć" },
    { en: "To pay back", pl: "Oddać (pieniądze)" },
    { en: "To point out", pl: "Zwrócić uwagę na" },
    { en: "To sign in", pl: "Zalogować się, wpisać się" },
    { en: "To sort out", pl: "Załatwić, uporządkować" },
    { en: "To speak up", pl: "Mówić głośniej" },
    { en: "To split up", pl: "Rozstać się" },
    { en: "To stay up", pl: "Nie kłaść się spać" },
    { en: "To switch off", pl: "Wyłączyć się, odciąć" },
    { en: "To think over", pl: "Przemyśleć" },
    { en: "To wear out", pl: "Zużyć; wykończyć" },
    { en: "To write down", pl: "Zapisać" },
    { en: "To zone out", pl: "Odpłynąć myślami" },
    { en: "To freak out", pl: "Spanikować" },
    { en: "To sleep in", pl: "Wyspać się, spać długo" },
    { en: "To slow down", pl: "Zwolnić" },
    { en: "To speed up", pl: "Przyspieszyć" },
    { en: "To warm up", pl: "Rozgrzać się" },
    { en: "To cool down", pl: "Ostygnąć, uspokoić się" },
    { en: "To back up", pl: "Wspierać; zrobić kopię zapasową" },
    { en: "To blow up", pl: "Wybuchnąć" }
  ],
  modismos: [
    { en: "Piece of cake", pl: "Bułka z masłem" },
    { en: "It's raining cats and dogs", pl: "Leje jak z cebra" },
    { en: "Break a leg!", pl: "Połamania nóg!" },
    { en: "To hit the nail on the head", pl: "Trafić w sedno" },
    { en: "To kill two birds with one stone", pl: "Upiec dwie pieczenie na jednym ogniu" },
    { en: "Once in a blue moon", pl: "Raz na ruski rok" },
    { en: "To cost a fortune", pl: "Kosztować fortunę" },
    { en: "To spill the beans", pl: "Wygadać się" },
    { en: "To let the cat out of the bag", pl: "Wypaplać sekret" },
    { en: "To pull someone's leg", pl: "Nabijać się z kogoś" },
    { en: "To call it a night", pl: "Skończyć na dziś wieczór" },
    { en: "To get cold feet", pl: "Stchórzyć w ostatniej chwili" },
    { en: "To have a lot on your plate", pl: "Mieć dużo na głowie" },
    { en: "To be in hot water", pl: "Mieć kłopoty" },
    { en: "To be in the same boat", pl: "Jechać na tym samym wózku" },
    { en: "To miss the boat", pl: "Przegapić okazję" },
    { en: "To cut corners", pl: "Iść na skróty, fuszerować" },
    { en: "To go the extra mile", pl: "Dać z siebie więcej" },
    { en: "To bite off more than you can chew", pl: "Porywać się z motyką na słońce" },
    { en: "To cry over spilt milk", pl: "Płakać nad rozlanym mlekiem" },
    { en: "To beat around the bush", pl: "Owijać w bawełnę" },
    { en: "To get to the point", pl: "Przejść do rzeczy" },
    { en: "To play it by ear", pl: "Improwizować" },
    { en: "To keep an eye on", pl: "Mieć oko na" },
    { en: "To see eye to eye", pl: "Być zgodnym" },
    { en: "To give someone a hand", pl: "Pomóc komuś" },
    { en: "To give someone the cold shoulder", pl: "Traktować kogoś ozięble" },
    { en: "To have second thoughts", pl: "Mieć wątpliwości" },
    { en: "To sleep on it", pl: "Prześpić się z tym" },
    { en: "To be on the fence", pl: "Nie móc się zdecydować" },
    { en: "To be up in the air", pl: "Wisieć w powietrzu" },
    { en: "To be a pain in the neck", pl: "Być utrapieniem" },
    { en: "To be all ears", pl: "Zamieniać się w słuch" },
    { en: "To keep your fingers crossed", pl: "Trzymać kciuki" },
    { en: "To be on thin ice", pl: "Stąpać po cienkim lodzie" },
    { en: "To burn the midnight oil", pl: "Zarywać noce nad nauką" },
    { en: "To hit the sack", pl: "Iść spać" },
    { en: "To hit the road", pl: "Ruszać w drogę" },
    { en: "To call the shots", pl: "Rządzić, decydować" },
    { en: "To be the last straw", pl: "Być kroplą, która przelała czarę" },
    { en: "To make ends meet", pl: "Wiązać koniec z końcem" },
    { en: "To save for a rainy day", pl: "Odkładać na czarną godzinę" },
    { en: "To ring a bell", pl: "Brzmieć znajomo" },
    { en: "To be on the same page", pl: "Nadawać na tych samych falach" },
    { en: "To think outside the box", pl: "Myśleć nieszablonowo" },
    { en: "Better late than never", pl: "Lepiej późno niż wcale" },
    { en: "Actions speak louder than words", pl: "Czyny mówią więcej niż słowa" },
    { en: "Don't judge a book by its cover", pl: "Nie oceniaj książki po okładce" },
    { en: "The early bird catches the worm", pl: "Kto rano wstaje, temu Pan Bóg daje" },
    { en: "Where there's a will, there's a way", pl: "Dla chcącego nic trudnego" },
    { en: "Easy come, easy go", pl: "Łatwo przyszło, łatwo poszło" },
    { en: "No pain, no gain", pl: "Bez pracy nie ma kołaczy" },
    { en: "Time flies", pl: "Czas leci" },
    { en: "Time is money", pl: "Czas to pieniądz" },
    { en: "Two heads are better than one", pl: "Co dwie głowy, to nie jedna" },
    { en: "When in Rome, do as the Romans do", pl: "Kiedy wejdziesz między wrony, musisz krakać jak i one" },
    { en: "Birds of a feather flock together", pl: "Ciągnie swój do swego" },
    { en: "Out of sight, out of mind", pl: "Co z oczu, to z serca" },
    { en: "It's not rocket science", pl: "To nie fizyka kwantowa" },
    { en: "It's a small world", pl: "Jaki ten świat mały" },
    { en: "Speak of the devil", pl: "O wilku mowa" },
    { en: "The ball is in your court", pl: "Piłka po Twojej stronie" },
    { en: "Get your act together", pl: "Weź się w garść" },
    { en: "Not my cup of tea", pl: "To nie moja bajka" },
    { en: "Over my dead body", pl: "Po moim trupie" },
    { en: "Rome wasn't built in a day", pl: "Nie od razu Kraków zbudowano" },
    { en: "You can't have it both ways", pl: "Nie można mieć ciastka i zjeść ciastka" },
    { en: "Let sleeping dogs lie", pl: "Nie wywołuj wilka z lasu" },
    { en: "Curiosity killed the cat", pl: "Ciekawość to pierwszy stopień do piekła" },
    { en: "A blessing in disguise", pl: "Szczęście w nieszczęściu" },
    { en: "Out of the blue", pl: "Nagle, jak grom z jasnego nieba" },
    { en: "On the tip of my tongue", pl: "Na końcu języka" },
    { en: "In a nutshell", pl: "W skrócie" },
    { en: "By the skin of your teeth", pl: "O włos" },
    { en: "Cut it out!", pl: "Przestań!" },
    { en: "Keep it up!", pl: "Tak trzymaj!" },
    { en: "Hang loose", pl: "Spoko, luz" },
    { en: "My lips are sealed", pl: "Będę milczeć jak grób" },
    { en: "It's a deal", pl: "Umowa stoi" },
    { en: "Let's call it even", pl: "Jesteśmy kwita" },
    { en: "No hard feelings", pl: "Bez urazy" },
    { en: "Better safe than sorry", pl: "Lepiej dmuchać na zimne" },
    { en: "To be a couch potato", pl: "Być kanapowcem" },
    { en: "To be a night owl", pl: "Być nocnym markiem" },
    { en: "To be an early bird", pl: "Być rannym ptaszkiem" },
    { en: "To have a sweet tooth", pl: "Mieć słabość do słodyczy" },
    { en: "To be full of beans", pl: "Tryskać energią" },
    { en: "To go Dutch", pl: "Płacić każdy za siebie" },
    { en: "To feel like a fish out of water", pl: "Czuć się jak ryba wyjęta z wody" },
    { en: "To learn the ropes", pl: "Poznać tajniki" },
    { en: "To know something inside out", pl: "Znać coś jak własną kieszeń" },
    { en: "To be on top of the world", pl: "Być na szczycie świata" },
    { en: "To be down in the dumps", pl: "Mieć chandrę" },
    { en: "To lose track of time", pl: "Stracić poczucie czasu" },
    { en: "To kill time", pl: "Zabijać czas" },
    { en: "To take a rain check", pl: "Przełożyć na inny raz" },
    { en: "To face the music", pl: "Ponieść konsekwencje" },
    { en: "To have a blast", pl: "Świetnie się bawić" }
  ],
  tiempo_planes: [
    { en: "Today", pl: "Dziś" },
    { en: "Tomorrow", pl: "Jutro" },
    { en: "Yesterday", pl: "Wczoraj" },
    { en: "The day after tomorrow", pl: "Pojutrze" },
    { en: "The day before yesterday", pl: "Przedwczoraj" },
    { en: "Tonight", pl: "Dziś wieczorem" },
    { en: "Last night", pl: "Wczoraj wieczorem" },
    { en: "This morning", pl: "Dziś rano" },
    { en: "This afternoon", pl: "Dziś po południu" },
    { en: "This weekend", pl: "W ten weekend" },
    { en: "Next week", pl: "W przyszłym tygodniu" },
    { en: "Last week", pl: "W zeszłym tygodniu" },
    { en: "In two weeks", pl: "Za dwa tygodnie" },
    { en: "A fortnight", pl: "Dwa tygodnie" },
    { en: "Every other day", pl: "Co drugi dzień" },
    { en: "Once a week", pl: "Raz w tygodniu" },
    { en: "Weekdays", pl: "Dni powszednie" },
    { en: "Weekend", pl: "Weekend" },
    { en: "Early", pl: "Wcześnie" },
    { en: "Late", pl: "Późno" },
    { en: "Later on", pl: "Później" },
    { en: "Soon", pl: "Wkrótce" },
    { en: "Recently", pl: "Niedawno" },
    { en: "Nowadays", pl: "Obecnie" },
    { en: "Lately", pl: "Ostatnio" },
    { en: "Ages ago", pl: "Wieki temu" },
    { en: "In a while", pl: "Za chwilę" },
    { en: "Right now", pl: "Właśnie teraz" },
    { en: "Right away", pl: "Od razu" },
    { en: "At the moment", pl: "W tej chwili" },
    { en: "In advance", pl: "Z wyprzedzeniem" },
    { en: "At the last minute", pl: "W ostatniej chwili" },
    { en: "Around noon", pl: "Około południa" },
    { en: "Midnight", pl: "Północ" },
    { en: "Dawn", pl: "Świt" },
    { en: "Half past six", pl: "Wpół do siódmej" },
    { en: "Quarter to nine", pl: "Za kwadrans dziewiąta" },
    { en: "Quarter past ten", pl: "Kwadrans po dziesiątej" },
    { en: "What time is it?", pl: "Która godzina?" },
    { en: "What's the date today?", pl: "Którego dziś mamy?" },
    { en: "What day is it today?", pl: "Jaki dziś dzień?" },
    { en: "Do you have any plans?", pl: "Masz jakieś plany?" },
    { en: "What are you doing this weekend?", pl: "Co robisz w ten weekend?" },
    { en: "Let's meet at eight", pl: "Spotkajmy się o ósmej" },
    { en: "Let's make it another day", pl: "Przełóżmy to na inny dzień" },
    { en: "Can we reschedule?", pl: "Możemy zmienić termin?" },
    { en: "I'm busy that day", pl: "Tego dnia jestem zajęty" },
    { en: "I'm free on Friday", pl: "W piątek mam czas" },
    { en: "Whenever you want", pl: "Kiedy chcesz" },
    { en: "Wherever you want", pl: "Gdzie chcesz" },
    { en: "Plan B", pl: "Plan B" },
    { en: "Calendar", pl: "Kalendarz" },
    { en: "Appointment", pl: "Wizyta, termin (u lekarza, w urzędzie)" },
    { en: "Date (romantic)", pl: "Randka" },
    { en: "Reminder", pl: "Przypomnienie" },
    { en: "Schedule", pl: "Grafik, plan dnia" },
    { en: "To set an alarm", pl: "Nastawić budzik" },
    { en: "To oversleep", pl: "Zaspać" }
  ],
  muletillas: [
    { en: "Like…", pl: "Jakby…, w sensie…" },
    { en: "You know…", pl: "Wiesz…" },
    { en: "I mean…", pl: "To znaczy…" },
    { en: "Well…", pl: "No cóż…" },
    { en: "So…", pl: "No to…, więc…" },
    { en: "Right?", pl: "Prawda?" },
    { en: "Isn't it?", pl: "Nie?" },
    { en: "Okay then", pl: "No dobra" },
    { en: "All right", pl: "W porządku" },
    { en: "Cool", pl: "Fajnie" },
    { en: "Awesome", pl: "Super" },
    { en: "Great", pl: "Świetnie" },
    { en: "Fine", pl: "Dobrze" },
    { en: "Nice one!", pl: "Nieźle!" },
    { en: "Oh my God!", pl: "O mój Boże!" },
    { en: "Oops!", pl: "Ups!" },
    { en: "Ouch!", pl: "Au!" },
    { en: "Yuck!", pl: "Fuj!" },
    { en: "Yummy!", pl: "Mniam!" },
    { en: "Wow!", pl: "Wow!" },
    { en: "Phew!", pl: "Uff!" },
    { en: "Hmm…", pl: "Hmm…" },
    { en: "Come on!", pl: "Dawaj! / No weź!" },
    { en: "Let's go!", pl: "Chodźmy!" },
    { en: "Hurry up!", pl: "Pospiesz się!" },
    { en: "Watch out!", pl: "Uważaj!" },
    { en: "Be careful", pl: "Bądź ostrożny" },
    { en: "Shh!", pl: "Ćśś!" },
    { en: "Gotcha!", pl: "Mam cię! / Jasne" },
    { en: "Kidding!", pl: "Żartuję!" },
    { en: "Just kidding", pl: "Tylko żartowałem" },
    { en: "Seriously?", pl: "Serio?" },
    { en: "For real?", pl: "Naprawdę?" },
    { en: "No kidding", pl: "Bez jaj / Nie gadaj" },
    { en: "Totally", pl: "Totalnie" },
    { en: "Definitely", pl: "Zdecydowanie" },
    { en: "Probably", pl: "Prawdopodobnie" },
    { en: "Maybe", pl: "Może" },
    { en: "Perhaps", pl: "Być może" },
    { en: "Literally", pl: "Dosłownie" },
    { en: "Honestly", pl: "Szczerze" },
    { en: "Anyhow", pl: "Tak czy inaczej" },
    { en: "Otherwise", pl: "W przeciwnym razie" },
    { en: "Same here", pl: "Ja też" },
    { en: "Me neither", pl: "Ja też nie" },
    { en: "Me too", pl: "Ja też" },
    { en: "So do I", pl: "Ja też (twierdząco)" },
    { en: "Neither do I", pl: "Ja też nie (przecząco)" },
    { en: "Fair point", pl: "Słusznie (potocznie)" },
    { en: "Fair play", pl: "Szacun, czapki z głów" },
    { en: "Mate", pl: "Stary, kolego (UK)" },
    { en: "Dude", pl: "Ziomek, stary (US)" },
    { en: "Folks", pl: "Ludzie, rodzina" },
    { en: "Guys", pl: "Ludzie, ekipa" },
    { en: "Y'all", pl: "Wy (południe USA)" },
    { en: "Gonna", pl: "Zamierzam (going to)" },
    { en: "Wanna", pl: "Chcę (want to)" }
  ],
  ropa_aspecto: [
    { en: "Clothes", pl: "Ubrania" },
    { en: "Outfit", pl: "Strój, stylizacja" },
    { en: "T-shirt", pl: "Koszulka" },
    { en: "Shirt", pl: "Koszula" },
    { en: "Blouse", pl: "Bluzka" },
    { en: "Jeans", pl: "Dżinsy" },
    { en: "Trousers / Pants", pl: "Spodnie" },
    { en: "Shorts", pl: "Szorty" },
    { en: "Skirt", pl: "Spódnica" },
    { en: "Dress", pl: "Sukienka" },
    { en: "Suit", pl: "Garnitur" },
    { en: "Tie", pl: "Krawat" },
    { en: "Jacket", pl: "Kurtka, marynarka" },
    { en: "Hoodie", pl: "Bluza z kapturem" },
    { en: "Sweatshirt", pl: "Bluza" },
    { en: "Tracksuit", pl: "Dres" },
    { en: "Leggings", pl: "Legginsy" },
    { en: "Socks", pl: "Skarpetki" },
    { en: "Underwear", pl: "Bielizna" },
    { en: "Pyjamas (clothes)", pl: "Piżama" },
    { en: "Shoes", pl: "Buty" },
    { en: "Boots", pl: "Kozaki" },
    { en: "Heels", pl: "Szpilki" },
    { en: "Belt", pl: "Pasek" },
    { en: "Hat", pl: "Kapelusz" },
    { en: "Cap (clothing)", pl: "Czapka z daszkiem" },
    { en: "Bag", pl: "Torebka, torba" },
    { en: "Watch", pl: "Zegarek" },
    { en: "Necklace", pl: "Naszyjnik" },
    { en: "Earrings", pl: "Kolczyki" },
    { en: "Bracelet", pl: "Bransoletka" },
    { en: "Ring", pl: "Pierścionek" },
    { en: "Glasses", pl: "Okulary" },
    { en: "Make-up", pl: "Makijaż" },
    { en: "Hairdresser's", pl: "Fryzjer" },
    { en: "Haircut", pl: "Strzyżenie" },
    { en: "To get a haircut", pl: "Ostrzyc się" },
    { en: "Fringe / Bangs", pl: "Grzywka" },
    { en: "Ponytail", pl: "Kucyk" },
    { en: "Curly hair", pl: "Kręcone włosy" },
    { en: "Straight hair", pl: "Proste włosy" },
    { en: "Blonde", pl: "Blond" },
    { en: "Dark-haired", pl: "Ciemnowłosy" },
    { en: "Tall", pl: "Wysoki" },
    { en: "Short", pl: "Niski" },
    { en: "Slim", pl: "Szczupły" },
    { en: "Good-looking", pl: "Przystojny" },
    { en: "Pretty", pl: "Ładna" },
    { en: "Casual", pl: "Na luzie, codzienny" },
    { en: "Smart / Formal", pl: "Elegancki, oficjalny" },
    { en: "Trendy", pl: "Modny" },
    { en: "Old-fashioned", pl: "Staroświecki" },
    { en: "Comfortable", pl: "Wygodny" },
    { en: "Tight", pl: "Obcisły" },
    { en: "Baggy", pl: "Luźny, workowaty" },
    { en: "Striped", pl: "W paski" },
    { en: "Checked", pl: "W kratę" },
    { en: "Spotted / Polka-dot", pl: "W groszki" },
    { en: "Plain", pl: "Gładki, bez wzoru" },
    { en: "Cotton", pl: "Bawełna" }
  ],
  ocio: [
    { en: "Hobby", pl: "Hobby" },
    { en: "Free time activities", pl: "Zajęcia w czasie wolnym" },
    { en: "To go to the cinema", pl: "Iść do kina" },
    { en: "To watch a film / movie", pl: "Obejrzeć film" },
    { en: "Series / TV show", pl: "Serial" },
    { en: "Episode", pl: "Odcinek" },
    { en: "Season (TV)", pl: "Sezon" },
    { en: "Spoiler", pl: "Spoiler" },
    { en: "To binge-watch", pl: "Oglądać seriale ciągiem" },
    { en: "Trailer", pl: "Zwiastun" },
    { en: "Subtitles", pl: "Napisy" },
    { en: "Concert", pl: "Koncert" },
    { en: "Gig", pl: "Mały koncert, występ" },
    { en: "Festival", pl: "Festiwal" },
    { en: "Band", pl: "Zespół muzyczny" },
    { en: "Singer", pl: "Piosenkarz" },
    { en: "Song", pl: "Piosenka" },
    { en: "Playlist", pl: "Playlista" },
    { en: "To dance", pl: "Tańczyć" },
    { en: "To sing", pl: "Śpiewać" },
    { en: "To play the guitar", pl: "Grać na gitarze" },
    { en: "To read a book", pl: "Czytać książkę" },
    { en: "Novel", pl: "Powieść" },
    { en: "To draw", pl: "Rysować" },
    { en: "To paint", pl: "Malować" },
    { en: "To take photos", pl: "Robić zdjęcia" },
    { en: "Video games", pl: "Gry wideo" },
    { en: "Board games", pl: "Gry planszowe" },
    { en: "Cards", pl: "Karty" },
    { en: "Chess", pl: "Szachy" },
    { en: "Puzzle", pl: "Puzzle, łamigłówka" },
    { en: "To go for a walk", pl: "Iść na spacer" },
    { en: "To go hiking", pl: "Chodzić po górach" },
    { en: "To go camping", pl: "Jechać pod namiot" },
    { en: "To go cycling", pl: "Jeździć na rowerze" },
    { en: "To go swimming", pl: "Iść popływać" },
    { en: "To go skating", pl: "Iść na łyżwy, na rolki" },
    { en: "To go shopping", pl: "Iść na zakupy" },
    { en: "To go out for dinner", pl: "Wyjść na kolację" },
    { en: "To go clubbing", pl: "Iść do klubu" },
    { en: "Bowling", pl: "Kręgle" },
    { en: "Escape room", pl: "Escape room" },
    { en: "Theme park", pl: "Park rozrywki" },
    { en: "Zoo", pl: "Zoo" },
    { en: "Aquarium", pl: "Akwarium" },
    { en: "Exhibition", pl: "Wystawa" },
    { en: "Ticket office", pl: "Kasa biletowa" }
  ],
  deporte: [
    { en: "Football / Soccer", pl: "Piłka nożna" },
    { en: "Basketball", pl: "Koszykówka" },
    { en: "Tennis", pl: "Tenis" },
    { en: "Match / Game", pl: "Mecz" },
    { en: "Player", pl: "Zawodnik" },
    { en: "Referee", pl: "Sędzia" },
    { en: "To score", pl: "Strzelić gola" },
    { en: "To win", pl: "Wygrać" },
    { en: "To lose", pl: "Przegrać" },
    { en: "To draw / tie", pl: "Zremisować" },
    { en: "Draw", pl: "Remis" },
    { en: "Score", pl: "Wynik" },
    { en: "Half-time", pl: "Przerwa" },
    { en: "Extra time", pl: "Dogrywka" },
    { en: "Penalty", pl: "Rzut karny" },
    { en: "Offside", pl: "Spalony" },
    { en: "Yellow card", pl: "Żółta kartka" },
    { en: "Red card", pl: "Czerwona kartka" },
    { en: "League", pl: "Liga" },
    { en: "Cup", pl: "Puchar" },
    { en: "Final (match)", pl: "Finał" },
    { en: "Semi-final", pl: "Półfinał" },
    { en: "Champion", pl: "Mistrz" },
    { en: "Fans / Supporters", pl: "Kibice" },
    { en: "Away game", pl: "Mecz wyjazdowy" },
    { en: "Home game", pl: "Mecz u siebie" },
    { en: "Training", pl: "Trening" },
    { en: "Pitch / Field", pl: "Boisko" },
    { en: "Court", pl: "Kort, boisko" },
    { en: "Fight (UFC)", pl: "Walka (UFC)" },
    { en: "Fighter", pl: "Zawodnik, wojownik" },
    { en: "Knockout", pl: "Nokaut" },
    { en: "Title fight", pl: "Walka o pas" },
    { en: "Weight class", pl: "Kategoria wagowa" },
    { en: "Round (sport)", pl: "Runda" },
    { en: "Undefeated", pl: "Niepokonany" },
    { en: "Rematch", pl: "Rewanż" },
    { en: "Treadmill", pl: "Bieżnia" },
    { en: "Weights", pl: "Ciężary" },
    { en: "Personal best", pl: "Rekord życiowy" },
    { en: "Marathon", pl: "Maraton" },
    { en: "Race", pl: "Bieg, wyścig" }
  ]
};
