/* =============================================================
   TESTI DELLA PAGINA (italiano)
   Sostituiscono i testi spagnoli predefiniti di index.html.
   {0}, {1}, {2}: valori inseriti dalla pagina (numeri, nomi, date).
   ============================================================= */

window.TEXTOS = {
  locale: "it-IT",
  errConfig: "Impossibile leggere config.js. Controlla virgole e virgolette in quel file.",
  horaLocal: "Ora locale", cambiarVersion: "Cambia paese", bandera: "Bandiera di {0}",
  calendario: "Calendario", mesAnt: "Mese precedente", mesSig: "Mese successivo", hoy: "Oggi", manana: "Domani",
  festivoDe: "Festivo {0}", legPrev: "Festivo previsto", familia: "Famiglia", diaSenalado: "Ricorrenza", evento: "Evento", escolar: "Scuola",
  proximas: "Prossime date", expresiones: "Espressioni utili", repaso: "Ripasso", reiniciar: "Azzera imparate",
  actualizar: "Aggiorna ora", actualizado: "Aggiornato alle {0} ({1})", tocaCerrar: "Tocca per chiudere",
  conversor: "Convertitore", queConvertir: "Cosa convertire", solAire: "Sole e aria",
  deDiferencia: "di differenza", mismaHora: "stessa ora", sinConexion: "Senza connessione", sinDatos: "Nessun dato",
  horaEn: "{0} a {1}", horaEnPais: "{0} in {1}",
  haceMin: "{0} min fa", haceH: "{0} h fa", haceDias: "{0} giorni fa",
  wmo: {
    "0": "Sereno", "1": "Poco nuvoloso", "2": "Parzialmente nuvoloso", "3": "Coperto", "45": "Nebbia", "48": "Nebbia con brina",
    "51": "Pioviggine debole", "53": "Pioviggine", "55": "Pioviggine intensa", "56": "Pioviggine gelata", "57": "Pioviggine gelata intensa",
    "61": "Pioggia debole", "63": "Pioggia", "65": "Pioggia forte", "66": "Pioggia gelata", "67": "Pioggia gelata forte",
    "71": "Neve debole", "73": "Neve", "75": "Neve forte", "77": "Neve granulosa",
    "80": "Rovesci deboli", "81": "Rovesci", "82": "Rovesci forti", "85": "Rovesci di neve", "86": "Rovesci di neve forti",
    "95": "Temporale", "96": "Temporale con grandine", "99": "Temporale con grandine forte"
  },
  max: "Max", min: "Min", ahora: "Ora", sensacion: "percepita", lluvia: "pioggia", lluviaDia: "Pioggia",
  amanece: "alba", anochece: "tramonto", deLuz: "{0} h {1} min di luce", sensMin: "Perc. min", sinNieve: "Niente neve", nieve: "Neve",
  tiempoEn: "Meteo a {0}", cargandoTiempo: "Caricamento meteo…", horaAHora: "Oggi ora per ora", proximosDias: "Prossimi giorni",
  prevGuardada: "Senza connessione: previsioni salvate {0}",
  errTiempo: "Impossibile caricare il meteo e non ci sono previsioni salvate. Premi Aggiorna ora.",
  meses: ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"],
  iniciales: ["L", "M", "M", "G", "V", "S", "D"], diaDe: "{0} {1}", esHoyAria: ", oggi",
  tagFest: "Fest", tagFam: "Fam", tagEvt: "Evt", tagEsc: "Scuola", tagDia: "Ric",
  rango: "dal {0} al {1}", fechaConfirmar: "data da confermare", datoOnline: "dato online", porConfirmar: "da confermare",
  horaConfirmar: "orario da confermare",
  fuenteOnline: " · fonte online (Nager.Date)", pendConfirmar: ", da confermare", pendConfirmarCon: ", da confermare con {0}",
  previsto: " · previsto, senza calendario ufficiale caricato", pendAprob: " · in attesa di approvazione",
  calEscolar: "Calendario scolastico", nadaMarcado: "Niente segnato per questo giorno.", santoral: "Santo del giorno:",
  warnFestivos: "Mancano i festivi ufficiali di {0} per il {1} in config.js.",
  warnFestivosSig: "Il calendario dei festivi del {0} dovrebbe essere già pubblicato ({1}): aggiungilo a config.js.",
  warnEscolar: "Manca il calendario scolastico{0} del prossimo anno in config.js.", deX: " di {0}",
  warnEventos: "Non ci sono più eventi futuri in config.js.",
  warnPartidos: "Non ci sono più partite dei {0}: aggiungi il calendario della nuova stagione a config.js.",
  stPartidos: "Partite online {0}", stPartidosCopia: "Fonte delle partite non raggiungibile: si usa la copia di {0}",
  stPartidosConfig: "Fonte delle partite non raggiungibile: si usano quelle di config.js",
  stFestivos: "Festivi {0} {1} online", stSinFestivos: "Fonte dei festivi {0} {1} non raggiungibile",
  cambioAdelanta: "Cambio d'ora ({0}): lancette avanti di un'ora", cambioRetrasa: "Cambio d'ora ({0}): lancette indietro di un'ora",
  desdeHoyDif: "da oggi, {0} h di differenza", desdeHoyMisma: "da oggi, stessa ora",
  noFechas: "Nessuna data in arrivo.", porConfirmarParen: " (da confermare)", esHoy: "È oggi!", enCurso: "In corso",
  mes: "mese", mesesN: "mesi", dia: "giorno", dias: "giorni",
  recuerda: "Ricorda. ", enNDias: "Tra {0} giorni",
  felicita: "Fai gli auguri a {0}!", cumpleDe: "Compleanno di {0}",
  aprendidasDe: "Imparate: {0} su {1}.", marcaCirculo: "Segna con il cerchio quelle che conosci già: non usciranno più.",
  marcarAprendida: "Segna come imparata", aprendidasManana: "Imparate: {0}. Da domani non usciranno più.",
  confirmReiniciar: "Vuoi rimettere in rotazione tutte le espressioni segnate come imparate?", tocaVer: "tocca per vedere",
  dolares: "Dollari", millas: "Miglia", kilometros: "Chilometri", fahrenheit: "Fahrenheit", celsius: "Celsius",
  libras: "Libbre", kilos: "Chili", onzas: "Once", gramos: "Grammi", pulgadas: "Pollici", centimetros: "Centimetri",
  mph: "Miglia orarie", kmh: "Km orari",
  bMillas: "Miglia / km", bYardas: "Iarde / m", bTazas: "Tazze / ml", tazas: "Tazze (cup)", mililitros: "Millilitri", notaTaza: "Tazza da cucina americana. Sulle etichette nutrizionali si arrotonda a 240 ml.", bGalones: "Galloni / litri", galones: "Galloni", litros: "Litri", notaGalon: "Gallone americano (benzina, latte). Il gallone britannico è 4,55 litri.", yardas: "Iarde", metros: "Metri", bLibras: "Libbre / chili", bOnzas: "Once / grammi", bPulgadas: "Pollici / cm",
  notaOnza: "Oncia di peso. L'oncia liquida (fl oz) è 29,57 ml.",
  cargandoCambio: "Caricamento del tasso di cambio…", bce: "tasso di riferimento BCE", tasaGuardada: "senza connessione: tasso salvato {0}",
  tasaManual: "senza connessione: tasso manuale di config.js, controllalo", sinCambio: "Nessun tasso di cambio: manca la connessione.",
  uvTxt: ["basso", "moderato", "alto", "molto alto", "estremo"],
  aqTxt: ["Buona", "Moderata", "Scarsa per persone sensibili", "Scarsa", "Molto scarsa", "Pericolosa"],
  cargandoAire: "Caricamento aria…", cargandoUV: "Caricamento indice UV…", errUV: "Impossibile caricare l'indice UV.",
  aire: "Aria {0} · {1}", aireSinDatos: "Aria: nessun dato", uvMax: "UV massimo {0} ({1}) verso le {2}. ",
  protSi: "Protezione solare nelle ore gialle o superiori.", protNo: "Non serve una protezione solare particolare.",
  datosGuardados: "Senza connessione: dati salvati {0}. ", uvAria: "Indice UV ora per ora a {0}"
};
