/* =============================================================
   SANTORALE / ONOMASTICI (indicativo)
   Santo o festa principale di ogni giorno secondo il calendario
   cattolico e la tradizione italiana. Può variare tra calendari e diocesi.
   Formato: "MM-GG": "Santo; altro santo"
   ============================================================= */

window.SANTORAL = {
  "01-01": "Maria Santissima Madre di Dio",
  "01-02": "Santi Basilio Magno e Gregorio Nazianzeno",
  "01-03": "Santissimo Nome di Gesù; Santa Genoveffa",
  "01-04": "Sant'Angela da Foligno",
  "01-05": "Sant'Amelia; San Giovanni Nepomuceno Neumann",
  "01-06": "Epifania del Signore",
  "01-07": "San Raimondo di Peñafort",
  "01-08": "San Severino; San Massimo",
  "01-09": "San Giuliano; Sant'Adriano di Canterbury",
  "01-10": "Sant'Aldo; San Guglielmo",
  "01-11": "Sant'Igino papa",
  "01-12": "San Modesto; Sant'Arcadio",
  "01-13": "Sant'Ilario di Poitiers, patrono di Parma",
  "01-14": "San Felice da Nola",
  "01-15": "San Mauro abate; San Paolo eremita",
  "01-16": "San Marcello I papa",
  "01-17": "Sant'Antonio abate",
  "01-18": "Santa Margherita d'Ungheria; Santa Prisca",
  "01-19": "San Mario; San Bassiano",
  "01-20": "San Sebastiano; San Fabiano",
  "01-21": "Sant'Agnese",
  "01-22": "San Vincenzo diacono",
  "01-23": "Sant'Emerenziana; San Giovanni l'Elemosiniere",
  "01-24": "San Francesco di Sales",
  "01-25": "Conversione di San Paolo",
  "01-26": "Santi Timoteo e Tito",
  "01-27": "Sant'Angela Merici",
  "01-28": "San Tommaso d'Aquino",
  "01-29": "San Valerio; San Costanzo",
  "01-30": "Santa Martina; Santa Giacinta Marescotti",
  "01-31": "San Giovanni Bosco",
  "02-01": "Santa Verdiana; San Severo",
  "02-02": "Presentazione del Signore (Candelora)",
  "02-03": "San Biagio",
  "02-04": "San Gilberto; Santa Giovanna di Valois",
  "02-05": "Sant'Agata",
  "02-06": "San Paolo Miki e compagni; Santa Dorotea",
  "02-07": "San Riccardo; San Teodoro",
  "02-08": "San Girolamo Emiliani; Santa Giuseppina Bakhita",
  "02-09": "Santa Apollonia",
  "02-10": "Santa Scolastica",
  "02-11": "Beata Vergine Maria di Lourdes",
  "02-12": "Sant'Eulalia; San Benedetto d'Aniane",
  "02-13": "San Benigno; Santa Fosca",
  "02-14": "San Valentino; Santi Cirillo e Metodio",
  "02-15": "Santi Faustino e Giovita",
  "02-16": "Santa Giuliana",
  "02-17": "Santi Sette Fondatori dei Servi di Maria; San Donato",
  "02-18": "Santa Bernadette; San Simone",
  "02-19": "San Corrado Confalonieri; San Mansueto",
  "02-20": "Sant'Eleuterio; Santi Francesco e Giacinta Marto",
  "02-21": "San Pier Damiani",
  "02-22": "Cattedra di San Pietro",
  "02-23": "San Policarpo",
  "02-24": "San Sergio; San Modesto",
  "02-25": "San Cesario; San Gerlando",
  "02-26": "San Porfirio; Sant'Alessandro",
  "02-27": "San Gabriele dell'Addolorata",
  "02-28": "San Romano; Sant'Ilario papa",
  "02-29": "San Giovanni Cassiano",
  "03-01": "Sant'Albino; San Felice III papa",
  "03-02": "Sant'Agnese di Boemia; San Quinto",
  "03-03": "Santa Cunegonda",
  "03-04": "San Casimiro; San Lucio",
  "03-05": "San Giovanni Giuseppe della Croce; Sant'Adriano",
  "03-06": "Santa Coletta; San Marciano",
  "03-07": "Sante Perpetua e Felicita",
  "03-08": "San Giovanni di Dio",
  "03-09": "Santa Francesca Romana; San Domenico Savio",
  "03-10": "San Simplicio papa; San Macario",
  "03-11": "San Costantino; San Sofronio",
  "03-12": "San Massimiliano; San Luigi Orione",
  "03-13": "Santa Patrizia; Sant'Eufrasia",
  "03-14": "Santa Matilde",
  "03-15": "Santa Luisa de Marillac; San Longino",
  "03-16": "Sant'Eriberto; Sant'Ilario di Aquileia",
  "03-17": "San Patrizio",
  "03-18": "San Cirillo di Gerusalemme; Sant'Anselmo di Lucca",
  "03-19": "San Giuseppe",
  "03-20": "San Claudio; Sant'Alessandra",
  "03-21": "San Nicola di Flüe; San Serapione",
  "03-22": "Santa Lea; San Benvenuto",
  "03-23": "San Turibio de Mogrovejo; Santa Rebecca",
  "03-24": "Santa Caterina di Svezia; San Romolo",
  "03-25": "Annunciazione del Signore",
  "03-26": "San Teodoro; Sant'Emanuele",
  "03-27": "San Ruperto; Sant'Augusta",
  "03-28": "San Sisto III papa; San Castore",
  "03-29": "San Secondo; San Bertoldo",
  "03-30": "San Giovanni Climaco; San Leonardo Murialdo",
  "03-31": "San Beniamino; Santa Balbina",
  "04-01": "Sant'Ugo; San Valerico",
  "04-02": "San Francesco di Paola",
  "04-03": "San Riccardo; San Sisto I papa",
  "04-04": "Sant'Isidoro di Siviglia",
  "04-05": "San Vincenzo Ferrer",
  "04-06": "San Guglielmo; San Prudenzio",
  "04-07": "San Giovanni Battista de La Salle",
  "04-08": "San Dionigi; Santa Giulia Billiart",
  "04-09": "Santa Maria di Cleofa; San Demetrio",
  "04-10": "San Terenzio; Sant'Ezechiele",
  "04-11": "San Stanislao; Santa Gemma Galgani",
  "04-12": "San Giulio I papa; San Zeno di Verona",
  "04-13": "San Martino I papa; Sant'Ermenegildo",
  "04-14": "San Lamberto; Santa Liduina",
  "04-15": "Santa Anastasia; San Damiano de Veuster",
  "04-16": "Santa Bernadette Soubirous; San Benedetto Giuseppe Labre",
  "04-17": "Sant'Aniceto papa; San Roberto",
  "04-18": "San Galdino; Sant'Apollonio",
  "04-19": "Sant'Emma; San Leone IX papa",
  "04-20": "Sant'Adalgisa; Sant'Agnese di Montepulciano",
  "04-21": "Sant'Anselmo d'Aosta",
  "04-22": "San Caio papa; San Sotero",
  "04-23": "San Giorgio; Sant'Adalberto",
  "04-24": "San Fedele da Sigmaringen; San Benedetto Menni",
  "04-25": "San Marco evangelista",
  "04-26": "San Cleto papa; San Marcellino",
  "04-27": "Santa Zita; San Liberale",
  "04-28": "San Pietro Chanel; San Luigi Maria Grignion de Montfort",
  "04-29": "Santa Caterina da Siena, patrona d'Italia",
  "04-30": "San Pio V papa",
  "05-01": "San Giuseppe lavoratore",
  "05-02": "Sant'Atanasio",
  "05-03": "Santi Filippo e Giacomo apostoli",
  "05-04": "San Ciriaco; San Floriano",
  "05-05": "San Gottardo; Sant'Irene",
  "05-06": "San Domenico Savio; Santa Giuditta",
  "05-07": "Santa Flavia Domitilla; Santa Rosa Venerini",
  "05-08": "Beata Vergine del Rosario di Pompei; San Vittore",
  "05-09": "San Pacomio; San Gregorio Ostiense",
  "05-10": "Sant'Antonino; San Giovanni d'Avila",
  "05-11": "Sant'Ignazio da Laconi; San Fabio",
  "05-12": "Santi Nereo e Achilleo; San Pancrazio",
  "05-13": "Beata Vergine Maria di Fatima",
  "05-14": "San Mattia apostolo",
  "05-15": "San Torquato; Sant'Isidoro agricoltore",
  "05-16": "Sant'Ubaldo; San Simone Stock",
  "05-17": "San Pasquale Baylon",
  "05-18": "San Giovanni I papa; San Felice da Cantalice",
  "05-19": "San Celestino V papa; Sant'Ivo",
  "05-20": "San Bernardino da Siena",
  "05-21": "San Cristoforo Magallanes e compagni; Sant'Eugenio de Mazenod",
  "05-22": "Santa Rita da Cascia",
  "05-23": "San Desiderio; San Giovanni Battista de' Rossi",
  "05-24": "Beata Vergine Maria Ausiliatrice",
  "05-25": "San Beda; San Gregorio VII papa; Santa Maria Maddalena de' Pazzi",
  "05-26": "San Filippo Neri",
  "05-27": "Sant'Agostino di Canterbury",
  "05-28": "Sant'Emilio; San Germano",
  "05-29": "San Paolo VI papa; San Massimino",
  "05-30": "Santa Giovanna d'Arco; San Ferdinando",
  "05-31": "Visitazione della Beata Vergine Maria",
  "06-01": "San Giustino martire",
  "06-02": "Santi Marcellino e Pietro",
  "06-03": "San Carlo Lwanga e compagni",
  "06-04": "San Francesco Caracciolo; San Quirino",
  "06-05": "San Bonifacio",
  "06-06": "San Norberto; San Claudio",
  "06-07": "Sant'Antonio Maria Gianelli; San Roberto",
  "06-08": "San Medardo",
  "06-09": "Sant'Efrem; Santi Primo e Feliciano",
  "06-10": "Beata Diana; San Landerico",
  "06-11": "San Barnaba apostolo",
  "06-12": "San Guido; San Gaspare Bertoni",
  "06-13": "Sant'Antonio di Padova",
  "06-14": "Sant'Eliseo; San Valerio",
  "06-15": "San Vito; Santa Germana",
  "06-16": "Santi Quirico e Giulitta; Sant'Aureliano",
  "06-17": "San Ranieri; Sant'Avito",
  "06-18": "San Gregorio Barbarigo; Santa Marina",
  "06-19": "San Romualdo; Santi Gervasio e Protasio",
  "06-20": "San Silverio papa; Santa Florentina",
  "06-21": "San Luigi Gonzaga",
  "06-22": "San Paolino da Nola; Santi Giovanni Fisher e Tommaso Moro",
  "06-23": "San Giuseppe Cafasso; Sant'Agrippina",
  "06-24": "Natività di San Giovanni Battista",
  "06-25": "San Guglielmo da Vercelli; San Massimo",
  "06-26": "San Vigilio; San Josemaría Escrivá",
  "06-27": "San Cirillo d'Alessandria",
  "06-28": "Sant'Ireneo di Lione",
  "06-29": "Santi Pietro e Paolo",
  "06-30": "Santi Primi Martiri della Chiesa di Roma",
  "07-01": "San Teobaldo; Sant'Aronne",
  "07-02": "San Bernardino Realino; Sant'Ottone",
  "07-03": "San Tommaso apostolo",
  "07-04": "Santa Elisabetta di Portogallo; San Pier Giorgio Frassati",
  "07-05": "Sant'Antonio Maria Zaccaria",
  "07-06": "Santa Maria Goretti",
  "07-07": "San Claudio; San Panteno",
  "07-08": "Santi Aquila e Priscilla; Sant'Adriano III papa",
  "07-09": "Santa Veronica Giuliani; Sant'Agostino Zhao Rong",
  "07-10": "Sante Rufina e Seconda; Sant'Amalberga",
  "07-11": "San Benedetto da Norcia, patrono d'Europa",
  "07-12": "San Fortunato; San Giovanni Gualberto",
  "07-13": "Sant'Enrico; Sant'Eugenio",
  "07-14": "San Camillo de Lellis",
  "07-15": "San Bonaventura",
  "07-16": "Beata Vergine Maria del Monte Carmelo",
  "07-17": "Sant'Alessio; Santa Marcellina",
  "07-18": "San Federico; Santa Marina",
  "07-19": "Sant'Arsenio; Santa Macrina",
  "07-20": "Sant'Elia profeta; Sant'Apollinare",
  "07-21": "San Lorenzo da Brindisi; Santa Prassede",
  "07-22": "Santa Maria Maddalena",
  "07-23": "Santa Brigida di Svezia, patrona d'Europa",
  "07-24": "Santa Cristina; San Charbel Makhlouf",
  "07-25": "San Giacomo apostolo",
  "07-26": "Santi Gioacchino e Anna",
  "07-27": "San Pantaleone; Santa Natalia",
  "07-28": "Santi Nazario e Celso; San Vittore I papa",
  "07-29": "Santi Marta, Maria e Lazzaro",
  "07-30": "San Pietro Crisologo",
  "07-31": "Sant'Ignazio di Loyola",
  "08-01": "Sant'Alfonso Maria de' Liguori",
  "08-02": "Sant'Eusebio di Vercelli; San Pietro Giuliano Eymard",
  "08-03": "Santa Lidia; Sant'Aspreno",
  "08-04": "San Giovanni Maria Vianney, curato d'Ars",
  "08-05": "Madonna della Neve (Dedicazione di Santa Maria Maggiore)",
  "08-06": "Trasfigurazione del Signore",
  "08-07": "San Gaetano da Thiene; San Sisto II papa",
  "08-08": "San Domenico di Guzmán",
  "08-09": "Santa Teresa Benedetta della Croce (Edith Stein), patrona d'Europa",
  "08-10": "San Lorenzo martire",
  "08-11": "Santa Chiara d'Assisi",
  "08-12": "Santa Giovanna Francesca de Chantal",
  "08-13": "Santi Ponziano e Ippolito",
  "08-14": "San Massimiliano Kolbe",
  "08-15": "Assunzione della Beata Vergine Maria",
  "08-16": "San Rocco; Santo Stefano d'Ungheria",
  "08-17": "San Giacinto; Santa Chiara della Croce",
  "08-18": "Sant'Elena",
  "08-19": "San Giovanni Eudes; San Ludovico di Tolosa",
  "08-20": "San Bernardo di Chiaravalle",
  "08-21": "San Pio X papa",
  "08-22": "Beata Vergine Maria Regina",
  "08-23": "Santa Rosa da Lima",
  "08-24": "San Bartolomeo apostolo",
  "08-25": "San Luigi IX re di Francia; San Giuseppe Calasanzio",
  "08-26": "Sant'Alessandro di Bergamo; Santa Teresa di Gesù Jornet",
  "08-27": "Santa Monica",
  "08-28": "Sant'Agostino",
  "08-29": "Martirio di San Giovanni Battista; Santa Sabina",
  "08-30": "Santi Felice e Adautto",
  "08-31": "Sant'Aristide; San Raimondo Nonnato",
  "09-01": "Sant'Egidio",
  "09-02": "Sant'Elpidio; Sant'Ingrid",
  "09-03": "San Gregorio Magno",
  "09-04": "Santa Rosalia; Santa Rosa da Viterbo",
  "09-05": "Santa Teresa di Calcutta",
  "09-06": "San Zaccaria profeta; Sant'Umberto",
  "09-07": "Santa Regina; San Grato",
  "09-08": "Natività della Beata Vergine Maria",
  "09-09": "San Pietro Claver; San Sergio I papa",
  "09-10": "San Nicola da Tolentino",
  "09-11": "Santi Proto e Giacinto",
  "09-12": "Santissimo Nome di Maria",
  "09-13": "San Giovanni Crisostomo",
  "09-14": "Esaltazione della Santa Croce",
  "09-15": "Beata Vergine Maria Addolorata",
  "09-16": "Santi Cornelio e Cipriano",
  "09-17": "San Roberto Bellarmino; Santa Ildegarda di Bingen",
  "09-18": "San Giuseppe da Copertino",
  "09-19": "San Gennaro",
  "09-20": "Santi Andrea Kim Taegon e compagni",
  "09-21": "San Matteo apostolo ed evangelista",
  "09-22": "San Maurizio; San Tommaso da Villanova",
  "09-23": "San Pio da Pietrelcina",
  "09-24": "San Pacifico; San Gerardo Sagredo",
  "09-25": "San Cleofa; San Sergio di Radonež",
  "09-26": "Santi Cosma e Damiano",
  "09-27": "San Vincenzo de' Paoli",
  "09-28": "San Venceslao; San Lorenzo Ruiz e compagni",
  "09-29": "Santi Arcangeli Michele, Gabriele e Raffaele",
  "09-30": "San Girolamo",
  "10-01": "Santa Teresa di Gesù Bambino",
  "10-02": "Santi Angeli Custodi",
  "10-03": "San Gerardo di Brogne; San Candido",
  "10-04": "San Francesco d'Assisi, patrono d'Italia",
  "10-05": "San Placido; Santa Faustina Kowalska",
  "10-06": "San Bruno",
  "10-07": "Beata Vergine Maria del Rosario",
  "10-08": "Santa Reparata; Santa Pelagia",
  "10-09": "San Dionigi e compagni; San Giovanni Leonardi",
  "10-10": "San Daniele Comboni; San Francesco Borgia",
  "10-11": "San Giovanni XXIII papa",
  "10-12": "San Serafino; San Massimiliano di Lorch",
  "10-13": "Sant'Edoardo; San Teofilo",
  "10-14": "San Callisto I papa",
  "10-15": "Santa Teresa d'Avila",
  "10-16": "Santa Margherita Maria Alacoque; Santa Edvige",
  "10-17": "Sant'Ignazio di Antiochia",
  "10-18": "San Luca evangelista",
  "10-19": "San Paolo della Croce; Santi Giovanni de Brébeuf e compagni",
  "10-20": "Santa Irene; Sant'Adelina",
  "10-21": "Sant'Orsola; San Gaspare del Bufalo",
  "10-22": "San Giovanni Paolo II papa",
  "10-23": "San Giovanni da Capestrano",
  "10-24": "Sant'Antonio Maria Claret",
  "10-25": "Santi Crisante e Daria",
  "10-26": "Sant'Evaristo papa; San Folco",
  "10-27": "San Fiorenzo; Santa Sabina",
  "10-28": "Santi Simone e Giuda apostoli",
  "10-29": "Sant'Ermelinda; San Narciso",
  "10-30": "San Germano di Capua; San Marciano",
  "10-31": "San Quintino; Sant'Alfonso Rodriguez",
  "11-01": "Tutti i Santi",
  "11-02": "Commemorazione di tutti i fedeli defunti",
  "11-03": "San Martino de Porres; Santa Silvia",
  "11-04": "San Carlo Borromeo",
  "11-05": "Santi Zaccaria ed Elisabetta",
  "11-06": "San Leonardo di Noblac",
  "11-07": "San Prosdocimo; Sant'Ernesto",
  "11-08": "San Goffredo; Santi Quattro Coronati",
  "11-09": "Dedicazione della Basilica Lateranense",
  "11-10": "San Leone Magno papa",
  "11-11": "San Martino di Tours",
  "11-12": "San Giosafat",
  "11-13": "Sant'Omobono; San Diego",
  "11-14": "San Giocondo; San Lorenzo O'Toole",
  "11-15": "Sant'Alberto Magno",
  "11-16": "Santa Margherita di Scozia; Santa Gertrude",
  "11-17": "Santa Elisabetta d'Ungheria",
  "11-18": "Dedicazione delle Basiliche dei Santi Pietro e Paolo; Sant'Oddone",
  "11-19": "San Fausto; Sant'Abdia",
  "11-20": "Sant'Ottavio; Sant'Edmondo",
  "11-21": "Presentazione della Beata Vergine Maria",
  "11-22": "Santa Cecilia",
  "11-23": "San Clemente I papa; San Colombano",
  "11-24": "Santi Andrea Dung-Lac e compagni; Santa Flora",
  "11-25": "Santa Caterina d'Alessandria",
  "11-26": "San Leonardo da Porto Maurizio; San Corrado",
  "11-27": "San Virgilio di Salisburgo",
  "11-28": "San Giacomo della Marca",
  "11-29": "San Saturnino; San Francesco Antonio Fasani",
  "11-30": "Sant'Andrea apostolo",
  "12-01": "Sant'Eligio; Sant'Ansano",
  "12-02": "Santa Bibiana",
  "12-03": "San Francesco Saverio",
  "12-04": "Santa Barbara; San Giovanni Damasceno",
  "12-05": "San Saba; San Giulio",
  "12-06": "San Nicola di Bari",
  "12-07": "Sant'Ambrogio",
  "12-08": "Immacolata Concezione",
  "12-09": "San Siro; San Juan Diego",
  "12-10": "Beata Vergine Maria di Loreto",
  "12-11": "San Damaso I papa",
  "12-12": "Beata Vergine Maria di Guadalupe",
  "12-13": "Santa Lucia",
  "12-14": "San Giovanni della Croce",
  "12-15": "Santa Virginia Centurione Bracelli; San Valeriano",
  "12-16": "Sant'Adelaide; Santa Albina",
  "12-17": "San Lazzaro; San Giovanni de Matha",
  "12-18": "San Graziano; San Malachia",
  "12-19": "Sant'Anastasio I papa; Sant'Urbano V papa",
  "12-20": "San Liberato; San Domenico di Silos",
  "12-21": "San Pietro Canisio",
  "12-22": "Santa Francesca Saverio Cabrini",
  "12-23": "San Giovanni da Kęty; Santa Vittoria",
  "12-24": "Sant'Adele; Santa Irmina",
  "12-25": "Natale del Signore",
  "12-26": "Santo Stefano primo martire",
  "12-27": "San Giovanni apostolo ed evangelista",
  "12-28": "Santi Innocenti martiri",
  "12-29": "San Tommaso Becket; San Davide re",
  "12-30": "San Ruggero; Sant'Eugenio",
  "12-31": "San Silvestro I papa"
};
